For each NACE Class get the 100 chunks that scored highest across all the reports

In [1]:
import pandas as pd
import glob
import os
import tqdm
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append("..")

wor_dir = "/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis"
os.chdir(wor_dir)
#wor_dir =" "
from test_base import *

In [2]:
overview_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/stoxx_600_overview.csv"
overview_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv"
overview_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv"
overview_path = wor_dir + "/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv"

In [3]:
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_3_min_chunk_len_100_cos_thresh_0.4_nace_level_2_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_3_min_chunk_len_100_cos_thresh_0.4_nace_level_2_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_3_min_chunk_len_0_cos_thresh_0.4_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/tables_cos_sim_0.0_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/sentence_len_5/paragraph_and_sentence_len_5_min_chunk_len_100_cos_thresh_0.4_nace_level_2_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/sentence_len_5/paragraph_and_sentence_len_5_min_chunk_len_100_cos_thresh_0.4_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_6_min_chunk_len_100_cos_thresh_0.4_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_4/"

raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2/"
raw_data_path = wor_dir + "/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_4/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_3_1/"
raw_data_path = wor_dir + "/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1/"

In [4]:
reports = glob.glob(raw_data_path + "*/*_long.csv")
reports = glob.glob(raw_data_path + "*/*_short.csv")
len(reports)

1556

In [5]:
sample_ratio = 1

In [6]:
max_elements_per_class = 1000000

top_k_sentences = 200000

In [7]:
# if true, adds only chunks to training that have been classified into the same NACE class its report comes from
filter_only_right_chunks = True

In [8]:
# if true, adds random chunks that do not fulfill the minimum treshold (for BERT Training)
with_null_classifiers = True

In [9]:
new_threshold_cos_sin = 0.45

In [10]:
nace_level_descriptions = 1
nace_level = 1
assert nace_level_descriptions >= nace_level

In [11]:
training_data_path = "data/training_data/approach_1"

In [12]:
suffix = f"sample_ratio_{sample_ratio}" + ("__filter_only_right_chunks" if filter_only_right_chunks else "") + ("__with_null_classifiers" if with_null_classifiers else "") + f"__nace_level_{nace_level}" + f"__cos_thres_{new_threshold_cos_sin}"

# "_subsample" if sample_ratio != 1 else ""
# end_path = os.path.join("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/test_read_training_data_right_classifications", raw_data_path.split("/")[-2] + suffix)
# end_path = os.path.join("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/test_read_training_data", raw_data_path.split("/")[-2] + suffix + "_with_no_class__cos_sim_04")
# end_path = os.path.join("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/test_read_training_data_right_classifications", raw_data_path.split("/")[-2] + suffix + "_with_no_class__cos_sim_04")

end_path = os.path.join(training_data_path, 
                        raw_data_path.split("/")[-2] + "__" + suffix)
end_path

'data/training_data/approach_1/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1__sample_ratio_1__filter_only_right_chunks__with_null_classifiers__nace_level_1__cos_thres_0.45'

In [13]:
#df_overview = pd.read_excel(overview_path)
df_overview = pd.read_csv(overview_path)
df_overview

,Unnamed: 0,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,...,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report
0,5789,ZW0009011041,Ariston Holdings Ltd.,1,1947.0,ZWE,V97772103,20090317.0,ZWE,@NA,...,ZW0009011041,603408,Ariston Holdings Ltd.,1.0,ARIS-ZW,1,SHARE,6034081,A,Ariston Holdings Ltd.1.pdf
1,35816,INE978A01027,Heritage Foods Limited,1,1992.0,IND,Y3179H146,20020117.0,IND,06FQLY-E,...,INE978A01027,BF2F40,Heritage Foods Limited,1.0,519552-IN,1,SHARE,BF2F405,A,Heritage Foods Limited1.pdf
2,80373,MYL7854OO002,Timberwell Bhd.,1,1996.0,MYS,Y88399103,19970516.0,MYS,05JH15-E,...,MYL7854OO002,690556,Timberwell Bhd.,1.0,7854-MY,1,SHARE,6905563,A,Timberwell Bhd.1.pdf
3,49813,MYQ0189OO009,Matang Bhd.,1,2015.0,MYS,Y58347108,20170117.0,MYS,@NA,...,MYQ0189OO009,BYYQB5,Matang Bhd.,1.0,0189-MY,1,SHARE,BYYQB53,A,Matang Bhd.2.pdf
4,73064,MYL4316OO005,Sin Heng Chan (Malaya) Bhd.,1,1962.0,MYS,Y80178109,19880324.0,MYS,05YMQ5-E,...,MYL4316OO005,681088,Sin Heng Chan (Malaya) Bhd.,1.0,4316-MY,1,SHARE,6810883,A,Sin Heng Chan (Malaya) Bhd.1.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,5783,US0404432025,Aristocrat Group Corp.,0,2011.0,USA,040443202,20120313.0,USA,00DDP9-E,...,US0404432025,04044320,Aristocrat Group Corp.,1.0,ASCC-US,1,SHARE,BWX6257,S,Aristocrat Group Corp.1.pdf
1558,73228,KYG816BW1095,Sino-Life Group Limited,1,2005.0,HKG,G816BW109,20090909.0,HKG,00C60C-E,...,KYG816BW1095,B409GR,Sino-Life Group Limited,1.0,8296-HK,1,SHARE,B409GR3,S,Sino-Life Group Limited1.pdf
1559,86319,KYG9477E1070,Water Oasis Group Limited,1,1998.0,HKG,G9477E107,20070905.0,HKG,00610B-E,...,KYG9477E1070,651233,Water Oasis Group Limited,1.0,WOSSF-US,0,SHARE,B02V9Q9,S,Water Oasis Group Limited1.pdf
1560,66027,US76119X1054,"Reservoir Media, Inc.",1,2007.0,USA,76119X105,20210105.0,USA,0NVYZ2-E,...,US76119X1054,76119X10,"Reservoir Media, Inc.",1.0,RSVR-US,1,SHARE,BP0B9H7,S,"Reservoir Media, Inc.1.pdf"
1561,38190,KYG4707P1054,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,@NA,...,KYG4707P1054,BJYFY1,Icon Culture Global Company Limited,1.0,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf

In [14]:
df_nace_codes_descriptions = pd.read_csv("data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", sep="\t")
filter_level_1_classes = "ABCDEFGHIJKLMNOPQRSTUVW"

In [15]:
result = pd.DataFrame(columns=["Sentences", "Score", "NACE_Code"])

# loop over all reports and get the all the sentences 
for report in tqdm.tqdm(reports):

    df = pd.read_csv(report)

    if filter_only_right_chunks: 
        report_name = os.path.basename(report).replace(".txt_short.csv", "") + ".pdf"
        report_code = df_overview[df_overview["Report"]==report_name]["NACE"].iloc[0]
        report_code = get_all_level(report_code)[nace_level]
        if nace_level == nace_level_descriptions: 
            filter_column = list(filter(lambda x: "Scores_"+str(report_code) in x, df.columns))
        else:
            filter_column = []
            for column in df.columns: 
                if "Scores" in column: 
                    if get_all_level(column.split("_")[1])[nace_level]==report_code: 
                        filter_column.append(column)
        df = df[["Sentences"]+filter_column]

    if nace_level == 1: 
        # filter some nace classes
        scores = df[[column for column in df.columns if ("Scores" in column) and get_all_level(column.split("_")[1], df_nace_codes_descriptions)[nace_level] in filter_level_1_classes]].columns
    else: 
        scores = df[[column for column in df.columns if ("Scores" in column)]].columns
    
    for score in scores:
        temp = df[df[score].notna()][["Sentences", score]]  
        try: 
            temp["NACE_Code"] = get_all_level(score.split("_")[1])[nace_level]
        except IndexError: 
            continue
        temp = temp.rename(columns={score: "Score"})
        result = pd.concat([result, temp])

  0%|                                                                                                                                                                                        | 0/1556 [00:00<?, ?it/s]/tmp/ipykernel_192445/934534259.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([result, temp])
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1556/1556 [00:11<00:00, 137.09it/s]

In [16]:
os.makedirs(end_path, exist_ok=True)

In [17]:
recordings = []

In [18]:
# for each code, store the 100 with the highest similarity score to the code

full_df = []
for code in set(result["NACE_Code"].to_list()): 

    #if not get_all_level(code.split("_")[1], df_nace_codes_descriptions)[1] in filter_level_1_classes: 
    # if not get_all_level(code, df_nace_codes_descriptions)[nace_level] in filter_level_1_classes: 
    #     continue

    temp = result[result["NACE_Code"] == code]
    temp = temp.drop_duplicates(subset="Sentences")
    temp = temp[temp["Sentences"].apply(len) >= 100]
    temp = temp.sort_values(by="Score", ascending=False)

    if with_null_classifiers: 
        temp.loc[temp["Score"]<new_threshold_cos_sin, "NACE_Code"] = "NO_CLASS"
        temp = temp[(temp["Score"] >= new_threshold_cos_sin) | (temp["NACE_Code"]=="NO_CLASS")]
        
        class_index = temp[temp["NACE_Code"]!="NO_CLASS"].index
        no_class_index = temp[temp["NACE_Code"]=="NO_CLASS"].index

        print(len(temp[temp["NACE_Code"]=="NO_CLASS"]))
        print(temp[temp["NACE_Code"]=="NO_CLASS"].index)
        print(temp.loc[no_class_index])
        print(code)
        print("--")

        temp = temp.loc[list(np.random.choice(no_class_index, len(class_index)))+list(class_index)]
    else:
        temp = temp[temp["Score"] >= new_threshold_cos_sin]

    number_of_elements_per_class = min(int(sample_ratio*len(temp)), max_elements_per_class, len(temp))
    random_choice = np.random.choice(len(temp), number_of_elements_per_class, replace=False)
    temp = temp.iloc[random_choice]
    temp = temp.sort_values(by="Score", ascending=False)
    temp = temp.iloc[:top_k_sentences, :]
    temp = temp.reset_index(drop=True)
    temp["Evaluation"] = None
    temp["Notes"] = None
    temp = temp[["Evaluation", "Notes", "Sentences", "Score", "NACE_Code"]]

    recordings.append({"Code": code,"Nbr. of Chunks": len(temp),"Avg. Length": temp["Sentences"].apply(len).mean(), "Avg. Score": temp["Score"].mean(), "Min. Score": temp["Score"].min(), "Max. Score": temp["Score"].max()})

    text = ""
    for i, row in temp.iterrows():
        text += f"#{i}, Score: " + str(round(row["Score"], 2)) + "\n\n" + row["Sentences"] + "\n\n"

    with open(os.path.join(end_path, code.replace("/"," ")) + ".txt", "w") as f:
        f.write(text)
    
    temp = temp.drop_duplicates(subset=["Sentences"])
    temp.to_csv(os.path.join(end_path, code.replace("/"," ")) + ".csv")

    full_df.append(temp)

full_df = pd.concat(full_df, axis=0, ignore_index=True)

8006
Index([394, 395,  20,  29, 223, 210, 288, 431, 354, 371,
       ...
       121, 123,   0, 105, 119, 144, 128,  53,  71,   4],
      dtype='int64', length=8006)
                                             Sentences     Score NACE_Code
394  code means the internal revenue code of as ame...  0.468868         G
394  operating and financial review and prospects i...  0.449992  NO_CLASS
394  group at cost at valuation accumulated depreci...  0.439279  NO_CLASS
394  the financial statements are prepared in accor...  0.432489  NO_CLASS
394  renowned for its expertise and experiences in ...  0.425176  NO_CLASS
..                                                 ...       ...       ...
4    gri standard disclosure page numbers direct an...  0.372778  NO_CLASS
4    consolidated statements of operations in thous...  0.364008  NO_CLASS
4    the customer can first go to the store to chec...  0.363518  NO_CLASS
4    civil aviation authority of thailand caat pres...  0.208522  NO_CLASS
4    ltp namp i tuamp vb w b b w ampamp . . b x y x...  0.019260  NO_CLASS

[149607 rows x 3 columns]
G
--
2522
Index([190, 257, 524, 259, 194, 617, 132, 397, 215, 297,
       ...
       263,  78, 235, 420, 109,  39, 444, 223, 258, 451],
      dtype='int64', length=2522)
                                             Sentences     Score NACE_Code
190  other provisions . contract liabilities . othe...  0.449829  NO_CLASS
190  humanas quality management should help reduce ...  0.354168  NO_CLASS
190  risk description risk management mitigation lo...  0.331822  NO_CLASS
190  as of march the company has income tax net ope...  0.328375  NO_CLASS
190  from our very beginnings our company reduced w...  0.316932  NO_CLASS
..                                                 ...       ...       ...
258  in the normal course of business the companys ...  0.287953  NO_CLASS
451  provisions are recognised when the group has a...  0.380859  NO_CLASS
451  government grants related to income that are r...  0.368595  NO_CLASS
451  pursuant to the articles of association where ...  0.348816  NO_CLASS
451  revenues from the sale of physical recorded mu...  0.287428  NO_CLASS

[13090 rows x 3 columns]
S
--
4894
Index([145, 172, 246, 477, 311, 282, 308, 561,   1, 275,
       ...
       212,  31,  13,  85,  44, 233,   3,   1,   4,   0],
      dtype='int64', length=4894)
                                             Sentences     Score NACE_Code
145  phase iii expansion plans may include a potent...  0.449776  NO_CLASS
145  food and beverage income and club activities i...  0.407851  NO_CLASS
145  the board believes that the continuous promoti...  0.364921  NO_CLASS
145  in october dolphin cove organized halloween ce...  0.356933  NO_CLASS
145  vlts for certain customers we provide our mult...  0.325134  NO_CLASS
..                                                 ...       ...       ...
0    the business review of the group for the year ...  0.262131  NO_CLASS
0    grants recognised as profit or loss are deduct...  0.237453  NO_CLASS
0    restated nores cash flows from operating activ...  0.224905  NO_CLASS
0    the group recognises rightofuse assets at the ...  0.196302  NO_CLASS
0    director and secretary of board of directors t...  0.031459  NO_CLASS

[46289 rows x 3 columns]
R
--
6094
Index([343, 331, 180,  31, 222, 146, 426, 337, 551,  88,
       ...
        94, 104, 109,  78,   5, 110, 103,  42,  29,  18],
      dtype='int64', length=6094)
                                             Sentences     Score NACE_Code
343  painting installation of foundations and piles...  0.676639         F
343  usually it takes out builders all risks insura...  0.656816         F
343  we employ ibs techniques comprising the use of...  0.577950         F
343  in accordance with article of the kgc articles...  0.570530         F
343  the company has entered into a build operate a...  0.537929         F
..                                                 ...       ...       ...
18   for the financial year endedending june catego...  0.356979  NO_CLASS
18   the rental revenues of galleria dalian amounte...  0.339314  NO_CLASS
18   investment non sharebased prc non share treasu...  0.312929  NO_CLASS
18   imobilizarile corporale cuprind terenuri si co...  0.302852  NO_CLASS
18   netel commits to sbti in january and undertake...  0.132356  NO_CLASS

[111814 rows x 3 columns]
F
--
4166
Index([548, 219, 553, 340, 158, 373, 443,  83, 473,  92,
       ...
       156, 233,  32, 329, 468, 236, 303, 376, 260, 328],
      dtype='int64', length=4166)
                                             Sentences     Score NACE_Code
548  social talent development and training kpi b. ...  0.449917  NO_CLASS
548  kidzees interactive illume programs being age ...  0.380334  NO_CLASS
548  amount reported includes a in k plan matching ...  0.237155  NO_CLASS
219  group china education limited cel wanbo instit...  0.449859  NO_CLASS
219  tuition and boarding fees received by universi...  0.394074  NO_CLASS
..                                                 ...       ...       ...
328  undertake such other functions and duties as m...  0.289939  NO_CLASS
328  . c divide its shares into several classes and...  0.280309  NO_CLASS
328  there are capital and financial requirements i...  0.262036  NO_CLASS
328  the structure of the incentive arrangements fo...  0.252848  NO_CLASS
328  disclosure regarding foreign jurisdictions tha...  0.209042  NO_CLASS

[38085 rows x 3 columns]
P
--
7179
Index([214,  63, 109, 476, 336,  71, 242,  19, 162, 191,
       ...
       186, 205,  75, 235, 234,  30, 265, 118, 245, 242],
      dtype='int64', length=7179)
                                             Sentences     Score NACE_Code
214  prepayments for acquisition of land use rights...  0.489349         L
214  completed under construction total rmb rmb rmb...  0.468669         L
214  our advisor also receives asset management fee...  0.449995  NO_CLASS
214  the overall property market in malaysia has co...  0.440006  NO_CLASS
214  the prc equity method property development nin...  0.434410  NO_CLASS
..                                                 ...       ...       ...
242  the group controls an entity when it is expose...  0.307275  NO_CLASS
242  management is responsible for the preparation ...  0.307108  NO_CLASS
242  they are stewards. they believe their role is ...  0.302097  NO_CLASS
242  the revised terms usually include extending th...  0.273205  NO_CLASS
242  .ltglyphltcfontpophgptimesnewromangt fccfnegtg... -0.029210  NO_CLASS

[133447 rows x 3 columns]
L
--
8944
Index([760, 353, 413,  48,  12, 259, 328, 368,  74, 480,
       ...
        48, 162, 112, 208, 110,  20,  44, 114,   9,  85],
      dtype='int64', length=8944)
                                             Sentences     Score NACE_Code
760  the group considers operating segment by servi...  0.449970  NO_CLASS
353  the group manages its business on a service di...  0.481399         N
353  in their reports for the financial year compan...  0.457551         N
353  intercompany transactions balances and unreali...  0.449951  NO_CLASS
353  revenue represents the transfer of promised go...  0.432750  NO_CLASS
..                                                 ...       ...       ...
85   in preparing the consolidated financial statem...  0.351313  NO_CLASS
85   he also obtained the qualification as a licens...  0.342962  NO_CLASS
85   ceo cfo chro csmo cio cdo presidents onelining...  0.260194  NO_CLASS
85   b establishes adequate internal controls to sa...  0.247793  NO_CLASS
85   glyphltcfontgpsirvtimesnewromanbolditalicgt lt...  0.024738  NO_CLASS

[156923 rows x 3 columns]
N
--
3314
Index([258, 309,  13, 397,  77, 125, 146, 277, 366, 184,
       ...
       195,  55, 137, 219,  26,  43, 214, 148,  99,  63],
      dtype='int64', length=3314)
                                             Sentences     Score NACE_Code
258  financial assets at fair value through net ear...  0.502111         K
258  . critical accounting estimates and judgments ...  0.497705         K
258  in accordance with ifrs financial liabilities ...  0.497245         K
258  we consider a legal finance asset to be conclu...  0.469580         K
258  as at december cash on hand demand deposits wi...  0.449995  NO_CLASS
..                                                 ...       ...       ...
63   collectively these businesses have added .bn a...  0.428775  NO_CLASS
63   certain of the companys contracts with custome...  0.423894  NO_CLASS
63   the groups holdings of cash and cash equivalen...  0.421211  NO_CLASS
63   brief resume and expertise in specific functio...  0.363858  NO_CLASS
63   glyphltcfontaaallltimesnewromangtbieglyphltcfo...  0.037624  NO_CLASS

[61155 rows x 3 columns]
K
--
8007
Index([ 66, 327,  86, 758, 284, 190, 438, 186, 247, 208,
       ...
        65, 166, 198,  40,  35, 207,  91, 187,  39, 181],
      dtype='int64', length=8007)
                                             Sentences     Score NACE_Code
66   the fair value of livestock is based on its pr...  0.449865  NO_CLASS
66   net assets ownership cash and cash equivalent ...  0.430387  NO_CLASS
66   the present rate of participation for women an...  0.392508  NO_CLASS
66   the produce segment operates in five core cate...  0.388922  NO_CLASS
66   the company has performed a preliminary valuat...  0.380480  NO_CLASS
..                                                 ...       ...       ...
181  in january gotham properties llc an oregon lim...  0.288084  NO_CLASS
181  we are at an important point as we are operati...  0.267482  NO_CLASS
181  due to the covid pandemic the global basmati r...  0.255849  NO_CLASS
181  for the year ended may change vs. change vs. e...  0.255085  NO_CLASS
181  training course target attendees month venue n...  0.165680  NO_CLASS

[127048 rows x 3 columns]
A
--
9149
Index([279, 416, 521, 238, 147,  80, 243, 214, 349, 145,
       ...
       381,  43,  67, 116, 351,  13, 276, 193,   6,  44],
      dtype='int64', length=9149)
                                             Sentences     Score NACE_Code
279  we believe that our expertise in earlystage dr...  0.465801         M
279  the knowledge and expertise of colleagues ensu...  0.455623         M
279  for more information about how we help our peo...  0.449973  NO_CLASS
279  professional ability business management leade...  0.433441  NO_CLASS
279  highlights page occupational safety amp health...  0.414186  NO_CLASS
..                                                 ...       ...       ...
44   we seek kind smart and creative individuals to...  0.318006  NO_CLASS
44   total costs incurred with construction contrac...  0.310074  NO_CLASS
44   revenue from the rendering of services are rec...  0.303230  NO_CLASS
44   as part of our audit in accordance with the ap...  0.293063  NO_CLASS
44   auditors responsibilities for the audit of the...  0.264685  NO_CLASS

[170396 rows x 3 columns]
M
--
6202
Index([386, 485,  41, 351, 167, 100, 394, 168, 299, 235,
       ...
       172, 182, 154, 160, 239, 149,  43, 120, 234, 109],
      dtype='int64', length=6202)
                                             Sentences     Score NACE_Code
386  also there are initiatives in order to promote...  0.572010         D
386  useful life in years buildings technical plant...  0.545251         D
386  pursuant to resolution of the rf government no...  0.492216         D
386  changes in technology particularly with respec...  0.478954         D
386  this was supported through an advanced distrib...  0.473380         D
..                                                 ...       ...       ...
109  during we integrated our capabilities within r...  0.367134  NO_CLASS
109  we have various firm transportation and gas pr...  0.363601  NO_CLASS
109  in addition to procedures and measures trainin...  0.332067  NO_CLASS
109  the consolidated entity designates only the sp...  0.303168  NO_CLASS
109  nisource calculates retention as the total num...  0.144867  NO_CLASS

[105582 rows x 3 columns]
D
--
8664
Index([247, 293, 111, 167,  92,  78, 284, 258, 263,  99,
       ...
        38, 118,  13, 353, 294,  57, 202, 103, 316, 219],
      dtype='int64', length=8664)
                                             Sentences     Score NACE_Code
247  iii new york hotel trades council and hotel as...  0.449970  NO_CLASS
247  when a contract contains lease and nonlease co...  0.443004  NO_CLASS
247  group purchase of plant and equipment note les...  0.442657  NO_CLASS
247  as the wellbeing of the guests employees and o...  0.441336  NO_CLASS
247  the total number of magnificent hotel shares i...  0.426097  NO_CLASS
..                                                 ...       ...       ...
219  we provided vfx services for advertisements sp...  0.336373  NO_CLASS
219  our dependence on a sole supplier or a limited...  0.319484  NO_CLASS
219  page corporate information chairmans statement...  0.314030  NO_CLASS
219  aspek tpb sdg aspects keterangan description m...  0.312651  NO_CLASS
219  pt sofia berkah abadi memiliki dan mengoperasi...  0.272463  NO_CLASS

[158117 rows x 3 columns]
I
--
2831
Index([340, 218,  45, 216, 403, 155, 550, 118, 237, 310,
       ...
        21, 192,  53,  35, 218, 202,  75, 176,  80, 240],
      dtype='int64', length=2831)
                                             Sentences     Score NACE_Code
340  assessed managements determination of costs at...  0.646452         E
340  the headquarters had generated kg of paper was...  0.572142         E
340  we strictly control the effluent quality throu...  0.521064         E
340  the revenue under the other segment included r...  0.462689         E
340  although we believe that further governmental ...  0.453189         E
..                                                 ...       ...       ...
240  ending balance iii. provision for impairment ....  0.388192  NO_CLASS
240  an intangible asset is derecognised on disposa...  0.376145  NO_CLASS
240  we generally compete for contracts with severa...  0.342144  NO_CLASS
240  we conduct supply chain assessments when consi...  0.323707  NO_CLASS
240  employees are afforded their rights as outline...  0.268971  NO_CLASS

[25486 rows x 3 columns]
E
--
9181
Index([399, 374, 193, 221,   9, 410, 456, 501, 231, 288,
       ...
       188, 226, 263,   5,  84, 314, 248, 307, 123, 239],
      dtype='int64', length=9181)
                                             Sentences     Score NACE_Code
399  on march the sapprft issued the provisional im...  0.497035         J
399  on august shanghai yueting on behalf of t h e ...  0.449859  NO_CLASS
399  iii participant acknowledges that all notes me...  0.405161  NO_CLASS
399  sebagai penyedia solusi pencetakan endtoend gc...  0.394291  NO_CLASS
399  th th th operating revenue revenue operating e...  0.391131  NO_CLASS
..                                                 ...       ...       ...
239  deferred income tax liabilities property plant...  0.289454  NO_CLASS
239  provisions are recognised when the group has a...  0.270359  NO_CLASS
239  fair value as of december recurring fair value...  0.264017  NO_CLASS
239  our procedures amongst other included obtainin...  0.262681  NO_CLASS
239  ltfiglyphltcfontaaaabefontadgt.glyphltcfontaaa...  0.124784  NO_CLASS

[165134 rows x 3 columns]
J
--
87
Index([362, 125, 100, 407, 220, 275, 117,  36,   5, 269, 105, 301,   8,   9,
       195, 302,  84,  25, 201, 152, 397, 392, 218,  32, 240, 127, 291, 162,
        56, 177, 425, 176, 204, 315, 332, 378, 364, 103,  88, 179, 128, 251,
        91, 141,  64, 319,  85, 165, 417, 213,  92, 120, 279, 345, 331, 223,
       386, 123, 161, 200, 178, 239, 382, 347, 256, 436,  28,  54, 252,  48,
       184, 268, 341, 222, 198, 234, 155,  77, 277, 217, 430, 289, 243,  69,
        42, 131,  13],
      dtype='int64')
                                             Sentences     Score NACE_Code
362  as at december the group had a total of as at ...  0.447861  NO_CLASS
125  categories gender male female age group age or...  0.435191  NO_CLASS
100  the details of workforce composition of the gr...  0.431959  NO_CLASS
407  human resources serve as the foundation for th...  0.425580  NO_CLASS
220  as mentioned in the section headed recruitment...  0.424078  NO_CLASS
..                                                 ...       ...       ...
243  the board has established three committees nam...  0.338319  NO_CLASS
69   disaggregation of revenue from contracts with ...  0.337567  NO_CLASS
42   during the year the groups revenue amounted to...  0.337055  NO_CLASS
131  each of the independent nonexecutive directors...  0.336278  NO_CLASS
13   during the year approximately approximately of...  0.335508  NO_CLASS

[87 rows x 3 columns]
T
--
8731
Index([ 35, 416, 371, 342, 241, 426, 388, 175, 213, 265,
       ...
       123, 255, 231, 260, 444, 207, 191, 107,  68,  45],
      dtype='int64', length=8731)
                                            Sentences     Score NACE_Code
35  to provide a riskfree living environment to el...  0.449862  NO_CLASS
35  in the medical committee carried out its dutie...  0.409154  NO_CLASS
35  this year we will be delivering care at lauris...  0.403687  NO_CLASS
35  meanwhile in order to show our care to female ...  0.369759  NO_CLASS
35  to perform tasks as assigned by the board of d...  0.361856  NO_CLASS
..                                                ...       ...       ...
45  prs and student tenants make a single payment ...  0.274197  NO_CLASS
45  in we received approximately of our net servic...  0.247862  NO_CLASS
45  this associate is considered material to the g...  0.247570  NO_CLASS
45  the business success of formycon group depends...  0.203175  NO_CLASS
45  credit originators who sell us defaulted consu...  0.175027  NO_CLASS

[152419 rows x 3 columns]
Q
--
8945
Index([506, 462,  97, 526,  29, 275,  91, 400,  49, 687,
       ...
       148, 424, 353, 118, 313, 229,  17, 159, 140, 280],
      dtype='int64', length=8945)
                                             Sentences     Score NACE_Code
506  each component element also includes several i...  0.564011         C
506  in thousands of short tons except as noted ind...  0.449954  NO_CLASS
506  the materiality determination process was cond...  0.437379  NO_CLASS
506  amendments to ifrs reference to the conceptual...  0.383984  NO_CLASS
506  . aftersale service the warranty policy is est...  0.365472  NO_CLASS
..                                                 ...       ...       ...
280  performance share units are settled in common ...  0.284105  NO_CLASS
280  thirdparty contract manufacturers including so...  0.279183  NO_CLASS
280  as of december deferred tax assets net operati...  0.268155  NO_CLASS
280  additionally the company has agreed to pay roy...  0.246582  NO_CLASS
280  general and administrative expenses . the incr...  0.234979  NO_CLASS

[162197 rows x 3 columns]
C
--
6386
Index([620, 253, 302, 204, 177, 203, 112, 252, 370,  36,
       ...
       123, 114,  11,  45,  83,  29, 133, 112, 141,  95],
      dtype='int64', length=6386)
                                             Sentences     Score NACE_Code
620  dr higgins brings extensive experience leading...  0.484412         B
620  ngos nongovernmental organisation. a nonprofit...  0.463711         B
620  the group has been using the rvd technology ex...  0.449987  NO_CLASS
620  stimation and evaluation of petroleum reserves...  0.435226  NO_CLASS
253  development of a mining project may take time ...  0.568592         B
..                                                 ...       ...       ...
95   the group has an interest in a worldclass glob...  0.378073  NO_CLASS
95   samples comprised g material that was collecte...  0.374087  NO_CLASS
95   he began his career in standard chartered bank...  0.321472  NO_CLASS
95   . the registrants other certifying officer and...  0.282429  NO_CLASS

In [19]:
statistics = full_df.groupby("NACE_Code").agg({"Sentences": "count", "Score": "mean"})

In [20]:
full_df = pd.concat([
    full_df[full_df["NACE_Code"] == "NO_CLASS"].sample(statistics.loc[statistics.index != "NO_CLASS", "Sentences"].max()), 
    full_df[full_df["NACE_Code"] != "NO_CLASS"]
    ])

In [21]:
statistics = full_df.groupby("NACE_Code").agg({"Sentences": "count", "Score": "mean"})
statistics.to_csv(end_path + "/statistics.csv")

In [22]:
statistics

           Sentences     Score
NACE_Code
A                370  0.480042
B               2784  0.499819
C                730  0.488633
D               3115  0.500345
E               1650  0.515510
F               3669  0.523780
G               1713  0.485469
H               2874  0.499496
I                854  0.491442
J                478  0.499299
K               6494  0.497577
L               2548  0.489265
M                606  0.485665
N                659  0.474658
NO_CLASS        6494  0.359985
P                416  0.487315
Q                328  0.488577
R                100  0.487335
S                 66  0.471894
T                 13  0.479503

In [23]:
full_df= full_df.rename(columns={"Sentences": "text"})
#full_df = full_df.drop(columns="Score")
full_df

,Evaluation,Notes,text,Score,NACE_Code
86776,None,None,at the cobaltproducing facility operated from ...,0.436413,NO_CLASS
37591,None,None,the principal activities of the company are in...,0.400789,NO_CLASS
131363,None,None,inventories are stated at the lower of cost an...,0.328865,NO_CLASS
50312,None,None,during the year the committee continued to ass...,0.445226,NO_CLASS
64136,None,None,stantecs offices it infrastructure project sit...,0.322791,NO_CLASS
...,...,...,...,...,...
124680,None,None,selain itu menurut data bps jumlah penumpang d...,0.450096,H
124681,None,None,he has participated since april as an elected ...,0.450035,H
124682,None,None,includes revenues primarily related to cancell...,0.450031,H
124683,None,None,on june we agreed to acquire upon their respec...,0.450020,H
124684,None,None,as part of the companys recovery from the impa...,0.450014,H

In [24]:
from sklearn.model_selection import train_test_split

# Split full_df into train (60%) and temp (40%)
train_df, temp_df = train_test_split(full_df, test_size=0.4, random_state=42)

# Split temp into test (20%) and validation (20%)
test_df, val_df = train_test_split(temp_df, test_size=0.5, random_state=42)

# Print the sizes of each split
print(f"Train size: {len(train_df)}, Test size: {len(test_df)}, Validation size: {len(val_df)}")

Train size: 21576, Test size: 7192, Validation size: 7193

In [25]:
full_df.to_csv(end_path + "/full_data.csv", index=False)

In [26]:
train_df.to_csv(end_path + "/train_data.csv", index=False)
val_df.to_csv(end_path + "/val_data.csv", index=False)
test_df.to_csv(end_path + "/test_data.csv", index=False)

In [27]:
end_path

'data/training_data/approach_1/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1__sample_ratio_1__filter_only_right_chunks__with_null_classifiers__nace_level_1__cos_thres_0.45'

In [28]:
%pwd

'/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis'