For each NACE Class get the 100 chunks that scored highest across all the reports

In [3]:
import pandas as pd
import glob
import os
import tqdm
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append("..")

#wor_dir = "/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis"
#os.chdir(wor_dir)
wor_dir =" "
from test_base import *

In [4]:
overview_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/stoxx_600_overview.csv"
overview_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv"
overview_path = wor_dir + "/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv"
overview_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv"

In [5]:
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_3_min_chunk_len_100_cos_thresh_0.4_nace_level_2_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_3_min_chunk_len_100_cos_thresh_0.4_nace_level_2_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_3_min_chunk_len_0_cos_thresh_0.4_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/tables_cos_sim_0.0_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/sentence_len_5/paragraph_and_sentence_len_5_min_chunk_len_100_cos_thresh_0.4_nace_level_2_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/sentence_len_5/paragraph_and_sentence_len_5_min_chunk_len_100_cos_thresh_0.4_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/paragraph_and_sentence_len_6_min_chunk_len_100_cos_thresh_0.4_nace_level_1_stoxx/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_4/"

raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_1/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2/"
raw_data_path = wor_dir + "/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_4/"
raw_data_path = wor_dir + "/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_3/"
raw_data_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2/"

In [6]:
reports = glob.glob(raw_data_path + "*/*_long.csv")
reports = glob.glob(raw_data_path + "*/*_short.csv")
len(reports)

1555

In [8]:
sample_ratio = 1

In [9]:
max_elements_per_class = 1000000

top_k_sentences = 200000

In [10]:
# if true, adds only chunks to training that have been classified into the same NACE class its report comes from
filter_only_right_chunks = True

In [11]:
# if true, adds random chunks that do not fulfill the minimum treshold (for BERT Training)
with_null_classifiers = True

In [12]:
new_threshold_cos_sin = 0.4

In [14]:
nace_level_descriptions = 2
nace_level = 1
assert nace_level_descriptions >= nace_level

In [15]:
training_data_path = "../data/training_data/"

In [16]:
suffix = f"sample_ratio_{sample_ratio}" + ("__filter_only_right_chunks" if filter_only_right_chunks else "") + ("__with_null_classifiers" if with_null_classifiers else "") + f"__nace_level_{nace_level}"

# "_subsample" if sample_ratio != 1 else ""
# end_path = os.path.join("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/test_read_training_data_right_classifications", raw_data_path.split("/")[-2] + suffix)
# end_path = os.path.join("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/test_read_training_data", raw_data_path.split("/")[-2] + suffix + "_with_no_class__cos_sim_04")
# end_path = os.path.join("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/test_read_training_data_right_classifications", raw_data_path.split("/")[-2] + suffix + "_with_no_class__cos_sim_04")

end_path = os.path.join(training_data_path, 
                        raw_data_path.split("/")[-2] + "__" + suffix)
end_path

'../data/training_data/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2__sample_ratio_1__filter_only_right_chunks__with_null_classifiers__nace_level_1'

In [17]:
#df_overview = pd.read_excel(overview_path)
df_overview = pd.read_csv(overview_path)
df_overview

,Unnamed: 0,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,...,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report
0,5789,ZW0009011041,Ariston Holdings Ltd.,1,1947.0,ZWE,V97772103,20090317.0,ZWE,@NA,...,ZW0009011041,603408,Ariston Holdings Ltd.,1.0,ARIS-ZW,1,SHARE,6034081,A,Ariston Holdings Ltd.1.pdf
1,35816,INE978A01027,Heritage Foods Limited,1,1992.0,IND,Y3179H146,20020117.0,IND,06FQLY-E,...,INE978A01027,BF2F40,Heritage Foods Limited,1.0,519552-IN,1,SHARE,BF2F405,A,Heritage Foods Limited1.pdf
2,80373,MYL7854OO002,Timberwell Bhd.,1,1996.0,MYS,Y88399103,19970516.0,MYS,05JH15-E,...,MYL7854OO002,690556,Timberwell Bhd.,1.0,7854-MY,1,SHARE,6905563,A,Timberwell Bhd.1.pdf
3,49813,MYQ0189OO009,Matang Bhd.,1,2015.0,MYS,Y58347108,20170117.0,MYS,@NA,...,MYQ0189OO009,BYYQB5,Matang Bhd.,1.0,0189-MY,1,SHARE,BYYQB53,A,Matang Bhd.2.pdf
4,73064,MYL4316OO005,Sin Heng Chan (Malaya) Bhd.,1,1962.0,MYS,Y80178109,19880324.0,MYS,05YMQ5-E,...,MYL4316OO005,681088,Sin Heng Chan (Malaya) Bhd.,1.0,4316-MY,1,SHARE,6810883,A,Sin Heng Chan (Malaya) Bhd.1.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,5783,US0404432025,Aristocrat Group Corp.,0,2011.0,USA,040443202,20120313.0,USA,00DDP9-E,...,US0404432025,04044320,Aristocrat Group Corp.,1.0,ASCC-US,1,SHARE,BWX6257,S,Aristocrat Group Corp.1.pdf
1558,73228,KYG816BW1095,Sino-Life Group Limited,1,2005.0,HKG,G816BW109,20090909.0,HKG,00C60C-E,...,KYG816BW1095,B409GR,Sino-Life Group Limited,1.0,8296-HK,1,SHARE,B409GR3,S,Sino-Life Group Limited1.pdf
1559,86319,KYG9477E1070,Water Oasis Group Limited,1,1998.0,HKG,G9477E107,20070905.0,HKG,00610B-E,...,KYG9477E1070,651233,Water Oasis Group Limited,1.0,WOSSF-US,0,SHARE,B02V9Q9,S,Water Oasis Group Limited1.pdf
1560,66027,US76119X1054,"Reservoir Media, Inc.",1,2007.0,USA,76119X105,20210105.0,USA,0NVYZ2-E,...,US76119X1054,76119X10,"Reservoir Media, Inc.",1.0,RSVR-US,1,SHARE,BP0B9H7,S,"Reservoir Media, Inc.1.pdf"
1561,38190,KYG4707P1054,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,@NA,...,KYG4707P1054,BJYFY1,Icon Culture Global Company Limited,1.0,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf

In [18]:
df_nace_codes_descriptions = pd.read_csv("../data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", sep="\t")
filter_level_1_classes = "ABCDEFGHIJKLMNOPQRSTUVW"

In [19]:
result = pd.DataFrame(columns=["Sentences", "Score", "NACE_Code"])

# loop over all reports and get the all the sentences 
for report in tqdm.tqdm(reports):

    df = pd.read_csv(report)

    if filter_only_right_chunks: 
        report_name = os.path.basename(report).replace(".txt_short.csv", "") + ".pdf"
        report_code = df_overview[df_overview["Report"]==report_name]["NACE"].iloc[0]
        report_code = get_all_level(report_code)[nace_level]
        if nace_level == nace_level_descriptions: 
            filter_column = list(filter(lambda x: "Scores_"+str(report_code) in x, df.columns))
        else:
            filter_column = []
            for column in df.columns: 
                if "Scores" in column: 
                    if get_all_level(column.split("_")[1])[nace_level]==report_code: 
                        filter_column.append(column)
        df = df[["Sentences"]+filter_column]

    if nace_level == 1: 
        # filter some nace classes
        scores = df[[column for column in df.columns if ("Scores" in column) and get_all_level(column.split("_")[1], df_nace_codes_descriptions)[nace_level] in filter_level_1_classes]].columns
    else: 
        scores = df[[column for column in df.columns if ("Scores" in column)]].columns
    
    for score in scores:
        temp = df[df[score].notna()][["Sentences", score]]  
        try: 
            temp["NACE_Code"] = get_all_level(score.split("_")[1])[nace_level]
        except IndexError: 
            continue
        temp = temp.rename(columns={score: "Score"})
        result = pd.concat([result, temp])

  0%|          | 0/1555 [00:00<?, ?it/s]/var/folders/fp/yhl61lbj3m73x3_17tsp1vrr0000gn/T/ipykernel_30501/934534259.py:35: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([result, temp])
100%|██████████| 1555/1555 [00:56<00:00, 27.54it/s]

In [21]:
result

                                             Sentences     Score NACE_Code
17   in june the company completed the sale of the ...  0.350486         C
25   for the thenowned arrow and geoffrey beene tra...  0.365972         C
26   of the costs incurred during million relates t...  0.330844         C
45   the companys management is responsible for mai...  0.342113         C
46   as a result we have received requests for sust...  0.329531         C
..                                                 ...       ...       ...
459  besides the adoption of alternative design for...  0.384183         F
460  he was a member of construction industry counc...  0.429248         F
470  depreciation allowance in of excess related de...  0.374058         F
477  plastic and chemical products building related...  0.435515         F
486  in the past year the foundation industry witne...  0.472951         F

[764535 rows x 3 columns]

In [22]:
os.makedirs(end_path, exist_ok=True)

In [23]:
recordings = []

In [24]:
# for each code, store the 100 with the highest similarity score to the code

full_df = []
for code in set(result["NACE_Code"].to_list()): 

    #if not get_all_level(code.split("_")[1], df_nace_codes_descriptions)[1] in filter_level_1_classes: 
    # if not get_all_level(code, df_nace_codes_descriptions)[nace_level] in filter_level_1_classes: 
    #     continue

    temp = result[result["NACE_Code"] == code]
    temp = temp.drop_duplicates(subset="Sentences")
    temp = temp[temp["Sentences"].apply(len) >= 100]
    temp = temp.sort_values(by="Score", ascending=False)

    if with_null_classifiers: 
        temp.loc[temp["Score"]<new_threshold_cos_sin, "NACE_Code"] = "NO_CLASS"
        temp = temp[(temp["Score"] >= new_threshold_cos_sin) | (temp["NACE_Code"]=="NO_CLASS")]
        
        class_index = temp[temp["NACE_Code"]!="NO_CLASS"].index
        no_class_index = temp[temp["NACE_Code"]=="NO_CLASS"].index

        print(len(temp[temp["NACE_Code"]=="NO_CLASS"]))
        print(temp[temp["NACE_Code"]=="NO_CLASS"].index)
        print(temp.loc[no_class_index])
        print(code)
        print("--")

        temp = temp.loc[list(np.random.choice(no_class_index, len(class_index)))+list(class_index)]
    else:
        temp = temp[temp["Score"] >= new_threshold_cos_sin]

    number_of_elements_per_class = min(int(sample_ratio*len(temp)), max_elements_per_class, len(temp))
    random_choice = np.random.choice(len(temp), number_of_elements_per_class, replace=False)
    temp = temp.iloc[random_choice]
    temp = temp.sort_values(by="Score", ascending=False)
    temp = temp.iloc[:top_k_sentences, :]
    temp = temp.reset_index(drop=True)
    temp["Evaluation"] = None
    temp["Notes"] = None
    temp = temp[["Evaluation", "Notes", "Sentences", "Score", "NACE_Code"]]

    recordings.append({"Code": code,"Nbr. of Chunks": len(temp),"Avg. Length": temp["Sentences"].apply(len).mean(), "Avg. Score": temp["Score"].mean(), "Min. Score": temp["Score"].min(), "Max. Score": temp["Score"].max()})

    text = ""
    for i, row in temp.iterrows():
        text += f"#{i}, Score: " + str(round(row["Score"], 2)) + "\n\n" + row["Sentences"] + "\n\n"

    with open(os.path.join(end_path, code.replace("/"," ")) + ".txt", "w") as f:
        f.write(text)
    
    temp = temp.drop_duplicates(subset=["Sentences"])
    temp.to_csv(os.path.join(end_path, code.replace("/"," ")) + ".csv")

    full_df.append(temp)

full_df = pd.concat(full_df, axis=0, ignore_index=True)

9855
Index([111, 131, 135,  33, 147, 222, 300,  20, 318, 152,
       ...
        43,  34, 110,  96,  46,  29,   7,   6,  66,   9],
      dtype='int64', length=9855)
                                             Sentences     Score NACE_Code
111  glyphltcfontpophlatimesnewromanboldgteegglyphl...  0.356993  NO_CLASS
111  the campaign consisted of informational videos...  0.180872  NO_CLASS
111  during the period we recorded a yearonyear inc...  0.175545  NO_CLASS
111  shares included in other interests are benefic...  0.174614  NO_CLASS
111  on behalf of the board the board of directors ...  0.170880  NO_CLASS
..                                                 ...       ...       ...
9    the remaining aggregate principal with interes...  0.106504  NO_CLASS
9    revenue during the years ended december and re...  0.099678  NO_CLASS
9    significant transaction of boffice proposed du...  0.089605  NO_CLASS
9    company employee benefits and entitlements inc...  0.073958  NO_CLASS
9    whether in transportation infrastructure energ...  0.018019  NO_CLASS

[144587 rows x 3 columns]
L
--
22761
Index([668, 468,  79, 337, 421, 722, 817, 689, 992, 751,
       ...
       432,   9, 275, 472, 367,  38, 167, 211, 158, 507],
      dtype='int64', length=22761)
                                             Sentences     Score NACE_Code
668  earnout consideration amounted to million. the...  0.426042         J
668  the site features a great display of images vi...  0.410465         J
668  d. making a distribution that does not comply ...  0.406692         J
668  in terms of technology astragraphia offers a r...  0.399996  NO_CLASS
668  expand internationally. we believe there is a ...  0.378709  NO_CLASS
..                                                 ...       ...       ...
507  on initial recognition of an equity investment...  0.295263  NO_CLASS
507  mr. xiao mingxiao aged has been a vice preside...  0.287924  NO_CLASS
507  the transaction price is the amount of conside...  0.282857  NO_CLASS
507  expansion of certsy credential verifications t...  0.271215  NO_CLASS
507  mvrcdglyphltcfontaaaabcfontadgtuvuglyphltcfont...  0.073614  NO_CLASS

[736693 rows x 3 columns]
J
--
8316
Index([698, 142, 800, 494, 446, 296, 263, 477, 321, 358,
       ...
       501,  14, 388,  71,  12, 313, 325,   8,   3,   4],
      dtype='int64', length=8316)
                                             Sentences     Score NACE_Code
698  as a company with a premium listing on the lon...  0.399964  NO_CLASS
698  resorts world las vegas features guest rooms a...  0.394651  NO_CLASS
698  nature of goods or services timing of recognit...  0.392720  NO_CLASS
698  to the extent we grant the customer the option...  0.381502  NO_CLASS
698  we conduct business in a number of jurisdictio...  0.369660  NO_CLASS
..                                                 ...       ...       ...
4    the group manages its capital to ensure that e...  0.304494  NO_CLASS
4    during the year ended march our significant in...  0.300021  NO_CLASS
4    the impact on operations and location of facil...  0.286763  NO_CLASS
4    rightofuse assets are depreciated on a straigh...  0.263468  NO_CLASS
4    director and secretary of board of directors t...  0.133496  NO_CLASS

[123492 rows x 3 columns]
R
--
5504
Index([194, 441, 197, 665,  24,  30,  71, 495, 367, 503,
       ...
         1,  32, 402, 172,  43, 249, 210, 218, 198, 229],
      dtype='int64', length=5504)
                                             Sentences     Score NACE_Code
194  revenue from domestic water sales amounted to ...  0.574976         E
194  the majority of the systems equipment and faci...  0.489711         E
194  during the year we have complied with a reques...  0.444203         E
194  the group has entered into certain service con...  0.409460         E
194  key subsidiary country of operation memiontec ...  0.408936         E
..                                                 ...       ...       ...
229  procurement service fee revenue is primarily e...  0.321904  NO_CLASS
229  discharge quality management creating green fo...  0.314511  NO_CLASS
229  as described further in note to the financial ...  0.309611  NO_CLASS
229  within one financial year after one financial ...  0.294781  NO_CLASS
229  all recommendations and proposals from the boa...  0.226264  NO_CLASS

[60920 rows x 3 columns]
E
--
13198
Index([793, 286, 316, 243, 732, 473, 687, 450, 568, 308,
       ...
       244, 151, 139,  90, 201, 108, 127,  92, 142,  87],
      dtype='int64', length=13198)
                                             Sentences     Score NACE_Code
793  as of december the group has fully completed t...  0.467323         A
793  rs. .a segment results company revenue operati...  0.399968  NO_CLASS
793  when the group is a sublessor it assesses the ...  0.349010  NO_CLASS
793  during the year ended december we had negative...  0.251155  NO_CLASS
793  consolidated statement of changes in equity   ...  0.249159  NO_CLASS
..                                                 ...       ...       ...
87   these demonstrate the groups commitment to the...  0.268125  NO_CLASS
87   . in compliance with the aforesaid mca circula...  0.265032  NO_CLASS
87   hk hk at january development expenditure incur...  0.246851  NO_CLASS
87   share revaluation accumulated total capital re...  0.236310  NO_CLASS
87   company discloses that rpts are conducted in s...  0.177183  NO_CLASS

[281747 rows x 3 columns]
A
--
4541
Index([664, 629, 564, 234, 850, 628, 509, 433, 469, 826,
       ...
        76,  55,  49,  54,  14, 131, 258,  84, 154, 196],
      dtype='int64', length=4541)
                                             Sentences     Score NACE_Code
664  our business is growing and becoming more comp...  0.312519  NO_CLASS
664  a review of business and future outlook of our...  0.167189  NO_CLASS
664  in november the group mortgaged its office pro...  0.150190  NO_CLASS
664  our anz assets give us the opportunity to serv...  0.130771  NO_CLASS
664  as at december bank balances amounting to rmb ...  0.128445  NO_CLASS
..                                                 ...       ...       ...
196  . exclusive call option to acquire all or part...  0.107591  NO_CLASS
196  the company is an investment holding company. ...  0.104785  NO_CLASS
196  . a subject to paragraph c of this resolution ...  0.096996  NO_CLASS
196  a this mainly relates to the amount payable fo...  0.096822  NO_CLASS
196  transactions between related parties are on no...  0.064806  NO_CLASS

[32855 rows x 3 columns]
P
--
10640
Index([302, 762, 736, 427,  54, 384, 339, 643, 675,  93,
       ...
        34,  66,  12,  96,  70, 132, 114,  32,  87,  68],
      dtype='int64', length=10640)
                                             Sentences     Score NACE_Code
302  in the group had finance lease arrangement for...  0.551733         G
302  vi during the year ended march the company als...  0.493994         G
302  property investment sale of financial assets m...  0.472487         G
302  d administration and management fee income pro...  0.471764         G
302  prior to joining our group alexander was regio...  0.430220         G
..                                                 ...       ...       ...
68   for the year ended december other revenue was ...  0.317096  NO_CLASS
68   our principal independent accountant for the f...  0.314301  NO_CLASS
68   i ifrs financial instruments amendment clarifi...  0.304289  NO_CLASS
68   feglyphltcfontmedkoptimesnewromangtglyphltcfon...  0.081520  NO_CLASS
68   ampamp b jac m nkqr m n m nqt .d cozz qr k g p...  0.009896  NO_CLASS

[249331 rows x 3 columns]
G
--
11875
Index([789, 204, 925, 366, 597, 485, 511, 299, 562, 129,
       ...
       336, 561,  29, 357, 287,  54, 115, 296, 592,  66],
      dtype='int64', length=11875)
                                             Sentences     Score NACE_Code
789  dalam menjalankan usahanya grup primaya hospit...  0.506864         Q
789  grand opening klinik bic vida laboratorium kli...  0.502333         Q
789  irwansyah s.kep ners . muhammad yani s. kep ne...  0.458594         Q
789  companies as at december equity interestordina...  0.400000  NO_CLASS
789  the employees can carryforward a portion of th...  0.351702  NO_CLASS
..                                                 ...       ...       ...
66   includes amortised expenses for unvested sos r...  0.265677  NO_CLASS
66   the group received insurance proceeds from a t...  0.261470  NO_CLASS
66   options and performance rights are not issued ...  0.254919  NO_CLASS
66   revenue primarily includes two components accr...  0.245909  NO_CLASS
66   there have been no material changes in the fin...  0.210993  NO_CLASS

[282181 rows x 3 columns]
Q
--
8826
Index([140, 483, 557, 374, 252, 738,  56, 405, 927,  11,
       ...
        85,  53,  56, 112,  24, 107,   3,  39, 108,  48],
      dtype='int64', length=8826)
                                             Sentences     Score NACE_Code
140  construction land is listed as houses and land...  0.599508         F
140  wastewater from construction sites is classifi...  0.535876         F
140  onsite inspections and rectification. we condu...  0.524773         F
140  quality cost and the use of automated construc...  0.491634         F
140  the companys significant portion of business i...  0.466030         F
..                                                 ...       ...       ...
48   land development joint ventures home building ...  0.306787  NO_CLASS
48   the company acts as an investment holding comp...  0.305072  NO_CLASS
48   the valuation techniques used are subjective i...  0.278475  NO_CLASS
48   in cursul anului a avut loc si cea de a doua m...  0.263476  NO_CLASS
48   number of shares and votes share of shares and...  0.102617  NO_CLASS

[167297 rows x 3 columns]
F
--
17554
Index([450, 312,  50, 595, 224, 688, 456, 107,  61, 630,
       ...
        77, 152, 329, 139, 405, 267, 380, 282, 397, 413],
      dtype='int64', length=17554)
                                             Sentences     Score NACE_Code
450  a pool consists of a group of vessels of simil...  0.495224         H
450  the sea water protection system is being maint...  0.406380         H
450  captain ting is responsible for overall daily ...  0.399993  NO_CLASS
450  government grants received by the group includ...  0.390088  NO_CLASS
450  the orcelle wind is a windpowered pure car tru...  0.381542  NO_CLASS
..                                                 ...       ...       ...
413  technology the increasing use of smartphones a...  0.259156  NO_CLASS
413  borrowings lease liabilities total note note a...  0.243276  NO_CLASS
413  an item of property plant and equipment is der...  0.226353  NO_CLASS
413  amendment to ifrs covidrelated rent concession...  0.218342  NO_CLASS
413  the group recognises right of use assets rou o...  0.203314  NO_CLASS

[441819 rows x 3 columns]
H
--
10453
Index([ 38, 302, 148, 366, 349, 412, 596, 111, 737, 264,
       ...
        22, 328, 275, 332, 159, 242, 300, 527, 105, 468],
      dtype='int64', length=10453)
                                             Sentences     Score NACE_Code
38   each of the services rendered is assessed to b...  0.602588         I
38   macroeconomic conditions the combination of ma...  0.443649         I
38   the auto camp is spread over m of land which t...  0.436957         I
38   our immediate priority was our foodled busines...  0.431575         I
38   for development properties whereby the group i...  0.429771         I
..                                                 ...       ...       ...
468  the following description is a summary and doe...  0.273686  NO_CLASS
468  listing rule governance principal description ...  0.266508  NO_CLASS
468  items included in the consolidated financial s...  0.254293  NO_CLASS
468  k concessions licenses trademarks and similar ...  0.250219  NO_CLASS
468  during the year ended december we invested mil...  0.231318  NO_CLASS

[214485 rows x 3 columns]
I
--
9318
Index([522, 606, 778, 369, 129, 330, 394, 201, 368, 263,
       ...
       138,   3, 209,  32, 354, 202, 451, 363, 176, 450],
      dtype='int64', length=9318)
                                             Sentences     Score NACE_Code
522  g glyphltcfontgdbfkoarialmtgtglyphltcfontgdbfk...  0.354393  NO_CLASS
522  the aposterior measures are provided by the pl...  0.158979  NO_CLASS
522  alternate directors mariana soto mara paz cerd...  0.156920  NO_CLASS
522  were using data and machine learning to make o...  0.151559  NO_CLASS
522  regarding the identification of new talents th...  0.140368  NO_CLASS
..                                                 ...       ...       ...
450  . as disclosed in the announcement of the comp...  0.172640  NO_CLASS
450  his experience is unique and vast having worke...  0.165365  NO_CLASS
450  in october two.pl.tnumzero.pl.tnumtwo.pl.tnumt...  0.141180  NO_CLASS
450  a short term million loan was provided from aw...  0.125951  NO_CLASS
450  december december shares amount shares amount ...  0.068410  NO_CLASS

[113072 rows x 3 columns]
D
--
4218
Index([603, 534,  48, 752, 207, 448, 386, 572, 112, 465,
       ...
        98,  64, 385, 290, 315, 516, 215,  25, 251,  35],
      dtype='int64', length=4218)
                                             Sentences     Score NACE_Code
603  beauty therapists working in stores have under...  0.401393         S
603  obtain sufficient appropriate audit evidence r...  0.399974  NO_CLASS
603  ve and msci put solutions in the it industry c...  0.382212  NO_CLASS
603  the group manages the capital structure and ma...  0.358558  NO_CLASS
534  during the directors do not have any interest ...  0.536370         S
..                                                 ...       ...       ...
35   brian has held many industry positions includi...  0.344655  NO_CLASS
35   the performance obligation is satisfied upon d...  0.341655  NO_CLASS
35   notes to the consolidated statement of cash fl...  0.302285  NO_CLASS
35   year ended december gross profit margin gross ...  0.287515  NO_CLASS
35   critical accounting policies this section iden...  0.248566  NO_CLASS

[31803 rows x 3 columns]
S
--
30646
Index([ 30,  50, 942,  81,  32, 244, 128,  46, 391, 714,
       ...
       466, 527, 234, 388, 398,  93, 145, 608, 301, 429],
      dtype='int64', length=30646)
                                             Sentences     Score NACE_Code
30   year ended year ended . . a power and fuel con...  0.448710         C
30   the company has three reportable segments. the...  0.445582         C
30   during the current period the group has compli...  0.422962         C
30   the recoverable amount corresponds to the high...  0.420729         C
30   development of new products to innovate digita...  0.420136         C
..                                                 ...       ...       ...
429  we may enter into additional business developm...  0.248925  NO_CLASS
429  translation difference contains the translatio...  0.247226  NO_CLASS
429  the audit procedures include a review of the s...  0.244719  NO_CLASS
429  iii agrees that the member will indemnify the ...  0.241633  NO_CLASS
429  in september the company entered into a noncan...  0.203112  NO_CLASS

[1490056 rows x 3 columns]
C
--
9567
Index([125, 226, 244, 520, 133, 294, 169,  38, 312, 133,
       ...
        24,  34, 147, 102,  35, 203,  59, 178, 217, 117],
      dtype='int64', length=9567)
                                             Sentences     Score NACE_Code
125  the deepsea atlantic was largely focused on op...  0.463454         B
125  the stripping ratio varies depending on the st...  0.462568         B
125  has been concluded and signed. under the terms...  0.452365         B
125  these commitments may be varied in the future ...  0.443005         B
125  communication and mutual understanding and res...  0.440841         B
..                                                 ...       ...       ...
117  sfrsi no. title effective date for periods beg...  0.311339  NO_CLASS
117  last months june qtr. march qtr. dec qtr. sep ...  0.301838  NO_CLASS
117  the outtrim project wap is in the exmouth subb...  0.276021  NO_CLASS
117  the groups main sources of energy consumption ...  0.260331  NO_CLASS
117  diversity and inclusion. glyphltcfontaablgitim...  0.115726  NO_CLASS

[233447 rows x 3 columns]
B
--
21333
Index([890, 641, 699,  29, 237, 349, 385,   1, 557, 490,
       ...
       175, 290, 295, 221,  56,  12, 467, 329, 182, 436],
      dtype='int64', length=21333)
                                             Sentences     Score NACE_Code
890  the physical division which is allocated to th...  0.579275         M
890  ltd. kbs us prime property singapore property ...  0.448759         M
890  . adjust the structure of credit customers dev...  0.399992  NO_CLASS
890  michele is a chartered accountant and provides...  0.391907  NO_CLASS
890  these licenses and registrations subject us am...  0.349612  NO_CLASS
..                                                 ...       ...       ...
436  all of our practices are registered with the r...  0.256711  NO_CLASS
436  the findings of independent audit reports are ...  0.256630  NO_CLASS
436  business combinations are initially accounted ...  0.245715  NO_CLASS
436  a sustained period of reduced snowfall events ...  0.208022  NO_CLASS
436  net cash used in operating activities for the ...  0.176292  NO_CLASS

[882113 rows x 3 columns]
M
--
13041
Index([ 212, 1278,  598,  330,  514,  269,  504,  195,   79,   61,
       ...
         30,  175,   87,  165,  120,  160,   45,  141,  151,  132],
      dtype='int64', length=13041)
                                             Sentences     Score NACE_Code
212  in february the fasb issued accounting standar...  0.647643         N
212  at the inception or on reassessment of a contr...  0.548915         N
212  contractual maturities of financial liabilitie...  0.530295         N
212  there are no sales between the business segmen...  0.530288         N
212  in accordance with ifrs lease liabilities were...  0.510036         N
..                                                 ...       ...       ...
132  during the year credit corp expanded on the fo...  0.284848  NO_CLASS
132  or authorizing others to provide anything of v...  0.280373  NO_CLASS
132  research and development spend for the year re...  0.271978  NO_CLASS
132  the board of directors consists of nine member...  0.251381  NO_CLASS
132  p glyphltcfontgpsirvtimesnewromanbolditalicgtg...  0.037051  NO_CLASS

[441587 rows x 3 columns]
N
--
6068
Index([692, 311, 209, 231, 303, 356, 434, 624, 963, 686,
       ...
        83,  21, 230, 357, 164, 203, 176,   5, 200, 111],
      dtype='int64', length=6068)
                                             Sentences     Score NACE_Code
692  in order to get an overview of its exposure to...  0.462856         K
692  increses and decreases of equity during the fi...  0.435742         K
692  in addition oaktree accounts will be permitted...  0.420302         K
692  summarised financial information in respect of...  0.401660         K
692  other financial assets d other current assets ...  0.399995  NO_CLASS
..                                                 ...       ...       ...
111  liquidity risk is the risk that the company wi...  0.353622  NO_CLASS
111  further details regarding the principal agreem...  0.349518  NO_CLASS
111  in the year the total underwritten premium inc...  0.321617  NO_CLASS
111  serving high net worth and ultrahigh net worth...  0.307735  NO_CLASS
111  khglyphltcfontaaallltimesnewromangtdjmehaglyph...  0.052488  NO_CLASS

[152650 rows x 3 columns]
K
--
173
Index([311, 505, 106, 417,  21, 140, 116, 363, 401, 514,
       ...
       222, 383, 455, 318, 168, 161, 217, 296, 112, 212],
      dtype='int64', length=173)

In [35]:
statistics = full_df.groupby("NACE_Code").agg({"Sentences": "count", "Score": "mean"})

In [36]:
full_df = pd.concat([
    full_df[full_df["NACE_Code"] == "NO_CLASS"].sample(statistics.loc[statistics.index != "NO_CLASS", "Sentences"].max()), 
    full_df[full_df["NACE_Code"] != "NO_CLASS"]
    ])

In [37]:
statistics.to_csv(end_path + "/statistics.csv")

In [38]:
statistics

           Sentences     Score
NACE_Code
A               2273  0.449670
B               7582  0.458783
C               8274  0.441124
E               2318  0.470171
F               4789  0.457653
G               6166  0.437566
H               3358  0.446564
I               3964  0.447471
J               2243  0.439861
K               6700  0.503423
M               8296  0.455993
N               6068  0.533480
NO_CLASS        8296  0.329343
Q               4920  0.463889
R               2524  0.473529
S               1340  0.441146
T                 19  0.440730

In [39]:
full_df= full_df.rename(columns={"Sentences": "text"})
#full_df = full_df.drop(columns="Score")
full_df

,Evaluation,Notes,text,Score,NACE_Code
114381,None,None,in moving towards sustainable supply chain pro...,0.284744,NO_CLASS
8016,None,None,fees equitysettled sharebased expense total re...,0.347439,NO_CLASS
31842,None,None,pages directors report sustainability report s...,0.319031,NO_CLASS
114336,None,None,the financial statements presented in this rep...,0.284953,NO_CLASS
14832,None,None,bsccl is an important member of two internatio...,0.317937,NO_CLASS
...,...,...,...,...,...
179811,None,None,the group has applied the practical expedient ...,0.413628,T
179812,None,None,material related party transactions entered in...,0.413411,T
179813,None,None,viii the entity or any member of a group of wh...,0.413084,T
179814,None,None,revenue is recognised when control over a prod...,0.408819,T
179815,None,None,at the lease commencement date the group recog...,0.404764,T

In [40]:
from sklearn.model_selection import train_test_split

# Split full_df into train (60%) and temp (40%)
train_df, temp_df = train_test_split(full_df, test_size=0.4, random_state=42)

# Split temp into test (20%) and validation (20%)
test_df, val_df = train_test_split(temp_df, test_size=0.5, random_state=42)

# Print the sizes of each split
print(f"Train size: {len(train_df)}, Test size: {len(test_df)}, Validation size: {len(val_df)}")

Train size: 47478, Test size: 15826, Validation size: 15826

In [41]:
full_df.to_csv(end_path + "/full_data.csv", index=False)

In [42]:
train_df.to_csv(end_path + "/train_data.csv", index=False)
val_df.to_csv(end_path + "/val_data.csv", index=False)
test_df.to_csv(end_path + "/test_data.csv", index=False)

In [43]:
end_path

'../data/training_data/dataset__reports_subset_from_full_data_1_sentence_len_6__min_chunk_len_100__cos_thresh_0.4__nace_level_2__sample_ratio_1__filter_only_right_chunks__with_null_classifiers__nace_level_1'

In [44]:
%pwd

'/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/benchmark'