In [19]:
import pandas as pd
import json
import ast
from scipy.special import softmax

In [2]:
%pwd

'/data/resources/weichel-llama3/work'

In [8]:
a = "projects/nace_classification/nace_report_topic_analysis/results/BERT_classification/dataset__stoxx_600_sentence_len_6__nace_level_1/Antofagasta plc1.txt/Antofagasta plc1.txt_classifications.csv"
a = "projects/nace_classification/nace_report_topic_analysis/results/BERT_classification/2_dataset__stoxx_600_sentence_len_6__nace_level_1/Hannover Rueck SE1.txt/Hannover Rueck SE1.txt_classifications.csv"

In [22]:
df = pd.read_csv(a, index_col=0)
scores = df.columns.drop("Sentences")

In [23]:
sentences = df["Sentences"]

In [32]:
import numpy as np
import pandas as pd

# assume df is your dataframe
def softmax(x):
    e = np.exp(x - np.max(x))   # subtract max for numerical stability
    return e / e.sum()

In [34]:
df_soft = df[scores].apply(lambda x: softmax(x), 1)
df_soft.max(1)

0      0.623879
1      0.576054
2      0.913393
3      0.932858
4      0.953926
         ...
306    0.947284
307    0.951072
308    0.885702
309    0.745895
310    0.913340
Length: 311, dtype: float64

In [12]:
df[scores].max(1).sort_values(ascending=False)

33     9.437278
79     8.940954
121    8.816452
291    8.780148
196    8.585886
         ...
250    3.394133
209    3.359793
194    3.142111
286    2.977048
99     2.908936
Length: 311, dtype: float64

In [13]:
df

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,-1.894361,-1.264417,4.136326,-2.265335,-3.008976,-1.579123,-0.686892,5.068840,-2.470571,-4.114100,-0.033472,-1.268820,3.378241,-2.288903,0.145076,-3.345425,-3.807578,there were no changes in the composition of th...
1,-0.695343,-3.893245,5.419019,-1.313361,-0.130322,-0.235103,-2.623850,-0.156747,-1.556218,-4.310181,-1.845998,-0.265323,0.832995,-1.431447,5.757366,-2.580001,-2.029149,from onwards the runoff result of the previous...
2,-1.594772,-2.274416,5.729294,-1.895857,-2.555533,-1.214713,-1.400067,2.925963,-1.526131,-3.521047,0.175502,-0.827296,1.292420,-2.373076,1.321531,-2.966021,-3.214162,a. the annual financial statements of the comp...
3,-1.702443,-3.178286,3.276305,6.438750,-2.227421,-3.257275,-2.082111,-2.707376,-2.986000,0.167853,-2.659322,-0.245776,2.445356,-1.600890,1.396590,-2.683732,-2.845778,this more extensive scope to flexibly shape th...
4,-1.396930,-3.660182,3.203647,0.120371,0.098467,-0.410318,-3.187246,-0.492044,-1.258380,-3.465861,-1.966563,-1.598775,1.417377,-1.132849,6.558451,-1.821275,-1.052174,c the companys disclosures on the premium rese...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,-1.424083,-4.040144,3.848856,-0.266699,0.249766,-0.302982,-3.169420,-0.295122,-1.286177,-3.885552,-1.795807,-1.626527,1.112627,-1.523770,6.896789,-2.084052,-1.487867,the executive directors calculate the amount o...
307,-1.372851,-3.583877,3.052367,0.166511,0.187522,-0.434953,-3.150415,-0.547901,-1.275900,-3.326154,-1.987110,-1.516371,1.470391,-1.032928,6.401889,-1.720639,-1.019275,deposits repurchase agreements cash at banks i...
308,-1.306188,-3.906844,4.164135,-0.419233,0.247297,-0.245578,-2.850069,-0.482438,-1.310508,-3.664335,-1.743607,-0.958633,1.168818,-1.326264,6.333496,-2.056635,-1.707658,in some cases provisions are determined on an ...
309,-0.996377,-3.859959,6.136189,-1.589080,-0.768920,-0.946994,-2.575916,0.566053,-1.655299,-4.391325,-1.432064,-0.349694,1.209978,-1.654612,5.006464,-2.900186,-2.486959,based on our audit procedures we were able to ...
310,-1.291247,-4.106691,4.347476,-0.411722,0.082548,-0.191578,-3.079859,-0.475338,-1.353858,-3.948862,-1.880369,-1.219997,1.189500,-1.481108,6.801793,-2.243260,-1.704005,the benefit adjustment based on surplus partic...

In [14]:
df[scores].max(1).shape

(311,)

In [15]:
df[scores].T.shape

(17, 311)

In [16]:
df[(df[scores].T == df[scores].max(1)).T]

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.06884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.757366,NaN,NaN,NaN
2,NaN,NaN,5.729294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,6.43875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.558451,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.896789,NaN,NaN,NaN
307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.401889,NaN,NaN,NaN
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.333496,NaN,NaN,NaN
309,NaN,NaN,6.136189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.801793,NaN,NaN,NaN

In [17]:
df = df[(df[scores].T == df[scores].max(1)).T]
df["Sentences"] = sentences
df

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.06884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,there were no changes in the composition of th...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.757366,NaN,NaN,from onwards the runoff result of the previous...
2,NaN,NaN,5.729294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a. the annual financial statements of the comp...
3,NaN,NaN,NaN,6.43875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,this more extensive scope to flexibly shape th...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.558451,NaN,NaN,c the companys disclosures on the premium rese...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.896789,NaN,NaN,the executive directors calculate the amount o...
307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.401889,NaN,NaN,deposits repurchase agreements cash at banks i...
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.333496,NaN,NaN,in some cases provisions are determined on an ...
309,NaN,NaN,6.136189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,based on our audit procedures we were able to ...
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.801793,NaN,NaN,the benefit adjustment based on surplus partic...

In [18]:
df.mean()

TypeError: Could not convert ['there were no changes in the composition of the supervisory board or its committees in the year under review. the term of office of the companys supervisory board ends pursuant to of the articles of association of hannover r ü ck se at the end of the general meeting that ratifies the acts of management for the financial year. nor were any changes made to the composition of the executive board in . at its meeting in august however the supervisory board appointed ms. sharon ooi as a member of the executive board of hannoverfrom onwards the runoff result of the previous years provision for outstanding claims is calculated by hannover rück se on an accidentyear basis and hence appropriately allocated.a. the annual financial statements of the company the financial statements of the hannover re group and the combined management report prepared by the executive board for the company and the group andthis more extensive scope to flexibly shape the place of work similarly helps our employees to strike a balance between career and private life.c the companys disclosures on the premium reserve are contained in the sections measurement of equity and liabilities and notes to equity and liabilities of the notes to the financial statements. disclosures on risks are contained in the companys management report in the section report on risks and opportunities subsection technical risks of personal reinsurance.the executive directors of the company are responsible for the preparation of the esefdocuments including the electronic renderings of the annual financial statements and the management report in accordance with abs. satz nr. number hgb.the deposits received from retrocessionaires and other liabilities are valued at the settlement amounts.shares units or shares in investment funds and other variableyield securities are valued according to the strict or modified lowerofcostormarket principle depending on the intended use. securities intended for use on a continuing basis in the normal course of business activities are valued according to the modified lowerofcostormarket principle b of the commercial code hgb in conjunction with of the commercial code hgb. permanent impairments are recognised through profit or loss.bearer debt securities and other fixedincome securities are valued according to the strict or modified lowerofcostormarket principle depending on the intended use. bearer debt securities intended for use on a continuing basis in the normal course of business activities are valued at initial cost plus or minus cumulative amortisation according to c of the commercial code hgb. permanent impairments are recognised through profit or loss pursuant to sentence of the commercial code hgb.the portfolio includes a special fund launched for hannover rück se by an external manager. the companys share of the fund is . the fund in question is a highyield fund investing principally in european fixedincome securities. an index composed of the iboxx universe is used as the benchmark. for hannover rück se a total amount of eur thousand eur thousand was distributed in the year under review. as in the previous year no gains on disposal were realised through the sale of unit certificates.the increase in the provisions for anticipated losses is due principally to the negative fair value of a derivative on the life side.a in the companys annual financial statements premium reserves amounting to eur million of total assets are reported under the technical provisions balance sheet item. the premium reserve was recognized primarily for the reinsurance activities in the life and health reinsurance segments.base. the review of the quality of the auditing was carried out using the system put in place in previous years. in one meeting the committee focused on the development of the companys major equity participations. the important topic of esgsustainability was also discussed by the committee on multiple occasions including in connection with the current reporting framework. the committee again opted for an external audit of the nonfinancial information statement and commissioned pricewaterhousecoopers gmbh wirtschaftsprüfungsgesellschaft to conduct this. the implementation of the new financial reporting standard ifrs was another point of emphasis in the committees deliberations in the financial year.the supervisory board would like to express its recognition and special appreciation to the executive board and above all to the employees for their efforts.the audit reports were distributed to all the members of the super visory board and explored in detail with the participation of the auditors at the supervisory board meeting held in march to consider the annual results. the auditors will also be present at the annual general meeting.property is valued at the purchase or construction cost less depreciation in accordance with the normal operational useful life. impairments are taken only if the reduction in value will probably be permanent sentence of the commercial code hgb.on december hannover re ireland dac dublin ireland sold its participation in somerset reinsurance holdings ltd. hamilton bermuda to hannover rück se. hannover rück se thus held in somerset reinsurance holdings ltd. on december hannover re contributed its participation in somerset reinsurance holdings ltd. to somerset holdings international ltd. hamilton bermuda. as compensation hannover re received a participation of in somerset holdings international ltd. as well as a cash consideration.dr. lipowsky since april chairwoman of the finance and audit committee and prior to her mr. haas in the same role as chairman engaged in a regular dialogue during with the chief financial officer and the independent auditor on the topics of financial reporting auditing of the financial statements and the internal control system. all in all we were involved in decisions taken by the executive board and assured ourselves of the lawfulness regularity and efficiency of the companys management as required by our statutory responsibilities and those placed upon us by the companys articles of association.the average size of the workforce was in the year under review of whom were executive staff and employees.the equalisation reserve is set up in accordance with the notes to of the regulation on the accounting of insurance undertakings rechversv the similar provisions are constituted in accordance with of the regulation on the accounting of insurance undertakings rechversv. with respect to insurance lines other property insurance and other indemnity insurance separate profit and loss accounts are drawn up only for the fidelity line.we also exchanged views with the executive board on the current strategy cycle and the status of target achievement. we discussed the major findings from the compliance audit and risk reports. the respective function holders of the key functions were available to answer questions for this purpose. we adopted a resolution on the annual revision of the investment guidelines in which regard no significant change to the general investment strategy was proposed. additionally the variable remuneration of the members of the executive board was defined on the basis of the findings with respect to attainment of the respective individual targets for the financial year. in this context as usual we factored the findings of external remuneration surveys into our deliberations for the purpose of making a market comparison.our objectives are to obtain reasonable assurance about whether the annual financial statements as a whole are free from material misstatement whether due to fraud or error and whether the management report as a whole provides an appropriate view of the companys position and in all material respects is consistent with the annual financial statements and the knowledge obtained in the audit complies with the german legal requirements and appropriately presents the opportunities and risks of future development as well as to issue an auditors report that includes our audit opinions on the annual financial statements and on the management report.based on the controls testing we carried out additional analytical and substantive audit procedures relating to the measurement of the premium reserves. in our tests of details procedures we evaluated the correct and proper use of the available cedant settlements for calculating the premium reserves. thereby we also assessed the appropriateness of the material assumptions by analyzing how the actuarial methods applied were derived. in particular we examined whether sufficient collateral was factored into the valuation according to criteria of german commercial law and whether it was necessary to strengthen reserves. further more we analyzed the development of premium reserves as compared to the previous year particularly in light of the fact that the assumptions correspond to the currently available cedant information current business developments and our expectations based on market observations.identify and assess the risks of material noncompliance with the requirements of abs. hgb whether due to fraud or error design and perform assurance procedures responsive to those risks and obtain assurance evidence that is sufficient and appropriate to provide a basis for our assurance opinion.by january the goal of appointing another woman to the executive board had already been achieved since that date two woman have sat on the executive board which is composed of eight members.we adopted a resolution on the annual revision of the investment guidelines in which regard no significant change to the general investment strategy was proposed. additionally the variable remuneration of the members of the executive board was defined on the basis of the findings with respect to attainment of the respective individual targets for the financial year. in this context as usual we factored the findings of external remuneration surveys into our deliberations for the purpose of making a market comparison. in preparation for the annual general meeting on may the agenda was discussed and approved and in view of the protracted uncertainties connected with the pandemic we opted to hold the general meeting virtually with no inperson attendance. in terms of content the remuneration report for the executive board was to be submitted to the general meeting for approval pursuant to a para. stock corporation act aktg.furthermore the supervisory board explored the possible contribution of part of the companys private equity portfolio to a joint venture.parttime employees are not subject to a cap on hours that they have built up on their time account which can be carried forward without any time limitation. in consultation with the employees supervisor overtime may be reduced by taking off entire days without any other restrictions even several weeks at a time provided this does not conflict with work requirements.details of supervisory board memberships within the meaning of sentence first halfsentence of the stock corporation act aktg. the other details are those on comparable control boards at other domestic and foreign business enterprises pursuant to sentence second halfsentence of the stock corporation act aktg.the current values can be found in the declaration on corporate governance on page et seq. furthermore we used the meeting as an opportunity to have the updated code of conduct presented to us. the code of conduct has now been published on the companys website httpswww.hannoverre.comcodeofconduct.pdf.ment and performance of the business and the position of the company together with a description of the principal opportunities and risks associated with the expected development of hannover rück se.the fair value disclosures pursuant to of the regulation on the accounting of insurance undertakings rechversv were determined entirely in the financial year.based on the controls testing we carried out additional analytical and substantive audit procedures relating to the measurement of the claims provision. in light of the significance of the claims provision for the overall business of the company our internal measurement specialists assessed the appropriateness of the methods used by the company. furthermore our internal measurement specialists evaluated the models used by the company and assumptions made by the executive directors based on industry expertise and experience with recognized actuarial practice. in this context the assessment of the legal representatives regarding increased inflation rates was also acknowledged. in particular we examined whether sufficient collateral was factored into the valuation according to criteria of german commercial law and whether it was necessary to strengthen reserves. thereby we verified the valuation methods for consistency of use.we have performed assurance work in accordance with abs. a hgb to obtain reasonable assurance as to whether the rendering of the annual financial statements and the management report hereinafter the esef documents contained in the electronic file hannoverruecksejalb.zip and prepared for publication purposes complies in all material respects with the requirements of abs. hgb for the electronic reporting format esef format. in accordance with german legal requirements this assurance work extends only to the conversion of the information contained in the annual financial statements and the management report into the esef format and therefore relates neither to the information contained within these renderings nor to any other information contained in the electronic file identified above.the finance and audit committee considered inter alia the consolidated financial statement and the quarterly reports drawn up in accordance with ifrs and the annual financial statement of hannover r ü ck se drawn up in accordance with the german commercial code hgb and it discussed with the independent auditors their reports on these financial statements. as in the previous years an expert opinion on the adequacy of the loss reserves in property and casualty reinsurance was noted the retrocession structure of the hannover re group as well as reports of the key functions were received and considered. in addition the committee examined the investment structure and investment income including the stress tests with regard to the investments and their implications for net income and the equityfor the purposes of the assessment we also evaluated the design and effectiveness of the controls established by the company for the purpose of calculating and recording the premium reserves. we focused in particular on controls designed to ensure that new products and policies are correctly classified and that changes in assumptions are correctly implemented in the systems.the executive directors are responsible for the preparation of the annual financial statements that comply in all material respects with the requirements of german commercial law and that the annual financial statements give a true and fair view of the assets liabilities financial position and financial performance of the company in compliance with german legally required accounting principles. in addition the executive directors are responsible for such internal control as they in accordance with german legally required accounting principles have determined necessary to enable the preparation of annual financial statements that are free from material misstatement whether due to fraud i.e. fraudulent financial reporting and misappropriation of assets or error.the fair values of securities traded in illiquid markets as well as those of the sundry loans and loans to affiliated companies and participating interests are calculated on the basis of yield curves taking into account the creditworthiness of the specific debtor and the currency of the loan.as security for technical liabilities various financial institutions have furnished sureties for our company in the form of letters of credit. the total amount of the letters of credit which also provide security for subsidiaries was eur million eur million as at the balance sheet date.there were no further contingent liabilities or other financial commitments that were not evident from the annual balance sheet.the principles set out by idw rh fab have been applied for the first time in the financial year to the measurement of provisions for insured direct commitments. the pension provisions for nonunitlinked employeefunded commitments are calculated according to the projected unit credit method insofar as the benefits are not covered by a pension insurance policy. in the case of insured benefits the settlement amount corresponds to the present value of the actuarial reserve for the life insurance contract plus surplus participation. the effect of application of idw rh fab amounts to eur million. a rate of compensation increase of and pension indexation of are assumed. fluctuation probabilities are determined separately according to age and gender.the supervisory board concurred with the opinions of the auditors and approved the annual financial statements and the consolidated financial statements the annual financial statements are thereby adopted. our proposal regarding the appropriation of the disposable profit for is in accordance with that of the executive board.in the group annual report. in addition we nominated dr. lipowsky and mr. haas as financial experts in accordance with para. stock corporation act aktg with dr. lipowsky having the necessary expertise particularly in accounting matters and mr. haas in particular when it comes to the auditing of financial statements. with these further advances in corporate governance we were then able to join the executive board in issuing an unqualified declaration of conformity pursuant to stock corporation act aktg regarding compliance with the german corporate governance code. we also discussed and approved as the full supervisory board the individual targets for the members of the executive board for . the focus here was on the findings of the organisational health check sustainability and the strategic objectives.acquired reinsurance premiums are accounted for in accordance with the terms and conditions of the reinsurance policies. in the absence of settlements of cedants the company made supplementary or complete estimates of the contributions. of the total gross premiums recognized approximately eur million were estimated. the estimates were based on assumptions and are therefore subject to considerable uncertainties and scope for judgment.hannover re has placed subordinated debt on the european capital market through its subsidiary hannover finance luxembourg s.a. hannover re has secured by subordinated guarantee the debt issued in which has a volume of eur million. in addition hannover re has placed two subordinated debts of eur million each a senior bond of eur million and two subordinated debts of eur million each on the european capital market. additional subordinated debt of eur million was placed in . the total amount of liabilities with a remaining maturity of more than five years is eur million.on november the executive board and supervisory board of hannover rück se submitted an updated declaration of conformity pursuant to of the stock corporation act aktg regarding compliance with the german corporate governance code and made it permanently accessible on the companys website www.hannoverre.comdeclarationofconformity.commencing in the company commissioned a comprehensive analysis of employee salaries using data analytics taking into account length of service and previous experience as well as current job title and career stage in order to obtain the most accurate possible information about whether an unjustified pay gap exists between employees and if so in which departments and in what amount. management has since 

In [ ]:
scores = df.columns.drop("Sentences")

In [ ]:
df[scores].mean(0).sort_values(ascending=False)

H           0.804783
B           0.757923
Q           0.696842
P           0.689872
C           0.664623
I           0.604747
N           0.603874
G           0.583012
F           0.548879
J           0.484441
K           0.342283
NO_CLASS         NaN
M                NaN
L                NaN
D                NaN
E                NaN
A                NaN
dtype: float64

In [ ]:
recordings = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/results/BERT_classification/dataset__stoxx_600_sentence_len_6__nace_level_1/recordings.csv")

In [ ]:
json.loads(recordings["classification_lvl_1"][0])

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

In [ ]:
l = []
for i in range(len(recordings)): 
    d = ast.literal_eval(recordings["classification_lvl_1"][i])
    print(list(d.items())[0][0][0])
    l.append(list(d.items())[0][0][0])

J
J
J
H
G
H
J
Q
Q
Q
Q
H
Q
Q
H
Q
J
J
H
Q
N
Q
Q
H
H
G
Q
Q
H
Q
H
Q
N
Q
N
H
G
Q
H
Q
Q
H
Q
Q
H
J
Q
H
H
Q
J
J
N
Q
Q
Q
Q
G
G
Q
G
N
Q
H
Q
H
K
Q
H
Q
Q
Q
Q
G
Q
H
Q
J
Q
Q
Q
G
Q
Q
Q
G
H
J
J
Q
H
Q
N
J
Q
H
H
Q
Q
N
J
N
Q
Q
N
Q
J

In [ ]:
pd.Series(l).value_counts()

Q    50
H    23
J    15
G     9
N     9
K     1
Name: count, dtype: int64

In [ ]:
recordings["classification_lvl_1"]

0      {'J_INFORMATION AND COMMUNICATION': 0.39629662...
1      {'J_INFORMATION AND COMMUNICATION': 0.33750051...
2      {'J_INFORMATION AND COMMUNICATION': 0.35369017...
3      {'H_TRANSPORTATION AND STORAGE': 0.38912087678...
4      {'G_WHOLESALE AND RETAIL TRADE; REPAIR OF MOTO...
                             ...
102    {'Q_HUMAN HEALTH AND SOCIAL WORK ACTIVITIES': ...
103    {'Q_HUMAN HEALTH AND SOCIAL WORK ACTIVITIES': ...
104    {'N_ADMINISTRATIVE AND SUPPORT SERVICE ACTIVIT...
105    {'Q_HUMAN HEALTH AND SOCIAL WORK ACTIVITIES': ...
106    {'J_INFORMATION AND COMMUNICATION': 0.39572551...
Name: classification_lvl_1, Length: 107, dtype: object