In [2]:
import numpy as np
import pandas as pd
import os
import sys
import glob
import tqdm
import re
from typing import List

os.chdir("/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis")
sys.path.append("../../benchmark")
import test_base
from sentence_splitter import split_text_into_sentences
from BERT_classifier.Classify_report_with_BERT import classification_report_BERT
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [3]:
sentence_length = 6

## Test using a BERT-Classification Model trained on paragraphs to classify an entire report.

**Function:** pdf -> NACE Class

In [4]:
dataset_path = "data/datasets/german_annual_reports"
dataset_path = "data/datasets/stoxx_600_extended"
dataset_path = "data/datasets/reports_subset_from_full_data_1"
dataset_path = "data/datasets/reports_subset_from_full_data_3"
dataset_path = "data/datasets/stoxx_600"

In [5]:
over_view_df_path = os.path.join(dataset_path, os.path.basename(dataset_path) + "_overview.csv")

dataset_path_texts = os.path.join(dataset_path, "TXTs")

dataset_name = os.path.basename(dataset_path)

In [6]:
nace_classes = pd.read_csv(over_view_df_path, index_col=0, sep=";")
nace_classes.head()

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
483,3i Group plc,III-GB,III-GB,701.210162,1276.962137,NaN,66.30,K,NaN,NaN
354,A.P. Moller - Maersk A/S Class B,MAERSK.B-DK,MAERSK.B-DK,77568.022858,47226.219381,51288.2262335699,50.20,H,NaN,NaN
275,A2A S.p.A.,A2A-IT,A2A-IT,22938.000000,14492.000000,NaN,35.11,D,NaN,NaN
107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
122,Aalberts N.V.,AALB-NL,AALB-NL,3230.000000,3324.000000,3148.6,25.93,C,Aalberts N.V.1.pdf,NaN

In [ ]:

nace_classes

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
483,3i Group plc,III-GB,III-GB,701.210162,1276.962137,NaN,66.30,K,NaN,NaN
354,A.P. Moller - Maersk A/S Class B,MAERSK.B-DK,MAERSK.B-DK,77568.022858,47226.219381,51288.2262335699,50.20,H,NaN,NaN
275,A2A S.p.A.,A2A-IT,A2A-IT,22938.000000,14492.000000,NaN,35.11,D,NaN,NaN
107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
122,Aalberts N.V.,AALB-NL,AALB-NL,3230.000000,3324.000000,3148.6,25.93,C,Aalberts N.V.1.pdf,NaN
...,...,...,...,...,...,...,...,...,...,...
577,WPP Plc,WPP-GB,WPP-GB,16910.961740,17068.346685,17413.6933169365,73.11,M,NaN,NaN
114,Yara International ASA,YAR-NO,YAR-NO,22742.705923,14273.219511,12820.6705029309,20.15,C,Yara International ASA2.pdf,NaN
344,Zalando SE,ZAL-DE,ZAL-DE,10344.800000,10143.100000,10572.5,47.91,G,NaN,NaN
246,Zealand Pharma A/S,ZEAL-DK,ZEAL-DK,13.977698,46.005625,8.40500161716342,21.20,C,NaN,NaN
442,Zurich Insurance Group Ltd,ZURN-CH,ZURN-CH,41393.017468,72341.013163,78985.6071849965,65.11,K,Zurich Insurance Group Ltd2.pdf,NaN

In [ ]:
report_to_nace_class = nace_classes.dropna(subset=["Report"]).set_index('Report').to_dict()["NACE"]
report_to_nace_class = {report[0][:-4] + ".txt": report[1] for report in report_to_nace_class.items()}
len(report_to_nace_class)

291

In [ ]:
reports_path = glob.glob(os.path.join(dataset_path, "PDFs/*.pdf"))
len(reports_path)

261

In [ ]:
reports_path = glob.glob(os.path.join(dataset_path_texts, "*.txt"))
len(reports_path)

263

In [ ]:
## ! Only filter the description pages !

# nace_classes_description_pages = nace_classes.dropna(subset="description_page")
# nace_classes_description_pages
# description_page_path = "data/datasets/stoxx_600/company_descriptions_txt/"
# reports_path = [description_page_path + name.replace("pdf", "txt") for name in nace_classes_description_pages["Report"].to_list()]

In [ ]:
def get_tables(lines: list): 
    tables = []
    current_table = []

    for line in lines:
        if line.strip().startswith("|"):  # line belongs to a table
            current_table.append(line.strip())
        else:
            if current_table:  # table ended
                tables.append("\n".join(current_table))
                current_table = []

    # catch last table if file ends without empty lines
    if current_table:
        tables.append("\n".join(current_table))

    return tables

def preprocess_report(pdf_path: str) -> List[str]:

    with open(pdf_path, "r") as f: 
        text = f.read()
    
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]

    tables = get_tables(lines)

    # drop if condidtion is True
    conditions = [
        # filter images
        lambda line: line == '<!-- image -->',
        
        #filter tables 
        lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False, 

        # filter headers
        #lambda line: line.strip()[0] == "#" if len(line) > 0 else True,

        # filter sentences
        #lambda line: "." not in line,
        
        # more than 50% is numbers
        lambda line: sum(ch.isalpha() for ch in line) / len(line) < 0.5,

        # minimum 3 words 
        lambda line: len(re.sub(r"[^a-zA-ZäöüÄÖÜß\s]", '', line).strip().split(" ")) < 3,

        # Minimum 2 Sentences
        #lambda line: sum([0 if len(sentence.split(" ")) < 3 else 1 for sentence in split_text_into_sentences(line, "en")]) < 2

    ]
    accepted_lines = [line for line in lines if not any(condition(line) for condition in conditions)]
    accepted_lines += tables

    chunks = []

    for line in accepted_lines: 
        sentences = split_text_into_sentences(line, language='en')
        sentences = [sentence.strip() for sentence in sentences]
        sentences = [sentence for sentence in sentences if sentence != ""]
        new_chunks = [(" ".join(sentences[i:i+sentence_length])).strip() for i in range(0, len(sentences), 3)]

        chunks += new_chunks
    
    if len(chunks) == 0: 
        return []
    elif len(chunks) == 1: 
        return chunks

    # if there is only one sentence in the last chunk, balance the two last chunks
    if len(split_text_into_sentences(chunks[-1], language = "en")) == 1: 
        last_two_chunks = chunks[-2] + " " + chunks[-1]
        chunks[-2] = last_two_chunks[0:(len(last_two_chunks) + 1) // 2]
        chunks[-1] = last_two_chunks[(len(last_two_chunks) + 1) // 2: (len(last_two_chunks)) - (len(last_two_chunks) + 1) // 2]

    chunks = [re.sub(r'\b\d+\.\d+\b', '', chunk) for chunk in chunks]
    chunks = [re.sub(r"[^a-zA-ZäöüÄÖÜß.\s]", '', chunk) for chunk in chunks]
    chunks = [re.sub(r"\s+", " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'\.{2,}', " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'^\d+\.\s*', " ", chunk) for chunk in chunks]
    chunks = [chunk.lower() for chunk in chunks]
    chunks = [chunk.strip() for chunk in chunks]

    return chunks

In [ ]:
ckpt = "results/BERT_models/results_null_classifiers__cos_thres_0.5__bert-base-uncased__train_full_model__some_labels/checkpoint-2331"
ckpt = "results/BERT_models/results_null_classifiers__cos_thres_0.5__bert-base-uncased__train_full_model__some_labels/checkpoint-2331"

ckpt = "results/BERT_models/results__new_approach_data__num_layers_2bert-base-uncased__train_full_model__some_labels/checkpoint-15990"
ckpt = "results/BERT_models/results__new_approach_data__num_layers_2bert-base-uncased__train_full_model__some_labels/checkpoint-15990"

model = classification_report_BERT.load_custom_bert_from_checkpoint(ckpt_path=ckpt)
tokenizer = AutoTokenizer.from_pretrained(ckpt)

In [ ]:
for i in range(1,2):
    nace_level = i

    result_path = f"results/BERT_classification/dataset__{dataset_name}_sentence_len_{sentence_length}__nace_level_{nace_level}"

    res = test_base.test_report_classification(
        reports_path=reports_path,
        preprocess_report=preprocess_report, 
        report_to_nace_class=report_to_nace_class, 
        result_path = result_path,
        level=i,
        overwrite=True, 
        classification_function=classification_report_BERT.classify_report, 
        path_nace_code_descriptions="data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", 
        model=model,
        tokenizer=tokenizer)

  0%|                                                                                                                                                                                          | 0/63 [00:00<?, ?it/s]

data/datasets/stoxx_600/company_descriptions_txt/AAK AB1.txt

  2%|██▊                                                                                                                                                                               | 1/63 [00:01<01:24,  1.37s/it]

1.1418273448944092
0.04811882972717285
0.04051613807678223
data/datasets/stoxx_600/company_descriptions_txt/ABB Ltd.2.txt
0.03274273872375488
0.06181836128234863
0.1740734577178955
0.04375171661376953
0.04293251037597656
0.0264127254486084
0.0457155704498291
0.03357362747192383

  3%|█████▋                                                                                                                                                                            | 2/63 [00:02<01:08,  1.13s/it]

data/datasets/stoxx_600/company_descriptions_txt/Accelleron Industries AG1.txt

  5%|████████▍                                                                                                                                                                         | 3/63 [00:02<00:45,  1.32it/s]

0.0379335880279541
0.028881549835205078
0.024559736251831055
0.021175146102905273
0.025891542434692383
data/datasets/stoxx_600/company_descriptions_txt/Acciona SA2.txt
0.02565312385559082
data/datasets/stoxx_600/company_descriptions_txt/Accor SA1.txt
0.030863285064697266
0.027241945266723633
0.020139217376708984
0.03211855888366699
0.032724618911743164
0.027639389038085938
0.028070688247680664

  8%|██████████████▏                                                                                                                                                                   | 5/63 [00:03<00:29,  1.97it/s]

0.04867839813232422
data/datasets/stoxx_600/company_descriptions_txt/Ackermans & van Haaren NV1.txt
0.055478811264038086
0.027529001235961914
0.02719402313232422
0.0633840560913086
0.029198646545410156
0.03401064872741699
0.06487202644348145
0.03023695945739746
0.025882720947265625
0.02825140953063965
0.02787470817565918
0.028609275817871094
0.03803277015686035

 10%|████████████████▉                                                                                                                                                                 | 6/63 [00:04<00:37,  1.52it/s]

data/datasets/stoxx_600/company_descriptions_txt/Adecco Group AG1.txt

 11%|███████████████████▊                                                                                                                                                              | 7/63 [00:04<00:37,  1.51it/s]

0.05654191970825195
0.03750109672546387
0.04409456253051758
0.04208540916442871
0.032781362533569336
data/datasets/stoxx_600/company_descriptions_txt/Admiral Group plc1.txt
0.06917738914489746
0.0743403434753418
0.04350471496582031
0.04004669189453125
0.12482857704162598
0.04925990104675293
0.0747377872467041
0.06866860389709473
0.04363107681274414
0.04786252975463867
0.04507112503051758
0.053199052810668945
0.07436347007751465
0.06599235534667969
0.05301952362060547
0.03134775161743164
0.16145563125610352
0.02756023406982422
0.02966761589050293
0.0366673469543457
0.023999929428100586
0.021642684936523438
0.03273725509643555

 13%|██████████████████████▌                                                                                                                                                           | 8/63 [00:07<01:06,  1.21s/it]

0.03477215766906738
0.028851747512817383
0.026593685150146484
0.032181739807128906
0.019690752029418945
0.021064281463623047
data/datasets/stoxx_600/company_descriptions_txt/Airbus SE1.txt
0.07534074783325195
0.0331575870513916
0.03630781173706055
0.04814553260803223
0.04249215126037598
0.09357452392578125
0.050679922103881836
0.06700587272644043
0.032713890075683594
0.06154918670654297
0.13903474807739258
0.06040334701538086
0.1748034954071045
0.04627490043640137
0.059732675552368164
0.05523538589477539
0.10093331336975098
0.040186166763305664
0.030501365661621094
0.06936430931091309
0.12049388885498047
0.04842019081115723
0.025156497955322266
0.0371854305267334
0.020996570587158203
0.05747509002685547

 14%|█████████████████████████▍                                                                                                                                                        | 9/63 [00:10<01:34,  1.75s/it]

0.0252532958984375
0.034590959548950195
0.03392601013183594
0.0315093994140625
data/datasets/stoxx_600/company_descriptions_txt/Alcon AG1.txt
0.056710243225097656
0.06556987762451172
0.05396747589111328
0.08003520965576172
0.09050321578979492
0.06389045715332031
0.0253140926361084

 16%|████████████████████████████                                                                                                                                                     | 10/63 [00:11<01:20,  1.51s/it]

0.11909174919128418
0.05402255058288574
data/datasets/stoxx_600/company_descriptions_txt/Allfunds Group plc1.txt
0.05304312705993652
0.12080264091491699
0.03686976432800293
0.033623456954956055
0.034597158432006836
0.04185009002685547
0.04044771194458008
0.035970211029052734
0.029947757720947266
0.032537221908569336

 17%|██████████████████████████████▉                                                                                                                                                  | 11/63 [00:12<01:10,  1.35s/it]

data/datasets/stoxx_600/company_descriptions_txt/Allreal Holding AG1.txt
0.05240917205810547
0.07873964309692383
0.03539109230041504
0.049271345138549805
0.03206133842468262
0.03412604331970215
0.033444881439208984
0.03881406784057617
0.027614593505859375
0.04416537284851074
0.04772019386291504
0.043431997299194336
0.036278724670410156
0.03920793533325195
0.0685572624206543

 19%|█████████████████████████████████▋                                                                                                                                               | 12/63 [00:13<01:11,  1.40s/it]

0.0695488452911377
data/datasets/stoxx_600/company_descriptions_txt/ANDRITZ AG1.txt
0.05585932731628418
0.09205150604248047
0.060141801834106445
0.05461835861206055
0.05632328987121582
0.031310081481933594
0.02676701545715332
0.06389927864074707
0.04312634468078613
0.05181598663330078
0.034410715103149414
0.029860258102416992
0.026435375213623047
0.028641700744628906

 21%|████████████████████████████████████▌                                                                                                                                            | 13/63 [00:15<01:15,  1.51s/it]

0.06091141700744629
0.03966569900512695
0.06065988540649414
data/datasets/stoxx_600/company_descriptions_txt/Anglo American plc1.txt
0.023120403289794922
0.0208587646484375
0.026459932327270508
0.020618200302124023
0.021751880645751953
0.022576093673706055
0.018720149993896484
0.02524852752685547
0.021778106689453125

 22%|███████████████████████████████████████▎                                                                                                                                         | 14/63 [00:16<01:10,  1.43s/it]

0.024251699447631836
0.03108048439025879
0.021934032440185547
0.02452540397644043
0.02205944061279297
0.023935317993164062
0.025438308715820312
data/datasets/stoxx_600/company_descriptions_txt/Anheuser-Busch InBev SANV3.txt
0.051497459411621094
0.08653378486633301
0.138685941696167
0.04657578468322754
0.04149508476257324
0.03642845153808594
0.049376487731933594
0.04274702072143555
0.05549049377441406
0.08067846298217773
0.03603196144104004

 24%|██████████████████████████████████████████▏                                                                                                                                      | 15/63 [00:18<01:06,  1.38s/it]

0.050359487533569336
data/datasets/stoxx_600/company_descriptions_txt/Antofagasta plc1.txt

 25%|████████████████████████████████████████████▉                                                                                                                                    | 16/63 [00:18<00:51,  1.10s/it]

0.026300430297851562
0.029851675033569336
0.030231237411499023
0.02876138687133789
0.028604745864868164
0.03230476379394531
data/datasets/stoxx_600/company_descriptions_txt/Arcadis NV1.txt

 27%|███████████████████████████████████████████████▊                                                                                                                                 | 17/63 [00:19<00:43,  1.05it/s]

0.043415069580078125
0.04613804817199707
0.02782154083251953
0.03480935096740723
0.034561872482299805
0.033362388610839844
data/datasets/stoxx_600/company_descriptions_txt/argenx SE1.txt

 29%|██████████████████████████████████████████████████▌                                                                                                                              | 18/63 [00:19<00:35,  1.27it/s]

0.03418540954589844
0.06968879699707031
0.05645942687988281
0.027973651885986328
data/datasets/stoxx_600/company_descriptions_txt/Arkema SA1.txt
0.042346954345703125
0.06100916862487793
0.03167724609375
0.06245565414428711
0.03352522850036621
0.055059194564819336
0.08086681365966797
0.03942108154296875
0.03473329544067383
0.04515886306762695

 32%|████████████████████████████████████████████████████████▏                                                                                                                        | 20/63 [00:20<00:26,  1.61it/s]

data/datasets/stoxx_600/company_descriptions_txt/Ashtead Group plc1.txt
0.08177852630615234
data/datasets/stoxx_600/company_descriptions_txt/ASM International N.V.1.txt
data/datasets/stoxx_600/company_descriptions_txt/ASR Nederland N.V.1.txt
0.028079748153686523
0.039304494857788086
0.05675053596496582
0.03284502029418945
0.054551124572753906
0.029401302337646484
0.0212860107421875
0.02745985984802246
0.02326178550720215
0.02986598014831543
0.03213930130004883
0.022608041763305664
0.023713350296020508

 35%|█████████████████████████████████████████████████████████████▊                                                                                                                   | 22/63 [00:22<00:26,  1.58it/s]

0.020917415618896484
data/datasets/stoxx_600/company_descriptions_txt/Assicurazioni Generali S.p.A.1.txt
0.027064085006713867
data/datasets/stoxx_600/company_descriptions_txt/Associated British Foods plc1.txt

 38%|███████████████████████████████████████████████████████████████████▍                                                                                                             | 24/63 [00:22<00:18,  2.09it/s]

0.02093338966369629
0.021082401275634766
0.020628690719604492
0.02459406852722168
0.028320789337158203
0.02536487579345703
0.02744889259338379
data/datasets/stoxx_600/company_descriptions_txt/AstraZeneca PLC1.txt

 40%|██████████████████████████████████████████████████████████████████████▏                                                                                                          | 25/63 [00:22<00:15,  2.38it/s]

0.06552481651306152
data/datasets/stoxx_600/company_descriptions_txt/Auto Trader Group PLC3.txt

 41%|█████████████████████████████████████████████████████████████████████████                                                                                                        | 26/63 [00:23<00:14,  2.51it/s]

0.029689788818359375
0.0312802791595459
0.0703272819519043
data/datasets/stoxx_600/company_descriptions_txt/Avanza Bank Holding AB1.txt

 43%|███████████████████████████████████████████████████████████████████████████▊                                                                                                     | 27/63 [00:23<00:14,  2.50it/s]

0.053465843200683594
0.04381608963012695
0.03728055953979492
0.05111861228942871
data/datasets/stoxx_600/company_descriptions_txt/Aviva plc1.txt

 44%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 28/63 [00:23<00:13,  2.65it/s]

0.027830839157104492
0.02991509437561035
0.02894902229309082
data/datasets/stoxx_600/company_descriptions_txt/AXA SA1.txt

 46%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 29/63 [00:24<00:14,  2.36it/s]

0.03684806823730469
0.021451950073242188
0.020801544189453125
0.021414756774902344
0.02583932876586914
0.023136138916015625
0.02179694175720215
0.01951742172241211
0.019188880920410156
data/datasets/stoxx_600/company_descriptions_txt/BAE Systems plc1.txt

 48%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 30/63 [00:24<00:11,  2.84it/s]

0.020980119705200195
0.02692389488220215
0.019072294235229492
data/datasets/stoxx_600/company_descriptions_txt/Bakkafrost PF2.txt

 49%|███████████████████████████████████████████████████████████████████████████████████████                                                                                          | 31/63 [00:24<00:11,  2.74it/s]

0.0193023681640625
0.018910884857177734
0.04007244110107422
0.03521847724914551
0.019544601440429688
0.019220352172851562
0.019199371337890625
data/datasets/stoxx_600/company_descriptions_txt/Balfour Beatty plc1.txt
0.039897918701171875
0.03082895278930664
0.03066539764404297
0.027457714080810547
0.02747201919555664
0.035317182540893555
0.025275468826293945

 51%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 32/63 [00:25<00:14,  2.12it/s]

0.07094860076904297
data/datasets/stoxx_600/company_descriptions_txt/Bank of Ireland Group Plc1.txt
0.0489656925201416
0.034662485122680664
0.02847146987915039
0.03968405723571777
0.08750081062316895
0.037767648696899414
0.023608922958374023
0.06865882873535156
0.05599474906921387
0.05866098403930664
0.03570675849914551
0.0530848503112793
0.04514312744140625
0.06143927574157715

 52%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 33/63 [00:27<00:23,  1.29it/s]

data/datasets/stoxx_600/company_descriptions_txt/Banque Cantonale Vaudoise1.txt
0.0691378116607666
0.06674647331237793
0.13441777229309082
0.054352760314941406
0.14829301834106445
0.05077099800109863
0.055846452713012695
0.0518193244934082

 54%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 34/63 [00:28<00:27,  1.06it/s]

0.09174537658691406
data/datasets/stoxx_600/company_descriptions_txt/Barry Callebaut AG3.txt
0.03381943702697754
0.028900623321533203
0.056717634201049805

 56%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                              | 35/63 [00:29<00:27,  1.03it/s]

0.17485642433166504
0.034154653549194336
0.04947924613952637
0.028717756271362305
0.0314483642578125
data/datasets/stoxx_600/company_descriptions_txt/Bavarian Nordic AS1.txt
0.026018142700195312
data/datasets/stoxx_600/company_descriptions_txt/Bellway p.l.c.1.txt
0.022293567657470703
0.021486282348632812
0.021809816360473633
0.02138066291809082
0.02591729164123535
0.02585148811340332
0.023131608963012695
0.030672073364257812
0.020795106887817383

 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 37/63 [00:30<00:17,  1.49it/s]

0.02038121223449707
data/datasets/stoxx_600/company_descriptions_txt/BKW AG1.txt
0.039628028869628906
0.04676413536071777
0.04007601737976074
0.02926468849182129
0.03680825233459473

 60%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 38/63 [00:30<00:15,  1.59it/s]

0.06866168975830078
data/datasets/stoxx_600/company_descriptions_txt/Boliden AB1.txt

 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 39/63 [00:31<00:14,  1.69it/s]

0.0302886962890625
0.02945852279663086
0.0286557674407959
0.02898120880126953
0.0271298885345459
0.04033493995666504
data/datasets/stoxx_600/company_descriptions_txt/Bollore SE1.txt
0.03772902488708496
0.05132770538330078
0.10296893119812012
0.019428730010986328
0.02318549156188965

 63%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 40/63 [00:32<00:17,  1.34it/s]

0.037374258041381836
0.02219223976135254
0.039487600326538086
0.02549290657043457
data/datasets/stoxx_600/company_descriptions_txt/Brenntag Societas Europaea1.txt

 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 41/63 [00:32<00:12,  1.74it/s]

0.03302717208862305
0.02184462547302246
data/datasets/stoxx_600/company_descriptions_txt/Bridgepoint Group Plc1.txt
0.024755239486694336
data/datasets/stoxx_600/company_descriptions_txt/Cembra Money Bank AG1.txt
0.02576422691345215
0.023656129837036133
0.026638031005859375
0.029296875
0.0312652587890625
0.023798704147338867
0.025285005569458008
0.04886507987976074
0.037262678146362305
0.07137680053710938
0.04615974426269531

 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 43/63 [00:33<00:10,  1.94it/s]

0.047647953033447266
data/datasets/stoxx_600/company_descriptions_txt/Chocoladefabriken Lindt & Spruengli AG2.txt
0.06791543960571289
0.03691291809082031
0.03972983360290527
0.0348811149597168
0.07261157035827637
0.06745672225952148
0.029722929000854492
0.08498835563659668
0.03522801399230957

 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 44/63 [00:34<00:12,  1.46it/s]

0.1693730354309082
0.03313398361206055
data/datasets/stoxx_600/company_descriptions_txt/Coca-Cola HBC AG2.txt
0.034555673599243164
0.028578996658325195
0.032602787017822266
0.030210018157958984
0.047042131423950195
0.02739739418029785
0.07315587997436523
0.025852203369140625
0.04743242263793945
0.05841684341430664
0.0466761589050293

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 45/63 [00:35<00:13,  1.32it/s]

0.028185129165649414
data/datasets/stoxx_600/company_descriptions_txt/COMET Holding AG1.txt
data/datasets/stoxx_600/company_descriptions_txt/ConvaTec Group Plc1.txt
0.02398061752319336
0.034698486328125
0.11175298690795898
0.024074316024780273
0.028532743453979492

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 47/63 [00:36<00:10,  1.58it/s]

0.02601003646850586
0.026456594467163086
0.03351998329162598
0.05894327163696289
data/datasets/stoxx_600/company_descriptions_txt/Danone SA1.txt
0.03864097595214844
0.035530805587768555
0.028873920440673828
0.04046297073364258
0.029509305953979492
0.029676437377929688
0.03366708755493164

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 48/63 [00:37<00:09,  1.52it/s]

0.03239917755126953
data/datasets/stoxx_600/company_descriptions_txt/Dassault Aviation SA1.txt

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 49/63 [00:37<00:08,  1.64it/s]

0.023798227310180664
0.02438187599182129
0.027365446090698242
0.0254514217376709
0.022616863250732422
0.025289058685302734
data/datasets/stoxx_600/company_descriptions_txt/DCC Plc1.txt

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 50/63 [00:38<00:07,  1.77it/s]

0.05056023597717285
0.023161888122558594
0.030048131942749023
0.02063155174255371
0.020615577697753906
0.06002521514892578
data/datasets/stoxx_600/company_descriptions_txt/Derwent London PLC REIT1.txt

 81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 51/63 [00:38<00:06,  1.89it/s]

0.02116847038269043
0.022888898849487305
0.020130634307861328
0.023151397705078125
0.021245956420898438
0.02692580223083496
0.020992517471313477
0.032855987548828125
data/datasets/stoxx_600/company_descriptions_txt/Deutsche Bank Aktiengesellschaft1.txt
0.047074079513549805
0.06057381629943848
0.02597498893737793
0.04718470573425293
0.03038763999938965
0.060019493103027344
0.029433727264404297
0.033696651458740234
0.07672238349914551
0.05131936073303223
0.05047440528869629
0.14075303077697754
0.05482125282287598

 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 52/63 [00:40<00:09,  1.20it/s]

0.05208563804626465
data/datasets/stoxx_600/company_descriptions_txt/Deutsche Lufthansa AG1.txt
0.030196189880371094
0.03370070457458496
0.16426968574523926
0.03170371055603027
0.07653689384460449
0.03545331954956055
0.03834891319274902

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 53/63 [00:40<00:08,  1.21it/s]

data/datasets/stoxx_600/company_descriptions_txt/Diageo PLC1.txt
0.041960716247558594
0.15193819999694824
0.09544992446899414
0.07159161567687988
0.03343844413757324
0.03327059745788574
0.036243438720703125

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 54/63 [00:41<00:07,  1.13it/s]

data/datasets/stoxx_600/company_descriptions_txt/DiaSorin S.p.A.1.txt
0.029506921768188477
0.04185628890991211
0.02852916717529297
0.02768254280090332
0.1079556941986084
0.052161455154418945
0.03995680809020996
0.027039527893066406
0.030055522918701172
0.043801307678222656

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 55/63 [00:43<00:08,  1.04s/it]

0.054880619049072266
0.04475235939025879
0.030327796936035156
data/datasets/stoxx_600/company_descriptions_txt/Direct Line Insurance Group Plc1.txt
0.036641597747802734
0.027150869369506836
0.03037881851196289
0.10056829452514648

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 56/63 [00:44<00:06,  1.05it/s]

0.06508827209472656
0.03598666191101074
data/datasets/stoxx_600/company_descriptions_txt/DSM-Firmenich AG1.txt
0.05851173400878906
0.062450408935546875
0.039168357849121094
0.03510141372680664
0.02555990219116211

 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 57/63 [00:45<00:05,  1.06it/s]

0.035341739654541016
0.03179311752319336
0.04545712471008301
0.03237199783325195
data/datasets/stoxx_600/company_descriptions_txt/Merck KGaA2.txt
0.047911643981933594
0.0698854923248291
0.03954792022705078
0.04488873481750488
0.03893303871154785

 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 58/63 [00:46<00:04,  1.01it/s]

0.05867624282836914
0.036951541900634766
0.027585268020629883
0.0308229923248291
data/datasets/stoxx_600/company_descriptions_txt/Orkla ASA1.txt

 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 59/63 [00:46<00:03,  1.33it/s]

0.030796051025390625
0.0276336669921875
data/datasets/stoxx_600/company_descriptions_txt/Scout24 SE3.txt
0.059842586517333984
0.09148526191711426
0.11578965187072754
0.02886223793029785
0.030079126358032227
0.03795886039733887
0.03283262252807617
0.06755495071411133

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 60/63 [00:47<00:02,  1.05it/s]

0.0433039665222168
0.029027938842773438
0.044294118881225586
data/datasets/stoxx_600/company_descriptions_txt/Severn Trent Plc1.txt

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 61/63 [00:48<00:01,  1.30it/s]

0.02134084701538086
0.01930093765258789
0.021131038665771484
0.020958662033081055
0.025776386260986328
0.03090977668762207
data/datasets/stoxx_600/company_descriptions_txt/Siemens Energy AG1.txt
0.0461578369140625
0.1270439624786377
0.028881311416625977
0.12002229690551758
0.036280155181884766
0.0322265625
0.043586015701293945
0.033159494400024414
0.025716304779052734

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 62/63 [00:49<00:00,  1.16it/s]

0.03682756423950195
0.033178091049194336
0.11234474182128906
data/datasets/stoxx_600/company_descriptions_txt/Signify NV3.txt
0.059760332107543945
0.059082984924316406
0.024661779403686523
0.02480602264404297

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:49<00:00,  1.26it/s]

0.15680885314941406
0.0451207160949707
0.029911041259765625
0.024290800094604492