In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", sep="\t")

In [3]:
df.head()

,ORDER_KEY,ID,CODE,NAME,PARENT_ID,LEVEL,Includes,IncludesAlso,Excludes
0,200,A,A,"AGRICULTURE, FORESTRY AND FISHING",NaN,1,This section includes the exploitation of vege...,NaN,NaN
1,300,1,1,"Crop and animal production, hunting and relate...",A,2,"This division includes two basic activities, n...",This division also includes service activities...,Agricultural activities exclude any subsequent...
2,350,11,01.1,Growing of non-perennial crops,1,3,This group includes the growing of non-perenni...,NaN,NaN
3,355,111,01.11,"Growing of cereals (except rice), leguminous c...",11,4,This class includes all forms of growing of ce...,NaN,"This class excludes:\n- growing of rice, see 0..."
4,360,112,01.12,Growing of rice,11,4,This class includes:\n- growing of rice (inclu...,NaN,NaN

In [4]:
id = "3"

In [5]:
(df["PARENT_ID"] == id).sum().item()

2

In [6]:
df["NBR_CHILDREN"] = None

In [7]:
for i, row in df.iterrows(): 
    id = row["ID"]
    nbr_children = (df["PARENT_ID"] == id).sum().item()
    df.loc[i, "NBR_CHILDREN"] = int(nbr_children)

In [8]:
df

,ORDER_KEY,ID,CODE,NAME,PARENT_ID,LEVEL,Includes,IncludesAlso,Excludes,NBR_CHILDREN
0,200,A,A,"AGRICULTURE, FORESTRY AND FISHING",NaN,1,This section includes the exploitation of vege...,NaN,NaN,3
1,300,1,1,"Crop and animal production, hunting and relate...",A,2,"This division includes two basic activities, n...",This division also includes service activities...,Agricultural activities exclude any subsequent...,7
2,350,11,01.1,Growing of non-perennial crops,1,3,This group includes the growing of non-perenni...,NaN,NaN,8
3,355,111,01.11,"Growing of cereals (except rice), leguminous c...",11,4,This class includes all forms of growing of ce...,NaN,"This class excludes:\n- growing of rice, see 0...",0
4,360,112,01.12,Growing of rice,11,4,This class includes:\n- growing of rice (inclu...,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...
991,51295,9820,98.20,Undifferentiated service-producing activities ...,982,4,This class includes the undifferentiated subsi...,NaN,NaN,0
992,51495,U,U,ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS A...,NaN,1,This class includes:\n- activities of internat...,NaN,NaN,1
993,51595,99,99,Activities of extraterritorial organisations a...,U,2,NaN,NaN,NaN,2
994,51645,990,99.0,Activities of extraterritorial organisations a...,99,3,NaN,NaN,NaN,1
995,51650,9900,99.00,Activities of extraterritorial organisations a...,990,4,This class includes:\n- activities of internat...,This class also includes:\n- activities of dip...,NaN,0

In [9]:
df.to_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", sep="\t")

In [ ]:
df[df["LEVEL"] == 1]["NBR_CHILDREN"].value_counts()

NBR_CHILDREN
3     6
1     5
5     2
4     2
2     2
6     2
24    1
7     1
Name: count, dtype: int64

In [16]:
df[df["LEVEL"] == 2]["NBR_CHILDREN"].value_counts()

NBR_CHILDREN
2     26
3     21
4     11
1      8
5      6
8      5
6      5
9      3
7      1
10     1
11     1
Name: count, dtype: int64

In [ ]:
level = 1

In [36]:
sectors = {}
for i, row in df[df["LEVEL"] == 1].iterrows(): 
    sectors[row["CODE"]] = row["NAME"]
sectors

{'A': 'AGRICULTURE, FORESTRY AND FISHING',
 'B': 'MINING AND QUARRYING',
 'C': 'MANUFACTURING',
 'D': 'ELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLY',
 'E': 'WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES',
 'F': 'CONSTRUCTION',
 'G': 'WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES',
 'H': 'TRANSPORTATION AND STORAGE',
 'I': 'ACCOMMODATION AND FOOD SERVICE ACTIVITIES',
 'J': 'INFORMATION AND COMMUNICATION',
 'K': 'FINANCIAL AND INSURANCE ACTIVITIES',
 'L': 'REAL ESTATE ACTIVITIES',
 'M': 'PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES',
 'N': 'ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES',
 'O': 'PUBLIC ADMINISTRATION AND DEFENCE; COMPULSORY SOCIAL SECURITY',
 'P': 'EDUCATION',
 'Q': 'HUMAN HEALTH AND SOCIAL WORK ACTIVITIES',
 'R': 'ARTS, ENTERTAINMENT AND RECREATION',
 'S': 'OTHER SERVICE ACTIVITIES',
 'T': 'ACTIVITIES OF HOUSEHOLDS AS EMPLOYERS; UNDIFFERENTIATED GOODS- AND SERVICES-PRODUCING ACTIVITIES OF HOUSEHOLDS FOR OWN USE',
 'U': 'ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS AND BODIES'}

In [ ]:
divisions = {}
for i, row in df[df["LEVEL"] == 1].iterrows(): 
    divisions[row["CODE"]] = df[df["PARENT_ID"] == row["CODE"]]["CODE"].to_list()
divisions

{'A': ['1', '2', '3'],
 'B': ['5', '6', '7', '8', '9'],
 'C': ['10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33'],
 'D': ['35'],
 'E': ['36', '37', '38', '39'],
 'F': ['41', '42', '43'],
 'G': ['45', '46', '47'],
 'H': ['49', '50', '51', '52', '53'],
 'I': ['55', '56'],
 'J': ['58', '59', '60', '61', '62', '63'],
 'K': ['64', '65', '66'],
 'L': ['68'],
 'M': ['69', '70', '71', '72', '73', '74', '75'],
 'N': ['77', '78', '79', '80', '81', '82'],
 'O': ['84'],
 'P': ['85'],
 'Q': ['86', '87', '88'],
 'R': ['90', '91', '92', '93'],
 'S': ['94', '95', '96'],
 'T': ['97', '98'],
 'U': ['99']}

In [35]:
classes = {}
for i, row in df[df["LEVEL"] == 2].iterrows(): 
    classes[row["CODE"]] = df[df["PARENT_ID"] == row["CODE"]]["CODE"].to_list()
classes

{'1': ['01.1', '01.2', '01.3', '01.4', '01.5', '01.6', '01.7'],
 '2': ['02.1', '02.2', '02.3', '02.4'],
 '3': ['03.1', '03.2'],
 '5': ['05.1', '05.2'],
 '6': ['06.1', '06.2'],
 '7': ['07.1', '07.2'],
 '8': ['08.1', '08.9'],
 '9': ['09.1', '09.9'],
 '10': ['10.1',
  '10.2',
  '10.3',
  '10.4',
  '10.5',
  '10.6',
  '10.7',
  '10.8',
  '10.9'],
 '11': ['01.11', '01.12', '01.13', '01.14', '01.15', '01.16', '01.19', '11.0'],
 '12': ['01.21',
  '01.22',
  '01.23',
  '01.24',
  '01.25',
  '01.26',
  '01.27',
  '01.28',
  '01.29',
  '12.0'],
 '13': ['01.30', '13.1', '13.2', '13.3', '13.9'],
 '14': ['01.41',
  '01.42',
  '01.43',
  '01.44',
  '01.45',
  '01.46',
  '01.47',
  '01.49',
  '14.1',
  '14.2',
  '14.3'],
 '15': ['01.50', '15.1', '15.2'],
 '16': ['01.61', '01.62', '01.63', '01.64', '16.1', '16.2'],
 '17': ['01.70', '17.1', '17.2'],
 '18': ['18.1', '18.2'],
 '19': ['19.1', '19.2'],
 '20': ['20.1', '20.2', '20.3', '20.4', '20.5', '20.6'],
 '21': ['02.10', '21.1', '21.2'],
 '22': ['02.20', '22.1', '22.2'],
 '23': ['02.30',
  '23.1',
  '23.2',
  '23.3',
  '23.4',
  '23.5',
  '23.6',
  '23.7',
  '23.9'],
 '24': ['02.40', '24.1', '24.2', '24.3', '24.4', '24.5'],
 '25': ['25.1', '25.2', '25.3', '25.4', '25.5', '25.6', '25.7', '25.9'],
 '26': ['26.1', '26.2', '26.3', '26.4', '26.5', '26.6', '26.7', '26.8'],
 '27': ['27.1', '27.2', '27.3', '27.4', '27.5', '27.9'],
 '28': ['28.1', '28.2', '28.3', '28.4', '28.9'],
 '29': ['29.1', '29.2', '29.3'],
 '30': ['30.1', '30.2', '30.3', '30.4', '30.9'],
 '31': ['03.11', '03.12', '31.0'],
 '32': ['03.21', '03.22', '32.1', '32.2', '32.3', '32.4', '32.5', '32.9'],
 '33': ['33.1', '33.2'],
 '35': ['35.1', '35.2', '35.3'],
 '36': ['36.0'],
 '37': ['37.0'],
 '38': ['38.1', '38.2', '38.3'],
 '39': ['39.0'],
 '41': ['41.1', '41.2'],
 '42': ['42.1', '42.2', '42.9'],
 '43': ['43.1', '43.2', '43.3', '43.9'],
 '45': ['45.1', '45.2', '45.3', '45.4'],
 '46': ['46.1', '46.2', '46.3', '46.4', '46.5', '46.6', '46.7', '46.9'],
 '47': ['47.1',
  '47.2',
  '47.3',
  '47.4',
  '47.5',
  '47.6',
  '47.7',
  '47.8',
  '47.9'],
 '49': ['49.1', '49.2', '49.3', '49.4', '49.5'],
 '50': ['50.1', '50.2', '50.3', '50.4'],
 '51': ['05.10', '51.1', '51.2'],
 '52': ['05.20', '52.1', '52.2'],
 '53': ['53.1', '53.2'],
 '55': ['55.1', '55.2', '55.3', '55.9'],
 '56': ['56.1', '56.2', '56.3'],
 '58': ['58.1', '58.2'],
 '59': ['59.1', '59.2'],
 '60': ['60.1', '60.2'],
 '61': ['06.10', '61.1', '61.2', '61.3', '61.9'],
 '62': ['06.20', '62.0'],
 '63': ['63.1', '63.9'],
 '64': ['64.1', '64.2', '64.3', '64.9'],
 '65': ['65.1', '65.2', '65.3'],
 '66': ['66.1', '66.2', '66.3'],
 '68': ['68.1', '68.2', '68.3'],
 '69': ['69.1', '69.2'],
 '70': ['70.1', '70.2'],
 '71': ['07.10', '71.1', '71.2'],
 '72': ['07.21', '07.29', '72.1', '72.2'],
 '73': ['73.1', '73.2'],
 '74': ['74.1', '74.2', '74.3', '74.9'],
 '75': ['75.0'],
 '77': ['77.1', '77.2', '77.3', '77.4'],
 '78': ['78.1', '78.2', '78.3'],
 '79': ['79.1', '79.9'],
 '80': ['80.1', '80.2', '80.3'],
 '81': ['08.11', '08.12', '81.1', '81.2', '81.3'],
 '82': ['82.1', '82.2', '82.3', '82.9'],
 '84': ['84.1', '84.2', '84.3'],
 '85': ['85.1', '85.2', '85.3', '85.4', '85.5', '85.6'],
 '86': ['86.1', '86.2', '86.9'],
 '87': ['87.1', '87.2', '87.3', '87.9'],
 '88': ['88.1', '88.9'],
 '90': ['90.0'],
 '91': ['09.10', '91.0'],
 '92': ['92.0'],
 '93': ['93.1', '93.2'],
 '94': ['94.1', '94.2', '94.9'],
 '95': ['95.1', '95.2'],
 '96': ['96.0'],
 '97': ['97.0'],
 '98': ['98.1', '98.2'],
 '99': ['09.90', '99.0']}

In [ ]:
def get_subtree(code)