### Create Training data for binary classification: description of business sector - True False

In [1]:
import pandas as pd
import glob
import os
import ast
import json

import numpy as np
import pandas as pd
import os
import sys
import glob
import tqdm
import re
import random
from typing import List

sys.path.append("../../")
from sentence_splitter import split_text_into_sentences
#from BERT_classifier.Classify_report_with_BERT import classification_report_BERT
#from transformers import AutoModelForSequenceClassification, AutoTokenizer

#### Load Positives

In [2]:
positives_json_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/JSONs"

In [3]:
df_overview = pd.read_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/stoxx_600_overview.csv", sep=";")
df_positives = df_overview[df_overview["description_page"].notna()]
df_positives

,Unnamed: 0,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
3,107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
6,94,ABB Ltd.,ABBN-CH,ABBN-CH,28073.948473,29665.651960,30586.3762461154,27.11,C,ABB Ltd.2.pdf,18
9,135,Accelleron Industries AG,ACLN-CH,ACLN-CH,742.680345,846.217532,NaN,28.11,C,Accelleron Industries AG1.pdf,7
10,296,Acciona SA,ANA-ES,ANA-ES,11195.000000,17021.000000,19190,41.20,F,Acciona SA2.pdf,7
11,365,Accor SA,AC-FR,AC-FR,4224.000000,5056.000000,5606,55.10,I,Accor SA1.pdf,5
...,...,...,...,...,...,...,...,...,...,...,...
394,69,Orkla ASA,ORK-NO,ORK-NO,5774.960695,5932.590483,6073.67720031738,10.89,C,Orkla ASA1.pdf,11
466,598,Scout24 SE,G24-DE,G24-DE,447.539000,509.114000,s,96.09,S,Scout24 SE3.pdf,41
472,286,Severn Trent Plc,SVT-GB,SVT-GB,2505.264229,2709.430915,NaN,36.00,E,Severn Trent Plc1.pdf,8
479,133,Siemens Energy AG,ENR-DE,ENR-DE,29005.000000,31119.000000,34465,27.33,C,Siemens Energy AG1.pdf,5
482,30,Signify NV,LIGHT-NL,LIGHT-NL,7514.000000,6704.000000,6143,27.40,C,Signify NV3.pdf,6

In [4]:
for i, row in df_positives.iterrows(): 
    path = row["Report"].replace(".pdf", ".json")
    with open(os.path.join(positives_json_path, path), "r") as f: 
        report_json = json.load(f)
    
    description_pages = ast.literal_eval(row["description_page"])
    description_pages = [description_pages] if isinstance(description_pages, int) else description_pages

    description_text = ""
    for description_page in description_pages:

        description_text += list(filter(lambda x: x["page"] == description_page + 1, report_json["pages"]))[0]["markdown"]

    print(row["Report"])
    print(description_text)
    print("-----" * 5 + "\n"*6)

    df_positives.loc[i, "Description"] = description_text

AAK AB1.pdf
## we do is about Making Better Happen ™ Everything

AAK specializes in plant-based oils and fats, the value-adding ingredients in many products people love to consume. We make these products better tasting, healthier, and more sustainable. In addition, we enhance their sensory experience - by giving the silkier mouthfeel in premium chocolate, the juicier texture in a plant-based burger, and a puffier appearance in a lower-fat pastry.

We can also optimize our customers' production and processes by substituting existing ingredients with plantbased equivalents that improve efficiency and enhance the performance and sustainability of the end product. AAK's value-adding solutions enable our customers to Making Better Happen ™ .

At the heart of AAK's offer is customer co-development, combining our desire to understand what Making Better Happen ™  means for each customer with the unique flexibility of our production assets and deep knowledge of products and industries, including Chocolate &amp; Confectionery, Bakery, Dairy, Plant-based Foods, Special Nutrition, Foodservice, and Personal Care. Our 4,000 employees support our close collaboration with customers through 25 regional sales offices, 16 dedicated Customer Innovation Centers, and with the support of more than 20 production facilities.

Listed on Nasdaq Stockholm and headquartered in Malmö, Sweden, AAK has been Making Better Happen ™ for 150 years.
-------------------------






ABB Ltd.2.pdf
-

## Who we are

ABB has a history of innovation excellence stretching back more than 130 years with 70+ years of manufacturing in India. Today, we are a leading global technology company that enables a more sustainable and resource-efficient future with our technology leadership in electrification and automation.

Our strong heritage as a technology pioneer has led to long-lasting relationships with many of our customers and given us a deep understanding of market needs and the ability to anticipate and drive trends.

Our solutions connect engineering know-how and software to optimize how things are manufactured, moved, powered and operated. Building on our heritage of excellence, ABB's ~105,000 employees are committed to driving innovations that accelerate industrial transformation.

## Our Electrification business area

provides leading electrical distribution and management technologies, solutions and services to electrify the world in a safe, smart and sustainable way. The portfolio includes mediumand low-  voltage electrical components, switchgear, digital devices, enclosures, breakers, power conversion products and charging solutions for electric vehicles, among others. With our products, solutions and services, we collaborate with customers to improve power delivery and security, enhance energy management, efficiency and operational reliability, as we seek to achieve a lowcarbon society for the benefit of society and the planet.

Our Motion business area keeps the world turning - while saving energy every day. We innovate and push the boundaries of technology to enable the low-carbon future for customers, industries and societies. With our digitally enabled drives, motors and services our customers and   partners achieve better performance, safety and reliability. We offer a combination of domain expertise and technology to deliver the optimum drive and motor solution for a wide range of applications in all   industrial segments.

## Our Process Automation business area

is the leading supplier of integrated automation, electrical and digital solutions for the process, hybrid and maritime industries. It enables customers to operate some of the largest and most complex industrial infrastructure essential to modern life and run them more safely, intelligently and sustainably. The portfolio includes ABB's market-leading distributed control system, industrial software, advanced sensing, as well as industry-specific anchor products.

## Our Robotics &amp; Discrete Automation

business area is the only business that offers a comprehensive and integrated portfolio covering robots, autonomous mobile robots and machine automation solutions, designed and orchestrated by our value-  creating software. The business area helps companies of all sizes and sectors - from auto  motive to electronics and   logistics - become more resilient, flexible and efficient.
-------------------------






Accelleron Industries AG1.pdf
## Accelleron at a glance

Accelleron's technology gives engines an extra boost in performance with the main purpose of improving their fuel efficiency and thus reducing their environmental impact by generating fewer emissions. The Company designs, manufactures, sells and services highly customized turbochargers for heavy-duty applications.

<!-- image -->

Accelleron reports its business in two segments: Medium &amp; Low Speed and High Speed. They both cover product business as well as the integrated service business. From an operating perspective, the business is organized in four operating divisions: two product divisions, one service division and one digital customer solutions division.

As a focused specialist with a comprehensive product and service range, Accelleron produces heavy-duty turbochargers varying from 100kg to 10 metric tons, from 500 kW to 30,000 kW. All main markets from Marine and Energy to

Off-Highway Vehicles are exposed to the megatrends of decarbonization and digitalization, both of which provide vast opportunities.

With its products, Accelleron is the undisputed leader in turbocharging mission-critical applications. The Company's operations are based on a foundation of almost a century of making significant and continuous investments in technology, partnerships with original equipment manufacturers (OEMs) and end-users and an unrivalled global service network with a unique service culture that will never let customers down.

<!-- image -->
-------------------------






Acciona SA2.pdf
## 2. BUSINESS MODEL: BUSINESS AS UNUSUAL

ACCIONA's business model is reflected in  every  action  and  project  the  company undertakes. Applying the Business as Unusual approach to infrastructure development,  it  responds  to  the  challenges  facing  our  planet  with  a  long-term vision, always seeking a positive impact on both people and the planet.

<!-- image -->

<!-- image -->

## Energy

- -Over 300 TWh produced
- -EBITDA €1,653 billion (+52% vs. 2021)
- -13.2 million tCO 2 avoided through renewable generation
- -23,910 GWh of renewable electricity generated

<!-- image -->

## Infraestructures

- -Total portfolio €22.02 billion
- -EBITDA €369 million (+14,2% vs. 2021)
- -1,149 Hm³ of treated water
- -Management of 85 water treatment plants
- -6,000 km of roads built in the last ten years
- -600 bridges built

## PERFORMANCE

<!-- image -->

## Real Estate

- -Portfolio of 617 units (+39,2% vs. 2021)
- -Total assests valued at €1,541 billion (+13,2% vs. 2021)
- -10 millionde m² of residential, commercial industrial and office buildings

<!-- image -->

## Urban Mobility

- -+12,000 Silence vehicles sold (43% vs. 2021)
- -+12,400 scooters shared

<!-- image -->

## Bestinver

- -€5,472 billion of assets managed

## IMPACT

Shareholders

- Skateholders

1

3

A new sector

<!-- image -->

4

The world in constant transformation

5

ACCIONA Solutions in 2022

<!-- image -->

6

Governance

7

About this report

<!-- image -->

8

Annex: Cash fiows social 2022

Index

Letter from the Chairman

2

## Business model: Business as unusual
-------------------------






Accor SA1.pdf
## Message from Sébastien Bazin, Chairman and Chief Executive Officer

2022 was the year optimism returned for the travel industry, and Accor thrived. Leisure and domestic travel are back stronger than ever, international travel is gathering momentum, and Accor's own activity was very strong, outpacing 2019 levels. This is a tribute to the fundamental strengths of the Group, to our solid partnership with our owners and partners, and above all, a tribute to our teams' incredible spirit and tenacity, which drive the Accor vision.

Our brand portfolio remains unmatched and we pursued our global expansion in 2022, signing significant development agreements in China, unveiling the Orient Express train and opening 300 new hotels. We are continuously evolving to best accelerate our growth and support our owners and network, and our decision to organize the Group into two dedicated divisions reinforces our focus and positions us to fully reap the benefits of our expertise, brands, and market leadership.

The future of hospitality goes far beyond the hotel room, it's also about unlocking inspired experiences and capturing ever-changing guest needs, and we continued to create unique moments and diversify our offerings in 2022. We enriched our F&amp;B concepts, participated in major events such as the 2022 World Cup with The Living Adventure, reopened the famous Lido in Paris, strengthened our powerful loyalty program ALL and booking platform, and made exciting plans for the Olympic and Paralympic Games Paris 2024. Our augmented hospitality vision naturally extends to our owners and partners' experiences, and we continued investing in our fully holistic ecosystem to deliver and support their needs.

The future of hospitality must also be responsible, respectful and with sustainability at its heart. Accor is committed to building a hospitality model where we contribute more than we take. In 2022, we delivered great achievements in our sustainable journey, including eliminating single-use plastic in the guest experience in more than 80% of our hotels, and are working hand in hand with all stakeholders to achieve meaningful change. It's a question of mindset, vision, and determination. I'm convinced we share these.

Also more than ever critical to hospitality is our people. We are continuing to focus on what matters most to me, taking care of and empowering our 290,000+ Talents, and we are deeply committed to recruitment, development and training. To care for one another is the very essence of hospitality, and at Accor we embrace this purpose wholeheartedly.

## We are poised to boldly move forward and further strengthen our leadership as the most attractive and innovative hospitality Group.

I am proud of Accor's achievements and saluting them would not be complete without a tribute to Accor co-founder Gérard Pélisson. His recent passing filled us with great sadness - Gérard was a true entrepreneur, reinventing hospitality and making a global impact that continues to live on and be a source of inspiration.

Looking ahead, I am confident that, together, we can go even further in 2023 and build on these tailwinds and on the legacy of Accor's founders. We are poised to boldly move forward to further strengthen our leadership as the most attractive and innovative hospitality Group. We have the people, we have the brands, we have the ambition and the focus. Now is the time to do what we do best, seize the opportunity and build an even stronger future ahead.
-------------------------






Ackermans & van Haaren NV1.pdf
## Ackermans &amp; van Haaren

-  is an independent, diversified group established in 1876,
-  listed on Euronext Brussels since 1984 (BEL20 and BEL ESG) and with solid family ties,
-  led by an experienced, multidisciplinary team,
-  using its own resources to invest,
-  in a balanced combination of a limited number of strategic longterm participations and a diversified portfolio of growth capital investments.

## Long-term perspective

-  We make clear agreements with our participations regarding strategic, operational and financial goals;
-  guided by our long-term strategy, we are prepared to help finance strategic projects of our participations through capital increases;
-  our participations remain responsible for their own financial position;
-  we strive for annual recurring growth of the results of each participation and of the group as a whole.

## Growth

-  We are a group of entrepreneurs with the ambition to build leading companies through internationalisation, innovation and diversification in the long term;
-  we  create  long-term  shareholder  value  thanks  to  a  recurring  increase  of  the  consolidated  shareholders'  equity,  supported  by  a steady long-term dividend growth;
-  we focus on recurring growth of the activities, long-term growth of the operating cash flow and shareholders' equity of the participations, rather than on absolute profitability targets or short-term dividend maximisation.

## Active ownership

-  We are proud of a successful track record of partnerships with families, co-shareholders and management teams;
-  we invest in both majority and minority interests on the basis of balanced shareholder agreements;
-  our experienced investment managers are actively involved in the governing bodies of the participations, assisted where necessary by external consultants and/or independent directors;
-  we are a networked organisation, based on a diversity of personalities and backgrounds and on a permanent exchange of best practices between the group companies;
-  we are in constant dialogue with the management teams of the participations and are involved in:
-  selecting the senior management,
-  defining the long-term strategy,
-  actively supporting strategic projects (M&amp;A, internationalisation, innovation and operational improvements).

## Sustainable

-  We pay particular attention to sustainable development and growth of the activities of our participations, with respect for people, environment and society;
-  we have developed an ESG policy based on UN Sustainable Development Goals and UN PRI guidelines, and we apply this policy within the group and to our own investment decisions;
-  our investment philosophy is based on transparent reporting and communication, clear agreements in terms of corporate governance and business ethics, and strict financial discipline and healthy balance sheets;
-  we want to help build a more sustainable world by investing in line with  societal  trends  such  as  climate  change,  reduction  of  greenhouse gases (e.g. through renewable energy projects), sustainable food chain, population growth and ageing and digitalisation.
-------------------------






Adecco Group AG1.pdf
## Our business at a glance

## OUR GLOBAL FOOTPRINT

<!-- image -->

## OUR SERVICE LINES

## PP  Permanent Placement

## Approximately

39,000 FTE employees globally /pluslining 30,000

FTE Akkodis consultants

## Approximately

## 100,000

clients

Approximately 2 million

associates on assignment  every day/commalining including in our  joint ventures

## FP  Flexible Placement

<!-- image -->

<!-- image -->

We place associates with organisations  on a temporary basis/commalining providing flexibility  to employers and new opportunities to  candidates/periodlining We manage the entire  recruitment process from candidate search  and screening/commalining through onboarding and  training/commalining to payroll and administration/periodlining  Associates are employed by the Group  while on assignments/commalining which often run  consecutively to provide continuous  employment/periodlining In some countries/commalining associates  are employed by the Adecco Group on a  permanent basis and seconded to clients/periodlining

We help employers to recruit talent for  permanent roles/commalining securing the skills needed  for an organisation's ongoing success/periodlining  We source candidates/commalining screen CVs/commalining conduct  interviews and assessments/commalining and advise  hiring managers/periodlining We have access to a wide  range of talent/commalining including hard-to-reach  professionals who are not actively looking  for a new job/periodlining

## OC Outsourcing/commalining Consulting &amp; Other Services

## Contribution to  Group revenues

Europe/commalining Middle East  &amp; Africa 67% Americas 21% Asia Pacific 12%

## CT Career Transition

<!-- image -->

We support organisations and their  employees through changes that require  individuals to transition out of their existing  roles/periodlining Through our expert coaching and  training/commalining we help individuals find new  opportunities both within and outside their  existing company/commalining ensuring positive  outcomes for all/periodlining Our LHH Career Transition  business is the global leader in its market/periodlining

## TR  Training/commalining Up-skilling &amp; Re-skilling

<!-- image -->

We also offer a full spectrum of complementary HR solutions/commalining  including/colonlining Outsourcing - staffing and managing the entirety of  a labour-intensive activity/commalining such as warehouse logistics or IT support/semicolonlining  Consulting - providing technical experts for project-related work/semicolonlining  Managed Service Programmes /parenleftliningMSPs/parenrightlining - managing all parts of the  flexible workforce at organisations using a large number of contingent  workers/semicolonlining and Recruitment Process Outsourcing /parenleftliningRPO/parenrightlining - handling  the entire hiring process for employers recruiting large numbers  of permanent employees/periodlining

## Gross profit  /parenleftlining/percentlining/parenrightlining

<!-- image -->

We offer training/commalining up-skilling and re-skilling both as standalone services  and in combination with other solutions/commalining such as placements or as  part of a broader workforce transformation offering/periodlining Adecco is  a leading provider of work-based training/periodlining Our General Assembly  brand is a leader in up-skilling and re-skilling in high-demand digital  skills/commalining while our Akkodis Tech Academy offers candidates the  opportunity to upskill in technology and digital engineering-related  fields to increase their employability and to create a supply of  in-demand candidates for our clients/periodlining

<!-- image -->
-------------------------






Admiral Group plc1.pdf
## Our Business Model What we do

## Insurance underwriting

<!-- image -->

<!-- image -->

Admiral Group's primary business is to sell car, van, home, travel, and pet insurance in the UK, Europe (Spain, France, Italy), and the US. The majority of our customers buy our products through the price comparison channel, with a smaller proportion of customers buying directly from us, as well as the broker and agency channels. In addition to our core insurance products, we generate other revenue from the sale of ancillary add-ons and from fees generated over the life cycle of a policy.

Read more about our Co-insurance and reinsurance on page 66

Read more about our Investing on page 65

The Group's core market is the UK, where we estimate we have 17% share of the private car insurance market and a 7% share of the private home insurance market 7 . Outside of the UK, we leverage the knowledge, skills, and resources from our established UK business to promote expansion overseas and grow both our international businesses and new ventures outside of insurance underwriting.

<!-- image -->

## Risk sharing

A key feature of our business model and success is the use of extensive reinsurance and co-insurance partnerships. These are proportional risk-sharing agreements, where insurers outside of the Group underwrite the majority of the risk generated, either through co-insurance or quota share reinsurance contracts. These arrangements include profit commission terms which allow Admiral to retain a significant portion of the profit generated.

## Investing premiums


/var/folders/fp/yhl61lbj3m73x3_17tsp1vrr0000gn/T/ipykernel_22847/2710329527.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_positives.loc[i, "Description"] = description_text

In [5]:
def get_tables(lines: list): 
    tables = []
    current_table = []

    for line in lines:
        if line.strip().startswith("|"):  # line belongs to a table
            current_table.append(line.strip())
        else:
            if current_table:  # table ended
                tables.append("\n".join(current_table))
                current_table = []

    # catch last table if file ends without empty lines
    if current_table:
        tables.append("\n".join(current_table))

    return tables

def preprocess_report(text: str) -> List[str]:

    # with open(pdf_path, "r") as f: 
    #     text = f.read()

    sentence_length = 1
    
    lines = text.split("\n")

    tables = get_tables(lines)

    # drop if condidtion is True
    conditions = [
        # filter images
        #lambda line: line == '<!-- image -->',
        
        #filter tables 
        #lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False, 

        # filter headers
        lambda line: line.strip()[0] == "#" if len(line) > 0 else True,

        # filter sentences
        #lambda line: "." not in line,
        
        # more than 50% is numbers
        #lambda line: sum(ch.isalpha() for ch in line) / len(line) < 0.5,

        # minimum 3 words 
        #lambda line: len(re.sub(r"[^a-zA-ZäöüÄÖÜß\s]", '', line).strip().split(" ")) < 3,

        # Minimum 2 Sentences
        #lambda line: sum([0 if len(sentence.split(" ")) < 3 else 1 for sentence in split_text_into_sentences(line, "en")]) < 2

    ]
    accepted_lines = [line for line in lines if not any(condition(line) for condition in conditions)]
    accepted_lines += tables

    chunks = []

    for line in accepted_lines: 
        sentences = split_text_into_sentences(line, language='en')
        sentences = [sentence.strip() for sentence in sentences]
        sentences = [sentence for sentence in sentences if sentence != ""]
        new_chunks = [(" ".join(sentences[i:i+sentence_length])).strip() for i in range(0, len(sentences), 3)]

        chunks += new_chunks
    
    if len(chunks) <= 1: 
        return chunks

    # if there is only one sentence in the last chunk, balance the two last chunks
    if len(split_text_into_sentences(chunks[-1], language = "en")) == 1: 
        last_two_chunks = chunks[-2] + " " + chunks[-1]
        chunks[-2] = last_two_chunks[0:(len(last_two_chunks) + 1) // 2]
        chunks[-1] = last_two_chunks[(len(last_two_chunks) + 1) // 2: (len(last_two_chunks)) - (len(last_two_chunks) + 1) // 2]

    chunks = [re.sub(r'\b\d+\.\d+\b', '', chunk) for chunk in chunks]
    chunks = [re.sub(r"[^a-zA-ZäöüÄÖÜß.\s]", '', chunk) for chunk in chunks]
    chunks = [re.sub(r"\s+", " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'\.{2,}', " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'^\d+\.\s*', " ", chunk) for chunk in chunks]
    chunks = [chunk.lower() for chunk in chunks]
    chunks = [chunk.strip() for chunk in chunks]

    return chunks

In [6]:
df_positives.loc[:,"lenght_desc"] = df_positives["Description"].apply(len)
df_positives

/var/folders/fp/yhl61lbj3m73x3_17tsp1vrr0000gn/T/ipykernel_22847/3719149439.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_positives.loc[:,"lenght_desc"] = df_positives["Description"].apply(len)

,Unnamed: 0,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page,Description,lenght_desc
3,107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3,## we do is about Making Better Happen ™ Every...,1424
6,94,ABB Ltd.,ABBN-CH,ABBN-CH,28073.948473,29665.651960,30586.3762461154,27.11,C,ABB Ltd.2.pdf,18,-\n\n## Who we are\n\nABB has a history of inn...,2907
9,135,Accelleron Industries AG,ACLN-CH,ACLN-CH,742.680345,846.217532,NaN,28.11,C,Accelleron Industries AG1.pdf,7,## Accelleron at a glance\n\nAccelleron's tech...,1491
10,296,Acciona SA,ANA-ES,ANA-ES,11195.000000,17021.000000,19190,41.20,F,Acciona SA2.pdf,7,## 2. BUSINESS MODEL: BUSINESS AS UNUSUAL\n\nA...,1569
11,365,Accor SA,AC-FR,AC-FR,4224.000000,5056.000000,5606,55.10,I,Accor SA1.pdf,5,"## Message from Sébastien Bazin, Chairman and ...",3503
...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,69,Orkla ASA,ORK-NO,ORK-NO,5774.960695,5932.590483,6073.67720031738,10.89,C,Orkla ASA1.pdf,11,"## Orkla's business areas in 2022\n\nIn 2022, ...",753
466,598,Scout24 SE,G24-DE,G24-DE,447.539000,509.114000,s,96.09,S,Scout24 SE3.pdf,41,≡\n\n## Grundlagen des Konzerns\n\n## Geschäft...,3264
472,286,Severn Trent Plc,SVT-GB,SVT-GB,2505.264229,2709.430915,NaN,36.00,E,Severn Trent Plc1.pdf,8,## OUR BUSINESS MODEL UNDERSTANDING OUR WORLD\...,2100
479,133,Siemens Energy AG,ENR-DE,ENR-DE,29005.000000,31119.000000,34465,27.33,C,Siemens Energy AG1.pdf,5,## Our business areas\n\n## Digital Industries...,4527
482,30,Signify NV,LIGHT-NL,LIGHT-NL,7514.000000,6704.000000,6143,27.40,C,Signify NV3.pdf,6,## Creating Value\n\n## Our strategic focus\n\...,2289

In [7]:
paragraphs = []

for i, row in df_positives.iterrows(): 
    paragraphs.extend(preprocess_report(row["Description"]))

In [8]:
paragraphs = [p for p in paragraphs if p != ""]
paragraphs = [p for p in paragraphs if len(p) > 30]
len(paragraphs)

759

In [9]:
df_paragraphs_positive = pd.DataFrame(paragraphs)
df_paragraphs_positive.to_csv("/Users/hendrikweichel/Desktop/positive_data.csv")

In [17]:
positive_paragraphs_selected = pd.read_csv("/Users/hendrikweichel/Desktop/positive_data_selected.csv", sep=";", index_col=0)
positive_paragraphs_selected = positive_paragraphs_selected.dropna()

#### Load Negatives

In [16]:
negative_paragraphs = []

for i, row in df_positives.iterrows(): 
    path = row["Report"].replace(".pdf", ".json")
    with open(os.path.join(positives_json_path, path), "r") as f: 
        report_json = json.load(f)
    description_pages = ast.literal_eval(row["description_page"])
    description_pages = [description_pages] if isinstance(description_pages, int) else description_pages

    description_text = ""
    for description_page in description_pages:

        description_text += list(filter(lambda x: x["page"] != description_page + 1, report_json["pages"]))[np.random.randint(len(report_json["pages"])-1)]["markdown"]

    print(row["Report"])
    print(description_text)
    print("-----" * 5 + "\n"*6)

    #df_positives.loc[i, "Description"] = description_text

    negative_paragraphs.extend(preprocess_report(description_text))

AAK AB1.pdf
## Consolidated Changes in Shareholders' Equity

|                                         | Attributable to the Parent's shareholders   | Attributable to the Parent's shareholders   | Attributable to the Parent's shareholders   | Non-controlling   |              |
|-----------------------------------------|---------------------------------------------|---------------------------------------------|---------------------------------------------|-------------------|--------------|
| SEK million                             | Share capital                               | Reserves                                    | Retained profit                             | interests         | Total equity |
| Opening balance as at January 1, 2021   | 426                                         | -1,456                                      | 10,729                                      | 39                | 9,738        |
| Profit for the year                     | -                                           | -                                           | 1,437                                       | 10                | 1,447        |
| Other comprehensive income              | -                                           | 687                                         | 12                                          | -1                | 698          |
| Comprehensive income                    | -                                           | 687                                         | 1,449                                       | 9                 | 2,145        |
| Transactions with shareholders          |                                             |                                             |                                             |                   |              |
| New issue of shares                     | 5                                           | -                                           | 429                                         | -                 | 434          |
| Change in non-controlling interests     | -                                           | -                                           | 104                                         | 0                 | 104          |
| Dividend                                | -                                           | -                                           | -590                                        | -                 | -590         |
| Total transactions with shareholders    | 5                                           | -                                           | -57                                         | 0                 | -52          |
| Closing balance as at December 31, 2021 | 431                                         | -769                                        | 12,121                                      | 48                | 11,831       |

|                                                | Attributable to the Parent's shareholders   | Attributable to the Parent's shareholders   | Attributable to the Parent's shareholders   | Non-controlling   |              |
|------------------------------------------------|---------------------------------------------|---------------------------------------------|---------------------------------------------|-------------------|--------------|
| SEK million                                    | Share capital                               | Reserves                                    | Retained profit                             | interests         | Total equity |
| Opening balance as at January 1, 2022          | 431                                         | -769                                        | 12,121                                      | 48                | 11,831       |
| Adjustment Opening balance IAS 29              | -                                           | -                                           | 41                                          | -                 | 41           |
| Adjusted Opening balance as at January 1, 2022 | 431                                         | -769                                        | 12,162                                      | 48                | 11,872       |
| Profit for the year                            | -                                           | -                                           | 1,770                                       | 10                | 1,780        |
| Other comprehensive income                     | -                                           | 1,470                                       | 149                                         | 6                 | 1,625        |
| Comprehensive income                           | -                                           | 1,470                                       | 1,919                                       | 16                | 3,405        |
| Transactions with shareholders                 |                                             |                                             |                                             |                   |              |
| New issue of shares                            | 2                                           | -                                           | 145                                         | -                 | 147          |
| Subscription warrants                          | -                                           | -                                           | 80                                          | -                 | 80           |
| Exit Russia                                    | -                                           | -                                           | 237                                         | -17               | 220          |
| Liquidation                                    | -                                           | -                                           | 5                                           | -                 | 5            |
| Dividend                                       | -                                           | -                                           | -646                                        | -                 | -646         |
| Total transactions with shareholders           | 2                                           | -                                           | -179                                        | -17               | -194         |
| Closing balance as at December 31, 2022        | 433                                         | 701                                         | 13,902                                      | 47                | 15,083       |

For further information, see Note 20.
-------------------------






ABB Ltd.2.pdf
<!-- image -->
-------------------------






Accelleron Industries AG1.pdf
Financial reporting

Accelleron Consolidated and Combined Statements of Income

Segment Operational EBITA and the reconciliation to the Company's consolidated and combined results are as follows:

|                                                          | Years Ended December 31,   | Years Ended December 31,   |
|----------------------------------------------------------|----------------------------|----------------------------|
| (USD in thousands)                                       | 2022                       | 2021                       |
| Income from continuing operations before taxes           | 156,483                    | 184,202                    |
| Add back: Interest and other finance expense , net 1     | 555                        | 1,379                      |
| Income from operations                                   | 157,038                    | 185,581                    |
| Add back: One-off and other non-operational costs, net 2 | 34,770                     | 2,024                      |
| Operational EBITA 3 :                                    | 191,808                    | 187,605                    |
| Thereof High Speed                                       | 40,954                     | 49,620                     |
| Thereof Medium & Low Speed                               | 150,854                    | 137,985                    |

1 Interest and other finance income/(expense), net includes non-operational pension income in the amount of USD 6,224 thousands (2021: USD 279 thousands of expense) and other finance expenses in the amount of USD 6,779 thousands (2021: USD 1,100 thousands).

- 2 One-off and other non-operational costs, net includes operational pension gains in the amount of USD 1,129 thousands (2021: USD nil), foreign exchange gains in the amount of USD 67 thousands (2021: USD 1,223 thousands), restructuring and related activities in the amount of USD 1,037 thousands of income (2021: USD 3,247 thousands of expenses) and build-up costs following the spin-off from Former Parent in the amount of USD 37,003 thousands (2021: USD nil).

3 Operational EBITA represents income from operations excluding costs related to acquisition and divestment, one-time items in statements of income, non-operational integration costs, special non-operational projects, restructuring costs, amortization of acquired intangibles as a result of a business combination and temporary unrealized timing differences in the context of foreign exchange transactions (FX). Operational EBITA is the Company's measure to monitor segments' performance and also used by management to evaluate the profitability of the Company as a whole.

The following table presents disaggregated revenues information for 2022 and 2021.

|                                               | Years Ended December 31,   | Years Ended December 31,   |
|-----------------------------------------------|----------------------------|----------------------------|
| (USD in thousands)                            | 2022                       | 2021                       |
| Geographical markets:                         |                            |                            |
| Asia, Middle East & Africa                    | 316,539                    | 303,091                    |
| thereof Japan                                 | 58,462                     | 66,519                     |
| thereof China                                 | 86,902                     | 81,040                     |
| The Americas                                  | 176,634                    | 145,274                    |
| thereof United States of America              | 127,018                    | 98,196                     |
| Europe                                        | 287,365                    | 308,101                    |
| thereof Switzerland                           | 19,499                     | 17,265                     |
|                                               | 780,538                    | 756,466                    |
| Product Type                                  |                            |                            |
| High Speed Products and Services              | 213,826                    | 205,885                    |
| Medium & Low Speed Products and Services      | 566,712                    | 550,581                    |
|                                               | 780,538                    | 756,466                    |
| Third-party revenues                          | 780,538                    | 755,122                    |
| Revenues with related parties (Former Parent) | -                          | 1,344                      |
| Total revenues                                | 780,538                    | 756,466                    |

One of the Company's HS customers accounted for 13% and 12% of total revenues in 2022 and 2021, respectively. As of December 31, 2022 another customer of the Company's M&amp;LS segment accounted for 12% of total revenues. Such customer accounted for less than 10% of total revenues in 2021 and is therefore not separately disclosed.

## Note 5 Income taxes

In 2021, amounts presented in these consolidated and combined financial statements relate to income taxes determined on a separate return basis. Current income tax liabilities are assumed to be immediately settled when due in the same year. Therefore, current income taxes payable is only presented in the consolidated and combined financial statements where the tax liability is not settled within the same year when the taxes are due. The net effect of the settlement of these transactions is reflected in 'Net transfer to Former Parent' as a financing activity in the consolidated and combined statements of cash flows. In 2022, the closing current tax payable/ receivable reflects the positions payable to tax authorities on a separate return basis.

In both 2022 and 2021, the Company implemented legal reorganizations in several jurisdictions in order to legally separate the Turbocharging business from the legacy ABB corporate structure. Most of these legal reorganizations were implemented at fair market value which led in various jurisdictions to the crystallization of taxable capital gains for the transferor and the recognition of tax-deductible goodwill for the transferee. The current and deferred income tax consequences resulting from these transactions were recorded in the consolidated and combined statements of changes in equity as a change in Net Parent Investment.

Additionally, Accelleron derecognized all tax attributes (primarily tax loss carry-forwards) that were forfeited with the legal reorganizations or that no longer existed once the Turbocharging business was separated from the Former Parent. Within the tax neutral demergers executed in 2021 and 2022, the related tax losses are not transferred to the Company and hence, the respective deferred tax assets and the corresponding valuation allowances were released (see consolidated and combined statements of changes in shareholders' equity).

"Income tax expense" consisted of the following:

|                              | December 31,   | December 31,   |
|------------------------------|----------------|----------------|
| (USD in thousands)           | 2022           | 2021           |
| Current taxes                | (24,800)       | (40,119)       |
| Deferred taxes               | (1,891)        | 222            |
| Tax expenses from operations | (26,691)       | (39,897)       |

90
-------------------------






Acciona SA2.pdf
## ND CE

01

02

03

04

Letter from the Chairman

Business model:

Business as unusual

A new sector

The world in constant transformation

05

06

07

08

ACCIONA Solutions in 2022

Governance

About this report

Annex: Cash flows social 2022
-------------------------






Accor SA1.pdf
<!-- image -->

ALL-Accor Live Limitless launches 'ALL Mobilité' a new digital mobility service developed with Karhoo Thanks to this mobility service, members of the loyalty program can now reserve their taxi or private hire vehicle on the ALL app or the website All.com. The mobility service covers 490 European cities, as well as Dubai and New York, and addresses two main needs:

- Trips when traveling ,  to go to a station, airport or an Accor hotel. This is a particularly useful service when abroad, where guests are often unaware of how to reserve and pay for taxis or chauffeur-driven vehicles.
- Day-to-day travel ,  whether personal or professional, to go to a meeting or a restaurant.

The service allows users to compare, in real time, available taxi and private hire vehicle offers and to make their choice according to rate, waiting time, vehicle category (electric, traditional, etc.) and available extras. The mobility service is the result of a strategic and technological partnership between ALL and Mobilize, the Renault Group brand dedicated to new mobilities, via its start-up Karhoo.

## ALL-Accor Live Limitless sets out the next chapter

with Paris Saint Germain After three highly successful years as a major partner and official jersey sponsor of Paris Saint-Germain, Accor has decided to extend its commitment with the French football giant, albeit in a different capacity, for a further four years to promote its lifestyle loyalty program. In the new partnership, ALL-Accor Live Limitless will  now be visible on the sleeve of PSG's training jersey, while a major focus of the collaboration will be on using Paris Saint-Germain assets to en-gage with and offer unique experiences ALL-Accor Live Limitless members all over the World. The partnership was initially created in 2019 to launch ALL-Accor Live Limitless , the daily lifestyle companion that brings together and enhances all the brands, services and partnerships operating within the Accor ecosystem. It has been a great success in providing current and future members with unforgettable experiences  while  supporting  and  promoting awareness of what was a new brand. The sponsorship has enabled ALL to be established as a global brand.
-------------------------






Ackermans & van Haaren NV1.pdf
Note 6: Segment information - equity and liabilities 2022

| (€ 1,000)                                                    | Segment 1                        | Segment 2       | Segment 3                 | Segment 4          | Segment 5            |                               |            |
|--------------------------------------------------------------|----------------------------------|-----------------|---------------------------|--------------------|----------------------|-------------------------------|------------|
|                                                              | Marine Engineering & Contracting | Private Banking | Real Estate & Senior Care | Energy & Resources | AvH & Growth Capital | Eliminations between segments | Total 2022 |
| I. Total equity                                              | 2,275,511                        | 1,639,351       | 841,492                   | 342,495            | 903,607              |                               | 6,002,456  |
| Shareholders' equity - group share                           | 1,414,303                        | 1,497,979       | 482,890                   | 342,495            | 895,966              |                               | 4,633,633  |
| Issued capital                                               | 0                                | 0               | 0                         | 0                  | 113,907              |                               | 113,907    |
| Share capital                                                | 0                                | 0               | 0                         | 0                  | 2,295                |                               | 2,295      |
| Share premium                                                | 0                                | 0               | 0                         | 0                  | 111,612              |                               | 111,612    |
| Consolidated reserves                                        | 1,388,917                        | 1,533,242       | 479,175                   | 317,111            | 829,477              |                               | 4,547,922  |
| Revaluation reserves                                         | 25,386                           | -35,263         | 3,715                     | 25,383             | -6,821               |                               | 12,401     |
| Financial assets : bonds - Fair value through OCI (FVOCI)    | 0                                | -32,964         | 0                         | 0                  | 0                    |                               | -32,964    |
| Financial assets : shares - Fair value through OCI (FVOCI)   | 0                                | 129             | 0                         | 0                  | 0                    |                               | 129        |

In [12]:
negative_paragraphs = [p for p in negative_paragraphs if p != ""]
negative_paragraphs = [p for p in negative_paragraphs if len(p) > 60]
len(negative_paragraphs)

698

In [13]:
negative_paragraphs

['composition of business segments power grids discontinued robotics and discrete automation motion electrification process automation in crores total',
 'revenues results net profit assets liabilities in crores depreciation amortisation',
 'composition of business segments power grids discontinued robotics and discrete automation motion electrification process automation in crores total',
 'revenues results net profit assets liabilities in crores depreciation amortisation',
 'the amounts recognized in accumulated other comprehensive income aoci at december before taxes were',
 'the following amounts were recognized in the companys consolidated and combined balance sheet as at december and classified as noncurrent assets',
 'the following assumptions were used to determine the projected benefit obligation at december weighted average',
 'for the companys benefit plans the discount rate used at each measurement date is set based on a highquality corporate bond yield curve reflecting the timing and amount of the future expected benefit payments for each of the plans.',
 'the following assumptions were used to determine the net periodic benefit cost',
 'the expected longterm rate of return on plan assets is determined by weighting the expected future longterm return for each individual asset class by a plans target asset allocation.',
 'the swiss pension plan is funded by regular contributions from employees and the company.',
 'plan assets are invested in diversified portfolios that are managed by thirdparty asset managers in accordance with local statutory regulations pension plan rules the results of assetliability management studies and investment guidelines as approved by the board of trustees.',
 'the board of trustees investment goal is to maximize the longterm returns of plan assets within specified risk parameters while considering future liabilities and liquidity needs.',
 'plan assets are measured at fair value at the balance sheet date.',
 'the fair values of the companys pension plan assets by asset class at december are presented below.',
 'amounts relate to assets measured using the nav practical expedient which are not subject to leveling.',
 'the company applies accounting guidance related to the presentation of certain investments using the net asset value nav practical expedient.',
 'a benchmark in promoting strategic sustainability master plan',
 'and operating essential infrastructure main strengths priorities',
 'authenticity share the same values and work towards the same goal in each workplace perception as one of the companies that contributes most to sustainable',
 'sustainable transformative innovation develop an innovative differential regenerative value in the company development innovation projects based around a regenerative vector',
 'governance accionas board will continue to lead this drive with oversight to ensure the companys mission is met project information available to stakeholders access to information on suppliers esg performance',
 'transparency undergo constant scrutiny more information about our business structure',
 'acciona has the capacity to create a unique sustainable difference with a portfolio of solutions aligned with sustainable transformation.',
 'solutionbased approachs the value proposition will be based on integrated infrastructure designed to maximise its contribution to the sdgs',
 'sustainable difference in each project accionas sustainable difference will be evident in each project number of solutions integrated with at least business areas develop a model for measuring productivity and regeneration hours of volunteer work invested',
 'regenerative ecosystems develop an ecosystem of organisations capable of increasing our capability in terms of regenerative transformation regenerative initiatives in conjunction with partners customers and suppliers total regenerative investment mobilised',
 'impact financing maximise the capacity of sustainable financing to bolster the companys value and competitive regenerative advantages in our projects more information accionas role in development infrastructure',
 'a benchmark in promoting strategic sustainability master plan',
 'sustainable transformative innovation develop an innovative differential regenerative value in the company development innovation projects based around a regenerative vector',
 'lever meaning indicators sustainable difference in each project accionas sustainable difference will be evident in each project number o',
 "Accor's unique ecosystem of leading brands, value-added services &amp; solutions, and powerful loyalty program allows us to constantly reinvent unique &amp; personalized experiences and services for our clients in line with their evolving needs and new ways of living, traveling and working, from hotel stays to restaurants to working and meeting.",
 'delen private bank focuses on the management and planning of assets of primarily private clients.',
 'delen group did everything possible to adhere to its mission financial peace of mind for its clients in the midst of all this uncertainty.',
 'the assets under management of delen group consolidated reached a level of million euros at yearend million euros.',
 'the stock market turmoil caused a sharp decrease in the value of the underlying assets which was partially offset by the net inflow of capital.',
 'this suggests that in difficult circumstances a personalised service proactive and relevant communication and an integrated offering of asset management and planning are key assets.',
 'there was a similar resilience in the netherlands thanks to the commercial commitment and efforts of the strengthened team.',
 'moreover the weak pound against the euro further decreased the assets under management expressed in euros.',
 'the average assets under management at delen private bank held up in resulting in slightly higher gross revenues million euros than in million euros.',
 'the sharp rise in inflation did not leave delen group unaffected either.',
 'akkodis is a global digital engineering company and smart industry leader that enables clients to accelerate and advance in their digital transformation with consultingcommalining solutionscommalining talentcommalining and academy servicesperiodlining building on four decades of combined pioneering heritage and engineering track recordcommalining akkodis is a trusted partner to the worlds industriesperiodlining we cocreate and pioneer solutions that help to solve major challengescommalining from accelerating the clean energy transition and green mobilitycommalining to improving user and patient centricityperiodlining',
 'akkodis was formed in early twoliningzeroliningtwoliningtwolining when modiscommalining the adecco groups hightech services businesscommalining was combined with akkacommalining a leader in engineering rampd servicesperiodlining todaycommalining the company employs threeliningzeroliningcommaliningzeroliningzeroliningzerolining tech experts across threeliningzerolining countries and is one of the leading global service companies in the smart industryperiodlining smart industry is where engineeringcommalining itcommalining and digital converge into a connected worldperiodlining it is about driving real change and enabling the transformation of productscommalining servicescommalining processescommalining and business models for a smarter and more sustainable tomorrowperiodlining akkodis aspires to become one of the most admired tech services companies in the worldperiodlining',
 'akkodis has based its strategy on sevenliningxsevenliningxfourliningperiodlining the company has placed its focus on seven global industriescommalining where it contributes deep expertise from seven tech practices and provides a broad portfolio of premium services across four service linescommalining which are highly flexible and complementary to existing client capabilitiescolonlining',
 'onelining consulting colonlining akkodis consulting services are resourced with highly skilled professionals who are adept at supporting the designcommalining deliverycommalining and operation of innovative solutionsperiodlining herecommalining akkodis delivers consultancy servicescommalining project servicescommalining managed servicescommalining and smart industry transformation servicesperiodlining leveraging deep sector knowhow and tech expertisecommalining akkodis consultants complement an organisations existing capabilitiescommalining bringing additional scalecommalining capacitycommalining and speedcommalining where neededperiodlining akkodis consultants support the entire project management process from ideation and design to validation and implementationperiodlining',
 'twolining solutions colonlining akkodis contributes a broad range of valueadded solutions to address tech and engineering needs in the defined key strategic industriesperiodlining the akkodis solutions portfolio is comprised of project servicescommalining managed servicescommalining and akkodis intellectual propertytemplates solutionsperiodlining supporting both local needs and global scalabilitycommalining we can adapt the right delivery modes according to client needscolonlining in countrycommalining nearshorecommalining and offshoreperiodlining akkodis continuously invests in its research amp innovation labscommalining building competencies for nextgeneration advancements in technologyperiodlining',
 'threelining talent colonlining with its global network of more than five million prequalified candidatescommalining akkodis rapidly connects organisations with the right it and engineering talentcommalining at the right time and placeperiodlining akkodis enables clients to reduce hiring timelines and costs of tech talent acquisitionperiodlining furthermorecommalining',
 'akkodis provides recruitment process outsourcing services for tech specialists around the globecommalining which enable human resource utilisation to be maximisedperiodlining through a broad spectrum of managed servicescommalining clients can benefit from global coverage in niche it and engineering marketsperiodlining',
 'fourlining academy colonlining through its global academy networkcommalining akkodis is enabling clients to close the tech and digital skills gap through customised upskilling and reskilling programmesperiodlining todaycommalining akkodis has established ten academies across europecommalining north americacommalining and asia pacificperiodlining each yearcommalining the network helps thousands of people to develop and grow their digital and engineering skills and futureproof their careersperiodlining simultaneouslycommalining academies are enabling organisations to adaptcommalining transformcommalining and equip their workforce with the skills needed to overcome the complexity brought about by a constantly changing digital landscapeperiodlining',
 'the worlds major industries are embracing digitalisation to increase performance and stay ahead of the gameperiodlining the size of the market opportunity related to this trend is significantperiodlining the aerospace industry is just one exampleperiodlining a recent research report onelining in partnership with the aerospace industries association found that advancing the digital maturity of the aerospace value stream could unlock dollarliningtwoliningzerolining billion in annual ebitdaperiodlining capitalising on this trend and recognising the convergence of legacy and digital engineeringcommalining akkodis is well placed to apply its core expertise to leverage the market opportunity and secure its place as the global smart industry leader with its sevenliningxsevenliningxfourlining strategyperiodlining',
 'from an external perspectivecommalining talent scarcity combined with rising inflation present the risk of high attrition and the related challenge of growing the number of consultants required to deliver upon healthy levels of client demandperiodlining',
 'talent scarcity as a market issue was highlighted by gartnercommalining incperiodliningcommalining in survey findings released in twoliningzeroliningtwoliningoneliningcommalining identifying that it executives see the talent shortage as the most significant adoption barrier to sixliningfourliningpercentlining of emerging technologiescommalining compared with just fourliningpercentlining in twoliningzeroliningtwoliningzeroliningperiodlining',
 'to mitigate this riskcommalining one of the actions that akkodis has taken is to engage its own academy service line to help upskill and reskill its own employees who can be rapidly deployed to meet client demandperiodlining with five million prequalified candidates for engineering and digital rolescommalining akkodis has one of the largest tech talent recruiting networks worldwideperiodlining',
 'from an internal perspectivecommalining the challenge of balancing onshore and offshore delivery to achieve the most effective mix of skills and expertise at the appropriate time and price for our clients is a key focusperiodlining as part of its strategycommalining akkodis is in the process of building up a global delivery network to mitigate this riskperiodlining',
 'onelining httpscolonliningwwwperiodliningmckinseyperiodliningcomindustriesaerospaceanddefenseourinsightsdigitalthenexthorizonforglobalaerospaceanddefense',
 'deliver digital and engineering capabilities to enable the smart industry transformation',
 'market sizecolonlining eur bn market growthcolonlining pa revenuescolonlining eur .bn countriesco',
 'continuingoperations gross m recoverable fromcoand reinsurers m net m',
 'continuing operations gross m recoverable fromcoand reinsurers m net m',
 'acquisition of insurance contracts expense excludes million million of aggregator fees from other group companies',
 'the million million administration and marketing costs allocated to insurance contracts is principally made up of salary costs.',
 'refer to note for a reconciliation between insurance contract expenses and the reported expense ratio. task force on climaterelated financial disclosures tcfd continued',
 'climate related risk tcfd category prus primarily affected description short term years medium term years long term years',
 'transition frompetrol anddiesel vehicles toevs transition policy andlegal technology market reputation reserving risk inukand international insurance changing distribution of riskfromnewtechnologies e.g. will evs beslower andsafer or silent moredangerous andpronetobatteryfires',
 'transition frompetrol anddiesel vehicles toevs transition policy andlegal technology market reputation erosion of competitive advantage inukcar insurance amoveawayfrompetrolanddieselvehiclestoalternative fuel vehicles reducing competitive advantage frompricing expertise stressing supply chain including repairer network andincreasinglr newentrantstaking marketshare as petrol anddiesel vehicles are replacedbyevs evoemsofferingbundledproductsandservices changing customeracquisition channel',
 'secular reduction inprivate vehicleuse transition policy andlegal technology market reputation reserving riskinukand international insurance changing distribution of risk fromemergingtechnologies e.g. will agreater proportion of morevulnerable road users fromescooters etc. lead to morebiandcsiclaims',
 'secular reduction inprivate vehicleuse transition policy andlegal technology market reputation erosion of competitive advantage inukcar insurance amoveawayfromprivatevehiclestoactive andpublic transport or car sharing thus reducing the overall size of admirals primarymarket',
 'increased incidence andseverity ofweather events physical acute chronic reserving riskinukand international insurance changetoincidence extent location andclusteringofboth chronic high frequency andacutehigh impact weather andclimaterelated drivers of insurance claims potentially differing bygeographye.g. southeasternusversusuk versus europeandaffectingtheukhouseholdlobin particular duetomateriality',
 'increased incidence andseverity ofweather events physical acute chronic premium riskand catastrophe risk average annual losses fromweathereventswill likelybe higher under future scenarios with higher carbon emissions inparticularaffectingtheukhouseholdlobduetomateriality increasinguncertaintyabouttrendsinpastdataandthedegree ofconfidencethatcanbeplacedinprojections',
 'increased incidence andseverity ofweather events physical acute chronic reduced availability of coinsurance reinsurance increase in the cost andimportanceofreinsurance protection increased concentration risk putting pressure onreinsurance reinsurance structures impacted ifmoreevents hit reinsurance layers possible changes to terms andconditions',
 'increased incidence andseverity ofweather events physical acute chronic failure of geographic andor product expansion profitability andor viability of householdmotorornew productunderwritingmaybecompromised',
 'increased incidence andseverity ofweather events physical acute chronic operational risk increased risk of office closuresandordamage increased levels of health andsafety risk during specific weather events increased data risk or reduced availability of core systems depending onthelocation of information related infrastructure suppliers maybeexposedtosimilarrisks division of responsibilities',
 'compliancewiththecodeprinciples compliancewiththecodeprinciples',
 'principle f thechair leads its overall theyshould throughout of openness the board andis responsible for effectiveness in directing the company. demonstrate objectivejudgement theirtenureandpromoteaculture anddebate.',
 'principle g theboardshouldinclude anappropriate combination of executive andnonexecutive and in particular independent nonexecutive directors such that nooneindividual or small group of individuals dominates the boards decisionmaking.',
 'principle h nonexecutive directors should have sufficient time to meettheir responsibilities.',
 'principle i theboard supported bythecompanysecretary should ensure that it has the policies processes information time andresources it needsin order to function effectively andefficiently. informationflowstoandfromtheboardonpage boardevaluationonpagesto',
 'climate related risk tcfd category prus primarily affected description short term years medium term years long term years',
 'introductionofnewtypesofriskwhichhavenotbeen encounteredbeforee.g.petrolcarsdonothavebatteryfires reduction or elimination of someclaimstypes e.g. wrongfuel claims unanticipated claims inflation fromreplacing brown technology with greenoldbrowntechnologymaybecome moreexpensive to repair',
 'secular reduction inprivate vehicleuse transition policy andlegal technology market reputation erosion of competitive advantage inukcar insurance amoveawayfromprivatevehiclestoactive andpublic transport or car sharing thus reducing the overall size of admirals primarymarket',
 'increased incidence andseverity ofweather events physical acute chronic reduced availability of coinsurance reinsurance increase in the cost andimportanceofreinsurance protection increased concentration risk putting pressure onreinsurance reinsurance structures impacted ifmoreevents hit reinsurance layers possible changes to terms andconditions',
 'compliancewiththecodeprinciples compliancewiththecodeprinciples',
 'principle f thechair leads its overall theyshould throughout of openness the board andis responsible for effectiveness in directing the company. demonstrate objectivejudgement theirtenureandpromoteaculture anddebate.',
 'there should beaclear division of responsibilitiesbetweenthe leadership of the board andtheexecutive leadership of the companys business. board composition andsuccession planningon page codeexplanationforprovisiononpage boardevaluationonpagesto board roles andresponsibil',

In [14]:
df_negative_paragraphs = pd.DataFrame(negative_paragraphs).drop_duplicates()
df_negative_paragraphs.to_csv("/Users/hendrikweichel/Desktop/negative_data.csv")

In [15]:
len(df_negative_paragraphs)

647

In [18]:
df_negative_paragraphs["label"] = False
positive_paragraphs_selected["label"] = True

In [21]:
df_negative_paragraphs

                                                     0  label
0    composition of business segments power grids d...  False
1    revenues results net profit assets liabilities...  False
4    the amounts recognized in accumulated other co...  False
5    the following amounts were recognized in the c...  False
6    the following assumptions were used to determi...  False
..                                                 ...    ...
693  additional fees invoiced for statutory audit i...  False
694  siemens as presents its income statement based...  False
695  following is the comparative summary of our fi...  False
696  during the year under review the company sales...  False
697  the name of holding company is signify holding...  False

[647 rows x 2 columns]

In [26]:
df_negative_paragraphs.columns, positive_paragraphs_selected.columns

(Index([0, 'label'], dtype='object'), Index(['0', 'label'], dtype='object'))

In [29]:
df_negative_paragraphs = df_negative_paragraphs.rename(columns={0:"text"})
positive_paragraphs_selected = positive_paragraphs_selected.rename(columns={"0":"text"})

In [40]:
df_full = pd.concat((df_negative_paragraphs, positive_paragraphs_selected), axis=0)

In [41]:
df_full = df_full.reset_index(drop=True)
df_full

                                                   text  label
0     composition of business segments power grids d...  False
1     revenues results net profit assets liabilities...  False
2     the amounts recognized in accumulated other co...  False
3     the following amounts were recognized in the c...  False
4     the following assumptions were used to determi...  False
...                                                 ...    ...
1153  we are building a customerfocused organization...   True
1154  we are developing tiered offerings with multip...   True
1155  we are driving new sustainable growth areas to...   True
1156  we are creating a digital front and backend em...   True
1157  we are further investing in our people creatin...   True

[1158 rows x 2 columns]

In [43]:
df_full.to_csv("/Users/hendrikweichel/Desktop/full_data_comp_description.csv")

In [44]:
from sklearn.model_selection import train_test_split

# Split full_df into train (60%) and temp (40%)
train_df, temp_df = train_test_split(df_full, test_size=0.4, random_state=42)

# Split temp into test (20%) and validation (20%)
test_df, val_df = train_test_split(temp_df, test_size=0.5, random_state=42)

# Print the sizes of each split
print(f"Train size: {len(train_df)}, Test size: {len(test_df)}, Validation size: {len(val_df)}")

Train size: 694, Test size: 232, Validation size: 232

In [45]:
train_df.to_csv("/Users/hendrikweichel/Desktop" + "/train_data.csv", index=False)
val_df.to_csv("/Users/hendrikweichel/Desktop" + "/val_data.csv", index=False)
test_df.to_csv("/Users/hendrikweichel/Desktop" + "/test_data.csv", index=False)