In [5]:
from docling.datamodel.base_models import InputFormat
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling.datamodel.pipeline_options import PdfPipelineOptions, TableFormerMode
from docling.document_converter import DocumentConverter
import tqdm
import os
import glob
import re
import pandas as pd
from sentence_splitter import split_text_into_sentences

In [10]:
texts_path = "../../data/TEXT_stoxx600_docling"
filterd_texts_path = "../data/FILTERED_TEXT_stoxx600_docling"

In [13]:
texts = glob.glob(texts_path + "/*.txt")

In [24]:
for text_path in tqdm.tqdm(texts): 
    accepted_lines = lines
    not_accepted_lines = []

    with open(text_path, "r") as f: 
        text = f.read()
    lines = text.split("\n")

    is_image = lambda line: line == '<!-- image -->'
    is_table = lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False
    
    accepted_lines = [line for line in accepted_lines if not is_image(line) and not is_table(line)]
    not_accepted_lines = [line for line in accepted_lines if is_image(line) or is_table(line)]

    df = pd.DataFrame(accepted_lines, columns=["lines"])
    df = df.drop_duplicates()
    df["len"] = df["lines"].apply(len)
    df = df.sort_values("len")
    
    df.to_csv(os.path.join(filterd_texts_path, os.path.basename(text_path)[:-4]) + "_lines_len.csv")

100%|██████████| 42/42 [00:00<00:00, 102.09it/s]

In [25]:
filter_len = lambda line: len(line) > 110
accepted_lines = [line for line in accepted_lines if filter_len(line)]

In [ ]:
chunks = []

for line in accepted_lines: 
    sentences = split_text_into_sentences(line, language='en')
    sentences = [sentence.strip() for sentence in sentences]
    sentences = [sentence for sentence in sentences if sentence != ""]
    new_chunks = [(" ".join(sentences[i:i+3])).strip() for i in range(0, len(sentences), 3)]

    chunks += new_chunks 

[print(chunk) for chunk in chunks]

Euronext N.V. (the 'Company' or 'Euronext' and together with its subsidiaries, the 'Group') is a Dutch public company with limited liability (naamloze vennootschap), whose ordinary shares are admitted to listing and trading on regulated markets  in  the  Netherlands, France,  Belgium  and  Portugal.  The  applicable  regulations  with  respect  to public information and protection of investors, as well as the commitments made by the Company to securities and market authorities, are described in this Universal Registration Document (the 'Universal Registration Document').
["Euronext N.V. (the 'Company' or 'Euronext' and together with its subsidiaries, the 'Group') is a Dutch public company with limited liability (naamloze vennootschap), whose ordinary shares are admitted to listing and trading on regulated markets in the Netherlands, France, Belgium and Portugal.", "The applicable regulations with respect to public information and protection of investors, as well as the commitments made by the Company to securities and market authorities, are described in this Universal Registration Document (the 'Universal Registration Document')."]
["Euronext N.V. (the 'Company' or 'Euronext' and together with its subsidiaries, the 'Group') is a Dutch public company with limited liability (naamloze vennootschap), whose ordinary shares are admitted to listing and trading on regulated markets in the Netherlands, France, Belgium and Portugal. The applicable regulations with respect to public information and protection of investors, as well as the commitments made by the Company to securities and market authorities, are described in this Universal Registration Document (the 'Universal Registration Document')."]




In addition to historical information, this Universal Registration Document includes forward-looking statements.
['In addition to historical information, this Universal Registration Document includes forward-looking statements.']
['In addition to historical information, this Universal Registration Document includes forward-looking statements.']




The forward-looking statements are generally identifi  ed by the use of forward-looking words, such as 'anticipate', 'believe', 'estimate', 'expect', 'intend', 'plan', 'project', 'predict', 'target', 'will', 'should', 'may' or other variations of such terms, or by discussion of strategy. These statements relate to Euronext's future prospects, developments and business strategies and are based on analyses or forecasts of future results and estimates of amounts not yet determinable. These forward-looking statements represent the view of Euronext only as of the dates they are made, and Euronext disclaims any obligation to update forward-looking statements, except as may be otherwise required by law. The forward-looking statements in this Universal Registration Document involve known and unknown risks, uncertainties and other factors that could cause Euronext's actual future results, performance and achievements to diff   er materially from those forecasted or suggested herein. These include changes in general economic and business conditions, as well as the factors described in section  - Risk Factors of this Universal Registration Document  .
["The forward-looking statements are generally identifi ed by the use of forward-looking words, such as 'anticipate', 'believe', 'estimate', 'expect', 'intend', 'plan', 'project', 'predict', 'target', 'will', 'should', 'may' or other variations of such terms, or by discussion of strategy.", "These statements relate to Euronext's future prospects, developments and business strategies and are based on analyses or forecasts of future results and estimates of amounts not yet determinable.", 'These forward-looking statements represent the view of Euronext only as of the dates they are made, and Euronext disclaims any obligation to update forward-looking statements, except as may be otherwise required by law.', "The forward-looking statements in this Universal Registration Document involve known and unknown risks, uncertainties and other factors that could cause Euronext's actual future results, performance and achievements to diff er materially from those forecasted or suggested herein.", 'These include changes in general economic and business conditions, as well as the factors described in section - Risk Factors of this Universal Registration Document .']
["The forward-looking statements are generally identifi ed by the use of forward-looking words, such as 'anticipate', 'believe', 'estimate', 'expect', 'intend', 'plan', 'project', 'predict', 'target', 'will', 'should', 'may' or other variations of such terms, or by discussion of strategy. These statements relate to Euronext's future prospects, developments and business strategies and are based on analyses or forecasts of future results and estimates of amounts not yet determinable. These forward-looking statements represent the view of Euronext only as of the dates they are made, and Euronext disclaims any obligation to update forward-looking statements, except as may be otherwise required by law.", "The forward-looking statements in this Universal Registration Document involve known and unknown risks, uncertainties and other factors that could cause Euronext's actual future results, performance and achievements to diff er materially from those forecasted or suggested herein. These include changes in general economic and business conditions, as well as the factors described in section - Risk Factors of this Universal Registration Document ."]




This universal registration document has been fi  led with the Stichting Autoriteit Financiële Markten (the 'AFM') on 30 March 2023 as competent authority under Regulation (EU) 2017/1129 without prior approval pursuant to Article 9 of Regulation (EU) 2017/1129. This universal registration document may be used for the purposes of an off  er to the public of securities or admission of securities to trading on a regulated market if approved by the AFM together with any amendments, if applicable, and a securities note and summary approved in accordance with Regulation (EU) 2017/1129.
["This universal registration document has been fi led with the Stichting Autoriteit Financiële Markten (the 'AFM') on 30 March 2023 as competent authority under Regulation (EU) 2017/1129 without prior approval pursuant to Article 9 of Regulation (EU) 2017/1129.", 'This universal registration document may be used for the purposes of an off er to the public of securities or admission of securities to trading on a regulated market if approved by the AFM together with any amendments, if applicable, and a securities note and summary approved in accordance with Regulation (EU) 2017/1129.']
["This universal registration document has been fi led with the Stichting Autoriteit Financiële Markten (the 'AFM') on 30 March 2023 as competent authority under Regulation (EU) 2017/1129 without prior approval pursuant to Article 9 of Regulation (EU) 2017/1129. This universal registration document may be used for the purposes of an off er to the public of securities or admission of securities to trading on a regulated market if approved by the AFM together with any amendments, if applicable, and a securities note and summary approved in accordance with Regulation (EU) 2017/1129."]




This copy of the annual fi  nancial reporting of Euronext N.V. for the year ended 31 December 2022 is not presented in the ESEF-format as specifi  ed in the Regulatory Technical Standards on ESEF (Delegated Regulation (EU) 2019/815). The ESEF single reporting package is available at: https://www.euronext.com/en/investor-relations/fi  nancial-information/fi  nancial-reports.
['This copy of the annual fi nancial reporting of Euronext N.V. for the year ended 31 December 2022 is not presented in the ESEF-format as specifi ed in the Regulatory Technical Standards on ESEF (Delegated Regulation (EU) 2019/815).', 'The ESEF single reporting package is available at: https://www.euronext.com/en/investor-relations/fi nancial-information/fi nancial-reports.']
['This copy of the annual fi nancial reporting of Euronext N.V. for the year ended 31 December 2022 is not presented in the ESEF-format as specifi ed in the Regulatory Technical Standards on ESEF (Delegated Regulation (EU) 2019/815). The ESEF single reporting package is available at: https://www.euronext.com/en/investor-relations/fi nancial-information/fi nancial-reports.']




This year has been crucial in laying the foundations for the future growth of Euronext. We have successfully completed the fi  rst major milestone of our 'Growth for Impact 2024' strategic plan with the migration of our Core Data Centre. Our achievements in 2022 pave the way for the next steps to be delivered in 2023 and 2024.
['This year has been crucial in laying the foundations for the future growth of\xa0Euronext.', "We have successfully completed the fi rst major milestone of our 'Growth for Impact 2024' strategic plan with the migration of our Core Data Centre.", 'Our achievements in 2022 pave the way for the next steps to be delivered in 2023 and 2024.']
["This year has been crucial in laying the foundations for the future growth of\xa0Euronext. We have successfully completed the fi rst major milestone of our 'Growth for Impact 2024' strategic plan with the migration of our Core Data Centre. Our achievements in 2022 pave the way for the next steps to be delivered in 2023 and 2024."]




These are the critical bricks to complete our presence across the integrated value chain, allowing us to innovate and shape capital markets in line with evolving client needs, and making Euronext even stronger to deliver future growth.
['These are the critical bricks to complete our presence across the integrated value chain, allowing us to innovate and shape capital markets in line with evolving client needs, and making Euronext even stronger to deliver future growth.']
['These are the critical bricks to complete our presence across the integrated value chain, allowing us to innovate and shape capital markets in line with evolving client needs, and making Euronext even stronger to deliver future growth.']




2022 was a critical year for Euronext, and for Europe. The military invasion of Ukraine by Russia has demonstrated very clearly the need for reinforced European cooperation and a strengthened European Union. At Euronext, we are committed to our European roots and to our global ambitions. We know that cooperation across Europe is vital to secure prosperity and peace among the European nations that have pooled their destiny in common. The challenges our continent is facing is a reminder to us all of the common values we defend, as we continue to build the leading pan-European market infrastructure.
['2022 was a critical year for Euronext, and for Europe.', 'The military invasion of Ukraine by Russia has demonstrated very clearly the need for reinforced European cooperation and a strengthened European Union.', 'At Euronext, we are committed to our European roots and to our global ambitions.', 'We know that cooperation across Europe is vital to secure prosperity and peace among the European nations that have pooled their destiny in common.', 'The challenges our continent is facing is a reminder to us all of the common values we defend, as we continue to build the leading pan-European market infrastructure.']
['2022 was a critical year for Euronext, and for Europe. The military invasion of Ukraine by Russia has demonstrated very clearly the need for reinforced European cooperation and a strengthened European Union. At Euronext, we are committed to our European roots and to our global ambitions.', 'We know that cooperation across Europe is vital to secure prosperity and peace among the European nations that have pooled their destiny in common. The challenges our continent is facing is a reminder to us all of the common values we defend, as we continue to build the leading pan-European market infrastructure.']




In 2022, Euronext reached record revenue resulting from the strong performance of our nonvolume related activities, together with effi cient management of revenue capture and of cash trading market share. Thanks to our trademark cost discipline, we reported lower costs than our 2022 cost guidance. As a result, we achieved an adjusted EBITDA of € million, which translated into an adjusted EPS of €. Consequently, we will propose a total dividend of € million, or € per share, at our next annual general meeting to be held in May 2023.
['In 2022, Euronext reached record revenue resulting from the strong performance of our nonvolume related activities, together with effi cient management of revenue capture and of cash trading market share.', 'Thanks to our trademark cost discipline, we reported lower costs than our 2022 cost guidance.', 'As a result, we achieved an adjusted EBITDA of € million, which translated into an adjusted EPS of €.', 'Consequently, we will propose a total dividend of € million, or € per share, at our next annual general meeting to be held in May 2023.']
['In 2022, Euronext reached record revenue resulting from the strong performance of our nonvolume related activities, together with effi cient management of revenue capture and of cash trading market share. Thanks to our trademark cost discipline, we reported lower costs than our 2022 cost guidance. As a result, we achieved an adjusted EBITDA of € million, which translated into an adjusted EPS of €.', 'Consequently, we will propose a total dividend of € million, or € per share, at our next annual general meeting to be held in May 2023.']




We celebrated in April 2022 the one-year anniversary of the acquisition of the Borsa Italiana Group, a turning point in the history of Euronext. A lot has been accomplished and 2022 has been critical to the integration. We are proud that some of the key milestones of our 'Growth for Impact 2024' strategic plan have already been successfully completed. We also confi  rmed that all the Euronext strategic projects are progressing well. The migration of the Euronext Core Data Centre from Basildon in the United Kingdom to Bergamo in Italy on 6 June 2022 was one of our most strategic and ambitious projects. It was delivered smoothly, on schedule and on budget. 25% of the equity trading in Europe is now handled every day within our new green Core Data Centre located in the European Union.
['We celebrated in April 2022 the one-year anniversary of the acquisition of the Borsa Italiana Group, a turning point in the history of Euronext.', 'A lot has been accomplished and 2022 has been critical to the integration.', "We are proud that some of the key milestones of our 'Growth for Impact 2024' strategic plan have already been successfully completed.", 'We also confi rmed that all the Euronext strategic projects are progressing well.', 'The migration of the Euronext Core Data Centre from Basildon in the United Kingdom to Bergamo in Italy on 6 June 2022 was one of our most strategic and ambitious projects.', 'It was delivered smoothly, on schedule and on budget.', '25% of the equity trading in Europe is now handled every day within our new green Core Data Centre located in the European Union.']
["We celebrated in April 2022 the one-year anniversary of the acquisition of the Borsa Italiana Group, a turning point in the history of Euronext. A lot has been accomplished and 2022 has been critical to the integration. We are proud that some of the key milestones of our 'Growth for Impact 2024' strategic plan have already been successfully completed.", 'We also confi rmed that all the Euronext strategic projects are progressing well. The migration of the Euronext Core Data Centre from Basildon in the United Kingdom to Bergamo in Italy on 6 June 2022 was one of our most strategic and ambitious projects. It was delivered smoothly, on schedule and on budget.', '25% of the equity trading in Europe is now handled every day within our new green Core Data Centre located in the European Union.']




Throughout the year, we continued to consolidate our leadership position in the listing and trading of equities in Europe, and as the fi  rst debt listing venue worldwide. In 2022, Euronext welcomed 83 new equity listings to its seven listing venues across Europe, half of which were Tech companies. As part of the integration of the Borsa Italiana Group, we also introduced a new listing framework in Italy, harmonised with Group and global standards to simplify access to fi  nancing for local and international issuers.
['Throughout the year, we continued to consolidate our leadership position in the listing and trading of equities in Europe, and as the fi rst debt listing venue worldwide.', 'In 2022, Euronext welcomed 83 new equity listings to its seven listing venues across Europe, half of which were Tech companies.', 'As part of the integration of the Borsa Italiana Group, we also introduced a new listing framework in Italy, harmonised with Group and global standards to simplify access to fi nancing for local and international issuers.']
['Throughout the year, we continued to consolidate our leadership position in the listing and trading of equities in Europe, and as the fi rst debt listing venue worldwide. In 2022, Euronext welcomed 83 new equity listings to its seven listing venues across Europe, half of which were Tech companies. As part of the integration of the Borsa Italiana Group, we also introduced a new listing framework in Italy, harmonised with Group and global standards to simplify access to fi nancing for local and international issuers.']




In 2023, we will bring the Italian  markets to our single trading platform, Optiq®, creating the deepest liquidity pool in Europe, and strengthening the leading European listing platform. Euronext Clearing will become the clearing house of choice for Euronext cash equity markets in Q4 2023, and the clearing house for listed derivatives and commodities markets in Q3 2024. This strategic transformation will allow Euronext to directly manage these key client services and provide a harmonised and internalised clearing framework across all Euronext venues. Our good progress on the Borsa Italiana integration programme allowed us to upgrade our 2024 annual run- rate synergy targets to €115 million.
['In 2023, we will bring the Italian markets to our single trading platform, Optiq®, creating the deepest liquidity pool in Europe, and strengthening the leading European listing platform.', 'Euronext Clearing will become the clearing house of choice for Euronext cash equity markets in Q4 2023, and the clearing house for listed derivatives and commodities markets in Q3 2024.', 'This strategic transformation will allow Euronext to directly manage these key client services and provide a harmonised and internalised clearing framework across all Euronext venues.', 'Our good progress on the Borsa Italiana integration programme allowed us to upgrade our 2024 annual run- rate synergy targets to €115 million.']
['In 2023, we will bring the Italian markets to our single trading platform, Optiq®, creating the deepest liquidity pool in Europe, and strengthening the leading European listing platform. Euronext Clearing will become the clearing house of choice for Euronext cash equity markets in Q4 2023, and the clearing house for listed derivatives and commodities markets in Q3 2024. This strategic transformation will allow Euronext to directly manage these key client services and provide a harmonised and internalised clearing framework across all Euronext venues.', 'Our good progress on the Borsa Italiana integration programme allowed us to upgrade our 2024 annual run- rate synergy targets to €115 million.']





[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

# Try new filter, that only contains full sentence.

In [70]:
lines = []

for i in range(10): 
    with open(texts[i], "r") as f: 
            text = f.read()
    lines += text.split("\n")

In [71]:
lines = list(set(lines))

In [117]:
lines = ["## The 15 elements of Yara's Compliance Program",
"1. Culture and tone at the top: Strong, explicit, and visible support and commitment to our policies from Yara's directors and senior management.",
"2. Risk management/periodic risk-based review: Clearly defined responsibilities and authorities for the implementation and oversight of the Compliance Program and codes, policies, and procedures, and for reporting to independent monitoring bodies.",
"3. Compliance organization / proper oversight, independence and resources: Clearly defined responsibilities and authorities for the implementation and oversight of the Compliance Program and codes, policies, and procedures, and for reporting to independent monitoring bodies.",
]

In [118]:
accepted_lines = []
not_accepted_lines = []

is_image = lambda line: line == '<!-- image -->'
is_table = lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False

# drop if condidtion is True
conditions = [
    lambda line: line == '<!-- image -->',
    lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False, 
    lambda line: line.strip()[0] == "#" if len(line) > 0 else True,
    lambda line: "." not in line,
    
    # more than 50% is numbers
    lambda line: sum(ch.isalpha() for ch in line) / len(line) < 0.5,

    # minimum 3 words 
    lambda line: len(re.sub(r"[^a-zA-ZäöüÄÖÜß\s]", '', line).strip().split(" ")) < 3,

    # Minimum 2 Sentences
    #lambda line: sum([0 if len(sentence.split(" ")) < 3 else 1 for sentence in split_text_into_sentences(line, "en")]) < 2

]
accepted_lines = [line for line in lines if not any(condition(line) for condition in conditions)]
not_accepted_lines = [line for line in lines if any(condition(line) for condition in conditions)]

In [119]:
# Minimum 2 Sentences
min_2_sentence = lambda line: sum([0 if len(sentence.split(" ")) < 3 else 1 for sentence in split_text_into_sentences(line, "en")]) < 2

min_2_sentence("München den 16. März 2023")

True

In [120]:
df_accepted_lines = pd.DataFrame(accepted_lines, columns=["Line"])
df_accepted_lines["len"] = df_accepted_lines["Line"].apply(len)
df_accepted_lines.sort_values("len")

                                                Line  len
0  1. Culture and tone at the top: Strong, explic...  145
1  2. Risk management/periodic risk-based review:...  247
2  3. Compliance organization / proper oversight,...  275

In [121]:
df_not_accepted_lines = pd.DataFrame(not_accepted_lines, columns=["Line"])
df_not_accepted_lines["len"] = df_not_accepted_lines["Line"].apply(len)
df_not_accepted_lines.sort_values("len")

                                              Line  len
0  ## The 15 elements of Yara's Compliance Program   47

In [125]:
sentence_length = 3

for line in accepted_lines: 
        sentences = split_text_into_sentences(line, language='en')
        sentences = [sentence.strip() for sentence in sentences]
        sentences = [sentence for sentence in sentences if sentence != ""]
        new_chunks = [(" ".join(sentences[i:i+sentence_length])).strip() for i in range(0, len(sentences), 3)]
new_chunks

['3. Compliance organization / proper oversight, independence and resources: Clearly defined responsibilities and authorities for the implementation and oversight of the Compliance Program and codes, policies, and procedures, and for reporting to independent monitoring bodies.']